import { AlertTriangle, BadgeCheck, FileCheck2, Plus, ReceiptText } from "lucide-react";
import { notFound } from "next/navigation";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { adicionarItemConta, gerarGuiaTiss, validarContaTiss } from "@/modules/faturamento/actions";

function one<T>(rel: T | T[] | null): T | null { return Array.isArray(rel) ? rel[0] ?? null : rel; }

export default async function ContaPage({ params, searchParams }: { params: Promise<{ contaId: string }>; searchParams: Promise<{ erro?: string; validado?: string }> }) {
  const { contaId } = await params;
  const qs = await searchParams;
  const supabase = await createClient();
  const [{ data: conta }, { data: itens }, { data: criticas }] = await Promise.all([
    supabase.from("contas_faturamento").select("id,competencia,tipo_cobranca,status,valor_bruto,valor_liquido,atendimento:atendimentos(numero_atendimento,numero_carteirinha,cobertura),paciente:pacientes(nome_completo,ra,numero_registro,cns),convenio:convenios(nome_fantasia,registro_ans),plano:convenio_planos(nome)").eq("id", contaId).maybeSingle(),
    supabase.from("conta_faturamento_itens").select("id,origem_tipo,data_execucao,tabela,codigo,descricao,quantidade,valor_unitario,valor_total,setor,cobravel").eq("conta_id", contaId).order("created_at"),
    supabase.from("conta_faturamento_criticas").select("id,codigo,severidade,campo,mensagem,resolvida,created_at").eq("conta_id", contaId).order("created_at"),
  ]);
  if (!conta) notFound();
  const paciente=one(conta.paciente); const atendimento=one(conta.atendimento); const convenio=one(conta.convenio); const plano=one(conta.plano);
  const erros=(criticas ?? []).filter((c)=>!c.resolvida && c.severidade==="erro").length;
  const alertas=(criticas ?? []).filter((c)=>!c.resolvida && c.severidade==="alerta").length;
  const addItem = adicionarItemConta.bind(null, contaId);
  const validar = validarContaTiss.bind(null, contaId);
  const gerarGuia = gerarGuiaTiss.bind(null, contaId);
  return <SectionPage eyebrow="Financeiro / Faturamento / Conta" title={paciente?.nome_completo ?? "Conta"} description={`Atendimento #${atendimento?.numero_atendimento ?? "—"} · Registro #${paciente?.numero_registro ?? "—"} · ${paciente?.ra ?? "—"}`}>
    {qs.erro ? <div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">Não foi possível processar a operação. Revise a conta e as críticas.</div> : null}
    {qs.validado ? <div className="mb-4 rounded-xl border border-brand-100 bg-brand-50 px-4 py-3 text-sm text-brand-800">Validação concluída. Revise as críticas abaixo antes de gerar a guia.</div> : null}
    <div className="grid gap-4 md:grid-cols-4"><Info label="Status" value={conta.status.replaceAll("_"," ")}/><Info label="Competência" value={conta.competencia}/><Info label="Cobertura" value={conta.tipo_cobranca === "convenio" ? `${convenio?.nome_fantasia ?? "Convênio"} · ${plano?.nome ?? "Plano"}` : "Particular"}/><Info label="Valor líquido" value={`R$ ${Number(conta.valor_liquido ?? 0).toLocaleString("pt-BR", { minimumFractionDigits:2 })}`}/></div>
    {conta.status === "pronta" && conta.tipo_cobranca === "convenio" ? <form action={gerarGuia} className="mt-5 flex justify-end"><button className="ui-button-primary inline-flex items-center gap-2"><FileCheck2 className="size-4"/>Gerar guia TISS em rascunho</button></form> : null}
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
      <section className="ui-card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold text-slate-900">Itens faturáveis</h2><p className="text-sm text-slate-500">Procedimentos, materiais, medicamentos, taxas, diárias e honorários.</p></div><ReceiptText className="size-5 text-brand-700"/></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Tipo</th><th className="px-4 py-3">Tabela/Código</th><th className="px-4 py-3">Descrição</th><th className="px-4 py-3 text-right">Qtd.</th><th className="px-4 py-3 text-right">Total</th></tr></thead><tbody className="divide-y divide-slate-100">{itens?.length ? itens.map((item)=><tr key={item.id}><td className="px-4 py-3 text-slate-500">{item.origem_tipo}</td><td className="px-4 py-3 font-mono text-xs text-slate-600">{item.tabela || "—"} / {item.codigo || "—"}</td><td className="px-4 py-3"><p className="font-medium text-slate-900">{item.descricao}</p><p className="text-xs text-slate-400">{item.setor || "Sem setor"}</p></td><td className="px-4 py-3 text-right">{Number(item.quantidade)}</td><td className="px-4 py-3 text-right font-semibold">R$ {Number(item.valor_total).toLocaleString("pt-BR",{minimumFractionDigits:2})}</td></tr>) : <tr><td colSpan={5} className="px-4 py-8 text-center text-slate-500">Nenhum item faturável lançado.</td></tr>}</tbody></table></div></section>
      <section className="ui-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-slate-900">Críticas TISS</h2><p className="text-sm text-slate-500">{erros} erro(s) impeditivo(s) · {alertas} alerta(s)</p></div>{erros ? <AlertTriangle className="size-5 text-rose-600"/> : <BadgeCheck className="size-5 text-emerald-600"/>}</div><div className="mt-4 space-y-3">{criticas?.length ? criticas.map((c)=><div key={c.id} className={`rounded-xl border p-3 ${c.severidade === "erro" ? "border-rose-200 bg-rose-50" : "border-amber-200 bg-amber-50"}`}><div className="flex items-center justify-between"><strong className="text-xs">{c.codigo}</strong><span className="text-[11px] uppercase">{c.severidade}</span></div><p className="mt-1 text-sm text-slate-700">{c.mensagem}</p></div>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Execute a validação para gerar as críticas da conta.</p>}</div><form action={validar} className="mt-5"><button className="ui-button-primary w-full">Validar conta para TISS</button></form></section>
    </div>
    <form action={addItem} className="ui-card mt-6 p-6"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><Plus className="size-5"/></span><div><h2 className="font-semibold text-slate-900">Adicionar item faturável</h2><p className="text-sm text-slate-500">Use códigos e tabelas oficiais/contratuais. O item será criticado se faltar codificação.</p></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="space-y-2 text-sm font-medium text-slate-700"><span>Tipo *</span><select name="origem_tipo" className="ui-input"><option value="procedimento">Procedimento</option><option value="medicamento">Medicamento</option><option value="material">Material</option><option value="taxa">Taxa</option><option value="diaria">Diária</option><option value="honorario">Honorário</option><option value="laboratorio">Laboratório</option><option value="imagem">Imagem</option><option value="outro">Outro</option></select></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Tabela</span><input name="tabela" className="ui-input" placeholder="Ex.: 22"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Código</span><input name="codigo" className="ui-input" placeholder="Código TUSS/contratual"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Data execução</span><input type="datetime-local" name="data_execucao" className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700 md:col-span-2"><span>Descrição *</span><input name="descricao" required className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Quantidade *</span><input name="quantidade" defaultValue="1" inputMode="decimal" className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Valor unitário *</span><input name="valor_unitario" defaultValue="0,00" inputMode="decimal" className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Setor</span><input name="setor" className="ui-input" placeholder="Consultório, Centro Cirúrgico..."/></label></div><div className="mt-5 flex justify-end"><button className="ui-button-primary">Adicionar item</button></div></form>
  </SectionPage>;
}
function Info({label,value}:{label:string;value:string}){return <div className="ui-card p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 font-semibold text-slate-900">{value}</p></div>}
