import { AlertTriangle, BadgeCheck, FileCheck2, Layers3, Plus, ReceiptText } from "lucide-react";
import { notFound } from "next/navigation";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { adicionarItemConta, gerarGuiaTiss, validarContaTiss } from "@/modules/faturamento/actions";
import { atualizarGrupoAto, atualizarItemAto, criarGrupoAto, recalcularGrupoAto } from "@/modules/faturamento/atos-actions";

function one<T>(rel:T|T[]|null):T|null{return Array.isArray(rel)?rel[0]??null:rel;}
function brl(v:number|null|undefined){return `R$ ${Number(v??0).toLocaleString("pt-BR",{minimumFractionDigits:2})}`;}

export default async function ContaPage({params,searchParams}:{params:Promise<{contaId:string}>;searchParams:Promise<{erro?:string;validado?:string}>}){
 const {contaId}=await params; const qs=await searchParams; const supabase=await createClient();
 const [{data:conta},{data:itens},{data:criticas},{data:grupos}]=await Promise.all([
  supabase.from("contas_faturamento").select("id,competencia,tipo_cobranca,status,valor_bruto,valor_liquido,atendimento:atendimentos(numero_atendimento,numero_carteirinha,cobertura),paciente:pacientes(nome_completo,ra,numero_registro,cns),convenio:convenios(nome_fantasia,registro_ans),plano:convenio_planos(nome)").eq("id",contaId).maybeSingle(),
  supabase.from("conta_faturamento_itens").select("id,origem_tipo,data_execucao,tabela,codigo,descricao,quantidade,valor_unitario,valor_total,setor,cobravel,grupo_ato_id,sequencia_ato,via_acesso,anestesia,numero_auxiliares,filme_m2,percentual_aplicado,valor_contratual_calculado,metodologia_preco,memoria_calculo").eq("conta_id",contaId).order("created_at"),
  supabase.from("conta_faturamento_criticas").select("id,codigo,severidade,campo,mensagem,resolvida,created_at").eq("conta_id",contaId).order("created_at"),
  supabase.from("conta_faturamento_grupos_ato").select("id,codigo_grupo,data_ato,via_acesso,acomodacao,urgencia,horario_especial,observacoes").eq("conta_id",contaId).order("data_ato"),
 ]);
 if(!conta)notFound();
 const paciente=one(conta.paciente),atendimento=one(conta.atendimento),convenio=one(conta.convenio),plano=one(conta.plano);
 const erros=(criticas??[]).filter(c=>!c.resolvida&&c.severidade==="erro").length; const alertas=(criticas??[]).filter(c=>!c.resolvida&&c.severidade==="alerta").length;
 const addItem=adicionarItemConta.bind(null,contaId),validar=validarContaTiss.bind(null,contaId),gerarGuia=gerarGuiaTiss.bind(null,contaId),novoGrupo=criarGrupoAto.bind(null,contaId),saveGrupo=atualizarGrupoAto.bind(null,contaId),saveItem=atualizarItemAto.bind(null,contaId),recalcGrupo=recalcularGrupoAto.bind(null,contaId);
 return <SectionPage eyebrow="Financeiro / Faturamento / Conta" title={paciente?.nome_completo??"Conta"} description={`Atendimento #${atendimento?.numero_atendimento??"—"} · Registro #${paciente?.numero_registro??"—"} · ${paciente?.ra??"—"}`}>
  {qs.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">Não foi possível processar a operação: {qs.erro}.</div>:null}
  {qs.validado?<div className="mb-4 rounded-xl border border-brand-100 bg-brand-50 px-4 py-3 text-sm text-brand-800">Validação concluída. Revise as críticas antes de gerar a guia.</div>:null}
  <div className="grid gap-4 md:grid-cols-4"><Info label="Status" value={conta.status.replaceAll("_"," ")}/><Info label="Competência" value={conta.competencia}/><Info label="Cobertura" value={conta.tipo_cobranca==="convenio"?`${convenio?.nome_fantasia??"Convênio"} · ${plano?.nome??"Plano"}`:"Particular"}/><Info label="Valor líquido" value={brl(conta.valor_liquido)}/></div>
  {conta.status==="pronta"&&conta.tipo_cobranca==="convenio"?<form action={gerarGuia} className="mt-5 flex justify-end"><button className="ui-button-primary inline-flex items-center gap-2"><FileCheck2 className="size-4"/>Gerar guia TISS em rascunho</button></form>:null}

  <section className="ui-card mt-6 p-5"><div className="flex items-center gap-3"><Layers3 className="size-5 text-brand-700"/><div><h2 className="font-semibold">Atos cirúrgicos / SADT</h2><p className="text-sm text-slate-500">Agrupe procedimentos do mesmo ato e aplique sequência, via, urgência, acomodação e regras contratuais.</p></div></div>
   <form action={novoGrupo} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-6"><input name="codigo_grupo" required className="ui-input" placeholder="Ex.: CIR-001"/><input type="date" name="data_ato" className="ui-input"/><input name="via_acesso" className="ui-input" placeholder="Via principal"/><select name="acomodacao" className="ui-input"><option value="">Acomodação</option><option value="enfermaria">Enfermaria</option><option value="apartamento">Apartamento</option><option value="uti">UTI</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="urgencia"/>Urgência</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="horario_especial"/>Horário especial</label><input name="observacoes" className="ui-input md:col-span-2 xl:col-span-5" placeholder="Observações do ato"/><button className="ui-button-primary">Criar grupo</button></form>
   <div className="mt-5 space-y-4">{grupos?.length?grupos.map(g=>{const membros=(itens??[]).filter(i=>i.grupo_ato_id===g.id).sort((a,b)=>Number(a.sequencia_ato??99)-Number(b.sequencia_ato??99));return <article key={g.id} className="rounded-2xl border border-slate-200 p-4"><form action={saveGrupo} className="grid gap-3 lg:grid-cols-[1fr_140px_160px_160px_auto_auto_auto]"><input type="hidden" name="grupo_ato_id" value={g.id}/><div><b>{g.codigo_grupo}</b><p className="text-xs text-slate-400">{membros.length} item(ns) neste ato</p></div><input type="date" name="data_ato" defaultValue={g.data_ato??""} className="ui-input"/><input name="via_acesso" defaultValue={g.via_acesso??""} className="ui-input" placeholder="Via"/><select name="acomodacao" defaultValue={g.acomodacao??""} className="ui-input"><option value="">Acomodação</option><option value="enfermaria">Enfermaria</option><option value="apartamento">Apartamento</option><option value="uti">UTI</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="urgencia" defaultChecked={g.urgencia}/>Urgência</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="horario_especial" defaultChecked={g.horario_especial}/>Especial</label><button className="ui-button-secondary">Salvar ato</button></form>
    <div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-3 py-2">Seq.</th><th className="px-3 py-2">Procedimento</th><th className="px-3 py-2">Via</th><th className="px-3 py-2">Anestesia</th><th className="px-3 py-2">Aux.</th><th className="px-3 py-2">Filme</th><th className="px-3 py-2 text-right">Lançado</th><th className="px-3 py-2 text-right">Contratual</th></tr></thead><tbody>{membros.map(i=><tr key={i.id} className="border-t border-slate-100"><td className="px-3 py-2">{i.sequencia_ato??"—"}</td><td className="px-3 py-2"><b>{i.descricao}</b><div className="text-xs text-slate-400">{i.codigo} · {i.metodologia_preco||"sem cálculo"}</div></td><td className="px-3 py-2">{i.via_acesso||g.via_acesso||"—"}</td><td className="px-3 py-2">{i.anestesia?"Sim":"Não"}</td><td className="px-3 py-2">{i.numero_auxiliares??0}</td><td className="px-3 py-2">{i.filme_m2??0}</td><td className="px-3 py-2 text-right">{brl(i.valor_unitario)}</td><td className="px-3 py-2 text-right font-semibold">{brl(i.valor_contratual_calculado)}</td></tr>)}</tbody></table></div>
    <form action={recalcGrupo} className="mt-3 flex justify-end"><input type="hidden" name="grupo_ato_id" value={g.id}/><button className="ui-button-primary">Recalcular grupo</button></form></article>}):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Nenhum ato agrupado ainda.</p>}</div>
  </section>

  <div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
   <section className="ui-card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold text-slate-900">Itens faturáveis</h2><p className="text-sm text-slate-500">Configure o contexto do ato e compare valor lançado com valor contratual.</p></div><ReceiptText className="size-5 text-brand-700"/></div><div className="divide-y divide-slate-100">{itens?.length?itens.map(item=><form action={saveItem} key={item.id} className="grid gap-3 p-4 xl:grid-cols-[1.4fr_160px_90px_130px_110px_110px_auto]"><input type="hidden" name="item_id" value={item.id}/><div><b className="text-sm">{item.descricao}</b><p className="text-xs text-slate-400">{item.tabela||"—"}/{item.codigo||"—"} · lançado {brl(item.valor_unitario)} · contratual {brl(item.valor_contratual_calculado)}</p></div><select name="grupo_ato_id" defaultValue={item.grupo_ato_id??""} className="ui-input"><option value="">Sem grupo</option>{grupos?.map(g=><option key={g.id} value={g.id}>{g.codigo_grupo}</option>)}</select><input name="sequencia_ato" defaultValue={item.sequencia_ato??1} className="ui-input" placeholder="Seq."/><input name="via_acesso" defaultValue={item.via_acesso??""} className="ui-input" placeholder="Via"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="anestesia" defaultChecked={item.anestesia}/>Anestesia</label><input name="numero_auxiliares" defaultValue={item.numero_auxiliares??0} className="ui-input" placeholder="Aux."/><div className="flex gap-2"><input name="filme_m2" defaultValue={item.filme_m2??0} className="ui-input w-24" placeholder="Filme"/><button className="ui-button-secondary">Salvar</button></div></form>):<p className="p-6 text-sm text-slate-500">Nenhum item faturável lançado.</p>}</div></section>
   <section className="ui-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-slate-900">Críticas TISS</h2><p className="text-sm text-slate-500">{erros} erro(s) impeditivo(s) · {alertas} alerta(s)</p></div>{erros?<AlertTriangle className="size-5 text-rose-600"/>:<BadgeCheck className="size-5 text-emerald-600"/>}</div><div className="mt-4 space-y-3">{criticas?.length?criticas.map(c=><div key={c.id} className={`rounded-xl border p-3 ${c.severidade==="erro"?"border-rose-200 bg-rose-50":"border-amber-200 bg-amber-50"}`}><div className="flex items-center justify-between"><strong className="text-xs">{c.codigo}</strong><span className="text-[11px] uppercase">{c.severidade}</span></div><p className="mt-1 text-sm text-slate-700">{c.mensagem}</p></div>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Execute a validação para gerar as críticas.</p>}</div><form action={validar} className="mt-5"><button className="ui-button-primary w-full">Validar conta para TISS</button></form></section>
  </div>

  <form action={addItem} className="ui-card mt-6 p-6"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><Plus className="size-5"/></span><div><h2 className="font-semibold text-slate-900">Adicionar item faturável</h2><p className="text-sm text-slate-500">Use códigos/tabelas contratuais; depois vincule ao ato quando aplicável.</p></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="space-y-2 text-sm font-medium text-slate-700"><span>Tipo *</span><select name="origem_tipo" className="ui-input"><option value="procedimento">Procedimento</option><option value="medicamento">Medicamento</option><option value="material">Material</option><option value="taxa">Taxa</option><option value="diaria">Diária</option><option value="honorario">Honorário</option><option value="laboratorio">Laboratório</option><option value="imagem">Imagem</option><option value="outro">Outro</option></select></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Tabela</span><input name="tabela" className="ui-input" placeholder="Ex.: 22"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Código</span><input name="codigo" className="ui-input" placeholder="Código TUSS/contratual"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Data execução</span><input type="datetime-local" name="data_execucao" className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700 md:col-span-2"><span>Descrição *</span><input name="descricao" required className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Quantidade *</span><input name="quantidade" defaultValue="1" inputMode="decimal" className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Valor unitário *</span><input name="valor_unitario" defaultValue="0,00" inputMode="decimal" className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Setor</span><input name="setor" className="ui-input" placeholder="Consultório, Centro Cirúrgico..."/></label></div><div className="mt-5 flex justify-end"><button className="ui-button-primary">Adicionar item</button></div></form>
 </SectionPage>;
}
function Info({label,value}:{label:string;value:string}){return <div className="ui-card p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 font-semibold text-slate-900">{value}</p></div>}
