import Link from "next/link";
import { ClipboardCheck, HeartPulse, Siren, Stethoscope } from "lucide-react";
import { NursingEvolutionBackgroundForm } from "@/components/enfermagem/nursing-evolution-background-form";
import { SectionPage } from "@/components/painel/section-page";
import { getAssistencialContext } from "@/modules/assistencial/context";

export const dynamic = "force-dynamic";
export const revalidate = 0;

type Paciente={nome_completo:string|null;ra:string|null;numero_registro:string|null};
type Triagem={classificacao_risco:string|null;queixa_principal:string|null;pressao_arterial:string|null;frequencia_cardiaca:number|null;frequencia_respiratoria:number|null;saturacao_o2:number|null;temperatura_c:number|null;dor_escala:number|null;created_at:string|null};
type Atendimento={id:string;numero_atendimento:string|number|null;tipo_atendimento:string|null;origem:string|null;setor_atual:string|null;status:string;data_abertura:string|null;paciente:Paciente|Paciente[]|null;triagens:Triagem|Triagem[]|null};
type Prescricao={id:string;atendimento_id:string;tipo:string;item:string;dose:string|null;via:string|null;frequencia:string|null;horarios:unknown;status:string};
type Evolucao={id:string;atendimento_id:string;avaliacao:string|null;intervencoes:string|null;resposta:string|null;plano:string|null;assinado_em:string|null;profissional:{nome_completo:string}|{nome_completo:string}[]|null};
function one<T>(v:T|T[]|null){return Array.isArray(v)?v[0]??null:v;}
function fmt(v:string|null|undefined){return v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(v)):"—";}
function riscoClasse(r:string|null){const x=(r??"").toLowerCase();if(x.includes("vermel"))return "bg-rose-600 text-white";if(x.includes("laranja"))return "bg-orange-500 text-white";if(x.includes("amarel"))return "bg-amber-400 text-amber-950";if(x.includes("verde"))return "bg-emerald-500 text-white";if(x.includes("azul"))return "bg-blue-500 text-white";return "bg-slate-200 text-slate-700";}

export default async function EnfermagemPsPage({searchParams}:{searchParams:Promise<{sucesso?:string;erro?:string;risco?:string}>}){
 const sp=await searchParams; const {supabase,empresaId,unidadeId}=await getAssistencialContext();
 const q=supabase.from("atendimentos").select("id,numero_atendimento,tipo_atendimento,origem,setor_atual,status,data_abertura,paciente:pacientes(nome_completo,ra,numero_registro),triagens(classificacao_risco,queixa_principal,pressao_arterial,frequencia_cardiaca,frequencia_respiratoria,saturacao_o2,temperatura_c,dor_escala,created_at)").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).in("status",["aberto","em_espera","em_atendimento"]).or("tipo_atendimento.ilike.%urg%,tipo_atendimento.ilike.%pronto%,origem.ilike.%urg%,origem.ilike.%pronto%,setor_atual.ilike.%urg%,setor_atual.ilike.%pronto%").order("data_abertura");
 const {data:atData}=await q; let atendimentos=(atData??[]) as unknown as Atendimento[];
 if(sp.risco) atendimentos=atendimentos.filter(a=>(Array.isArray(a.triagens)?a.triagens.at(-1):a.triagens)?.classificacao_risco?.toLowerCase()===sp.risco?.toLowerCase());
 const ids=atendimentos.map(a=>a.id);
 const [pRes,eRes]=ids.length?await Promise.all([
  supabase.from("prescricoes").select("id,atendimento_id,tipo,item,dose,via,frequencia,horarios,status").in("atendimento_id",ids).eq("empresa_id",empresaId).eq("unidade_id",unidadeId).in("status",["ativa","assinada"]).order("created_at"),
  supabase.from("evolucoes_multiprofissionais").select("id,atendimento_id,avaliacao,intervencoes,resposta,plano,assinado_em,profissional:profissionais(nome_completo)").in("atendimento_id",ids).eq("empresa_id",empresaId).eq("unidade_id",unidadeId).eq("area","enfermagem").order("assinado_em",{ascending:false}),
 ]):[{data:[]},{data:[]}];
 const prescricoes=(pRes.data??[]) as unknown as Prescricao[]; const evolucoes=(eRes.data??[]) as unknown as Evolucao[];
 const riscos=[...new Set(atendimentos.map(a=>{const t=Array.isArray(a.triagens)?a.triagens.at(-1):a.triagens;return t?.classificacao_risco}).filter(Boolean))] as string[];
 return <SectionPage eyebrow="Assistencial / Enfermagem / Urgência" title="Enfermagem do Pronto-Socorro" description="Fila assistencial do PS com classificação de risco, triagem, prescrição, checagem e evolução de Enfermagem.">
  {sp.sucesso?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">Registro realizado com sucesso.</div>:null}{sp.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">Não foi possível concluir: {decodeURIComponent(sp.erro)}.</div>:null}
  <div className="mb-5 flex flex-wrap gap-2"><Link href="/assistencial/enfermagem/pronto-socorro" className="btn-secondary">Todos os riscos</Link>{riscos.map(r=><Link key={r} href={`/assistencial/enfermagem/pronto-socorro?risco=${encodeURIComponent(r)}`} className="btn-secondary">{r}</Link>)}<Link href="/assistencial/enfermagem/andares" className="btn-secondary">Andares</Link></div>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">Pacientes no PS</p><p className="mt-2 text-3xl font-black text-rose-700">{atendimentos.length}</p></div><div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">Prescrições ativas</p><p className="mt-2 text-3xl font-black text-emerald-700">{prescricoes.length}</p></div><div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">Com triagem</p><p className="mt-2 text-3xl font-black text-brand-700">{atendimentos.filter(a=>Boolean(a.triagens)).length}</p></div><div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">Evoluções</p><p className="mt-2 text-3xl font-black text-violet-700">{evolucoes.length}</p></div></section>
  <div className="mt-6 space-y-4">{atendimentos.map(a=>{const paciente=one(a.paciente);const triagem=Array.isArray(a.triagens)?a.triagens.at(-1)??null:a.triagens;const itens=prescricoes.filter(p=>p.atendimento_id===a.id);const ultima=evolucoes.find(e=>e.atendimento_id===a.id);return <article key={a.id} className="his-card p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Siren className="size-5 text-rose-600"/><h2 className="font-black text-slate-950">{paciente?.nome_completo??"Paciente"}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-black uppercase ${riscoClasse(triagem?.classificacao_risco??null)}`}>{triagem?.classificacao_risco??"Sem classificação"}</span></div><p className="mt-1 text-sm text-slate-600">Atend. #{a.numero_atendimento??"—"} · {a.setor_atual??a.tipo_atendimento??"Pronto-Socorro"} · entrada {fmt(a.data_abertura)}</p><p className="mt-1 text-xs text-slate-500">RA {paciente?.ra??"—"} · Registro {paciente?.numero_registro??"—"}</p>{triagem?.queixa_principal?<p className="mt-2 text-sm font-semibold text-slate-800">Queixa: {triagem.queixa_principal}</p>:null}</div><div className="flex flex-wrap gap-2"><Link href={`/assistencial/enfermagem?atendimento=${a.id}&retorno=${encodeURIComponent('/assistencial/enfermagem/pronto-socorro')}`} className="ui-button-primary"><ClipboardCheck className="size-4"/>Checar prescrição</Link><Link href={`/prontuario/${a.id}`} className="btn-secondary"><Stethoscope className="size-4"/>Prontuário</Link></div></div>
   {triagem?<div className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-6"><div className="rounded-lg bg-slate-50 p-2 text-xs"><b>PA</b><br/>{triagem.pressao_arterial??"—"}</div><div className="rounded-lg bg-slate-50 p-2 text-xs"><b>FC</b><br/>{triagem.frequencia_cardiaca??"—"}</div><div className="rounded-lg bg-slate-50 p-2 text-xs"><b>FR</b><br/>{triagem.frequencia_respiratoria??"—"}</div><div className="rounded-lg bg-slate-50 p-2 text-xs"><b>SpO₂</b><br/>{triagem.saturacao_o2??"—"}%</div><div className="rounded-lg bg-slate-50 p-2 text-xs"><b>Temp.</b><br/>{triagem.temperatura_c??"—"} °C</div><div className="rounded-lg bg-slate-50 p-2 text-xs"><b>Dor</b><br/>{triagem.dor_escala??"—"}/10</div></div>:null}
   <div className="mt-4 overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-3 py-2">Tipo</th><th className="px-3 py-2">Item</th><th className="px-3 py-2">Dose/Via</th><th className="px-3 py-2">Frequência</th><th className="px-3 py-2">Horários</th></tr></thead><tbody>{itens.length?itens.map(p=><tr key={p.id} className="border-t"><td className="px-3 py-2 font-bold">{p.tipo}</td><td className="px-3 py-2">{p.item}</td><td className="px-3 py-2">{[p.dose,p.via].filter(Boolean).join(" · ")||"—"}</td><td className="px-3 py-2">{p.frequencia??"—"}</td><td className="px-3 py-2">{Array.isArray(p.horarios)?p.horarios.join(", "):"—"}</td></tr>):<tr><td colSpan={5} className="px-3 py-5 text-center text-slate-500">Sem itens ativos.</td></tr>}</tbody></table></div>
   {ultima?<div className="mt-4 rounded-xl bg-violet-50 p-3 text-sm"><p className="font-black text-violet-900">Última evolução · {fmt(ultima.assinado_em)} · {one(ultima.profissional)?.nome_completo??"Enfermagem"}</p><p className="mt-1 text-violet-800">{ultima.avaliacao??ultima.intervencoes??ultima.resposta??ultima.plano??"—"}</p></div>:null}
   <details className="mt-4 rounded-xl border border-slate-200"><summary className="cursor-pointer px-4 py-3 font-black text-slate-800"><span className="inline-flex items-center gap-2"><HeartPulse className="size-4"/>Evoluir atendimento no PS</span></summary><NursingEvolutionBackgroundForm atendimentoId={a.id}><textarea name="avaliacao" className="ui-input min-h-24" placeholder="Avaliação de Enfermagem / estado atual"/><textarea name="intervencoes" className="ui-input min-h-24" placeholder="Intervenções e cuidados realizados"/><textarea name="resposta" className="ui-input min-h-24" placeholder="Resposta clínica / reavaliação"/><textarea name="plano" className="ui-input min-h-24" placeholder="Plano de Enfermagem / condutas pendentes"/></NursingEvolutionBackgroundForm></details>
  </article>})}{!atendimentos.length?<div className="his-card p-8 text-center text-sm text-slate-500">Nenhum atendimento ativo do Pronto-Socorro encontrado.</div>:null}</div>
 </SectionPage>;
}