import Link from "next/link";
import { Building2, ClipboardList, FileSearch, ShieldCheck, UsersRound } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { getAssistencialContext } from "@/modules/assistencial/context";
import { adicionarAchadoInLocoAction, adicionarAuditorExternoAction, atualizarStatusAuditoriaInLocoAction, criarAuditoriaInLocoAction, responderAchadoInLocoAction } from "@/modules/auditoria/in-loco-actions";

export const dynamic="force-dynamic";
export const revalidate=0;

type Auditor={id:string;nome:string;cargo:string|null;conselho:string|null;numero_conselho:string|null;empresa:string|null};
type Achado={id:string;categoria:string;codigo_glosa:string|null;descricao:string;valor_questionado:number|null;severidade:string;status:string;resposta_hospital:string|null;prazo_resposta:string|null};
type Auditoria={id:string;numero:number;operadora_nome:string;protocolo_operadora:string|null;escopo:string|null;data_inicio:string;data_fim_prevista:string|null;status:string;sala_local:string|null;auditores:Auditor[]|null;achados:Achado[]|null};
function money(v:number|null|undefined){return Number(v??0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
function when(v:string|null|undefined){return v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(v)):"—";}

export default async function AuditoriaInLocoPage({searchParams}:{searchParams:Promise<{sucesso?:string;erro?:string}>}){
 const sp=await searchParams;const {supabase,empresaId,unidadeId}=await getAssistencialContext();
 const {data}=await supabase.from("auditorias_in_loco").select("id,numero,operadora_nome,protocolo_operadora,escopo,data_inicio,data_fim_prevista,status,sala_local,auditores:auditoria_in_loco_auditores(id,nome,cargo,conselho,numero_conselho,empresa),achados:auditoria_in_loco_achados(id,categoria,codigo_glosa,descricao,valor_questionado,severidade,status,resposta_hospital,prazo_resposta)").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).order("data_inicio",{ascending:false}).limit(100);
 const auditorias=(data??[]) as unknown as Auditoria[];const abertas=auditorias.filter(a=>!['concluida','cancelada'].includes(a.status));const achados=auditorias.flatMap(a=>a.achados??[]);const questionado=achados.reduce((s,a)=>s+Number(a.valor_questionado??0),0);
 return <SectionPage eyebrow="Receita / Auditoria / Operadora" title="Auditoria In Loco" description="Controle da visita presencial da operadora, auditores externos, escopo, achados, glosas potenciais, respostas e encerramento.">
  <div className="mb-4 flex flex-wrap gap-2"><Link href="/auditoria" className="btn-secondary">← Auditoria de Contas</Link></div>
  {sp.sucesso?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">Operação concluída.</div>:null}{sp.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">Erro: {decodeURIComponent(sp.erro)}.</div>:null}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">Auditorias abertas</p><p className="mt-2 text-3xl font-black text-brand-700">{abertas.length}</p></div><div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">Achados</p><p className="mt-2 text-3xl font-black text-amber-700">{achados.length}</p></div><div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">Valor questionado</p><p className="mt-2 text-2xl font-black text-rose-700">{money(questionado)}</p></div><div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">Operadoras</p><p className="mt-2 text-3xl font-black text-violet-700">{new Set(auditorias.map(a=>a.operadora_nome)).size}</p></div></section>
  <details className="his-card mt-5"><summary className="cursor-pointer p-5 font-black"><span className="inline-flex items-center gap-2"><Building2 className="size-5"/>Nova auditoria in loco</span></summary><form action={criarAuditoriaInLocoAction} className="grid gap-3 border-t p-5 md:grid-cols-2 xl:grid-cols-3"><input name="operadora_nome" required className="ui-input" placeholder="Operadora / convênio"/><input name="protocolo_operadora" className="ui-input" placeholder="Protocolo / ofício"/><input name="sala_local" className="ui-input" placeholder="Sala / local da auditoria"/><label className="text-sm font-semibold">Início<input name="data_inicio" required type="datetime-local" className="ui-input mt-1"/></label><label className="text-sm font-semibold">Fim previsto<input name="data_fim_prevista" type="datetime-local" className="ui-input mt-1"/></label><textarea name="escopo" className="ui-input min-h-24 md:col-span-2 xl:col-span-3" placeholder="Escopo: internações, contas, período, especialidades, amostragem..."/><textarea name="observacoes" className="ui-input min-h-20 md:col-span-2 xl:col-span-3" placeholder="Observações de preparação"/><button className="ui-button-primary xl:col-span-3 xl:justify-self-end">Agendar auditoria</button></form></details>
  <div className="mt-5 space-y-4">{auditorias.map(a=>{const auditorExterno=a.auditores??[],itens=a.achados??[],abertosAchados=itens.filter(x=>!['revertido','encerrado'].includes(x.status));return <article key={a.id} className="his-card overflow-hidden"><div className="flex flex-col gap-4 border-b p-5 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-slate-950">#{a.numero} · {a.operadora_nome}</h2><span className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-black uppercase text-brand-700">{a.status.replaceAll('_',' ')}</span></div><p className="mt-1 text-sm text-slate-500">Início {when(a.data_inicio)} · fim previsto {when(a.data_fim_prevista)} · protocolo {a.protocolo_operadora??'—'}</p><p className="mt-2 text-sm text-slate-700">{a.escopo??'Sem escopo registrado.'}</p></div><form action={atualizarStatusAuditoriaInLocoAction} className="flex gap-2"><input type="hidden" name="id" value={a.id}/><select name="status" className="ui-input" defaultValue={a.status}><option value="agendada">Agendada</option><option value="em_andamento">Em andamento</option><option value="aguardando_resposta">Aguardando resposta</option><option value="em_contestacao">Em contestação</option><option value="concluida">Concluída</option><option value="cancelada">Cancelada</option></select><button className="btn-secondary">Atualizar</button></form></div>
   <div className="grid gap-4 p-5 xl:grid-cols-3"><section className="rounded-xl border p-4"><div className="flex items-center gap-2"><UsersRound className="size-4 text-violet-700"/><h3 className="font-black">Auditores da operadora</h3></div><div className="mt-3 space-y-2">{auditorExterno.map(x=><div key={x.id} className="rounded-lg bg-slate-50 p-2 text-sm"><b>{x.nome}</b><br/><span className="text-xs text-slate-500">{[x.cargo,x.conselho&&`${x.conselho} ${x.numero_conselho??''}`,x.empresa].filter(Boolean).join(' · ')}</span></div>)}</div><form action={adicionarAuditorExternoAction} className="mt-3 space-y-2"><input type="hidden" name="auditoria_id" value={a.id}/><input name="nome" required className="ui-input" placeholder="Nome do auditor"/><div className="grid grid-cols-2 gap-2"><input name="cargo" className="ui-input" placeholder="Cargo"/><input name="empresa" className="ui-input" placeholder="Empresa"/><input name="conselho" className="ui-input" placeholder="Conselho"/><input name="numero_conselho" className="ui-input" placeholder="Registro"/></div><button className="btn-secondary w-full">Adicionar auditor</button></form></section>
   <section className="rounded-xl border p-4 xl:col-span-2"><div className="flex items-center gap-2"><FileSearch className="size-4 text-amber-700"/><h3 className="font-black">Achados e glosas potenciais</h3></div><div className="mt-3 space-y-3">{itens.map(x=><div key={x.id} className="rounded-xl border border-amber-100 bg-amber-50/50 p-3"><div className="flex flex-wrap justify-between gap-2"><div><p className="text-xs font-black uppercase text-amber-800">{x.categoria} · {x.severidade} {x.codigo_glosa?`· ${x.codigo_glosa}`:''}</p><p className="mt-1 text-sm font-semibold">{x.descricao}</p></div><b className="text-rose-700">{money(x.valor_questionado)}</b></div>{x.resposta_hospital?<p className="mt-2 rounded-lg bg-white p-2 text-xs text-slate-700">Resposta: {x.resposta_hospital}</p>:<form action={responderAchadoInLocoAction} className="mt-2 flex gap-2"><input type="hidden" name="id" value={x.id}/><input name="resposta_hospital" required className="ui-input flex-1" placeholder="Resposta/contestação do hospital"/><button className="btn-secondary">Responder</button></form>}</div>)}</div><details className="mt-3 rounded-xl border"><summary className="cursor-pointer px-3 py-2 text-sm font-black">+ Registrar achado</summary><form action={adicionarAchadoInLocoAction} className="grid gap-2 border-t p-3 md:grid-cols-2"><input type="hidden" name="auditoria_id" value={a.id}/><input name="categoria" required className="ui-input" placeholder="Categoria: prontuário, cobrança, autorização..."/><input name="codigo_glosa" className="ui-input" placeholder="Código glosa TISS"/><textarea name="descricao" required className="ui-input min-h-20 md:col-span-2" placeholder="Descrição do achado"/><textarea name="fundamentacao" className="ui-input min-h-20 md:col-span-2" placeholder="Fundamentação contratual/TISS/regra da operadora"/><input name="valor_questionado" className="ui-input" placeholder="Valor questionado"/><select name="severidade" className="ui-input" defaultValue="media"><option value="baixa">Baixa</option><option value="media">Média</option><option value="alta">Alta</option><option value="critica">Crítica</option></select><label className="text-sm font-semibold">Prazo de resposta<input name="prazo_resposta" type="datetime-local" className="ui-input mt-1"/></label><button className="ui-button-primary md:self-end">Registrar achado</button></form></details><div className="mt-3 text-xs font-semibold text-slate-500"><ClipboardList className="mr-1 inline size-3"/>{abertosAchados.length} achado(s) ainda em tratamento</div></section></div>
  </article>})}{!auditorias.length?<div className="his-card p-8 text-center text-slate-500"><ShieldCheck className="mx-auto mb-2 size-5"/>Nenhuma auditoria in loco cadastrada.</div>:null}</div>
 </SectionPage>;
}
