import Link from "next/link";
import { Activity, Cable, CircleDot, FlaskConical, MonitorCog, Network, RadioTower, Stethoscope } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { getAssistencialContext } from "@/modules/assistencial/context";
import { registrarTesteIntegracaoAction, salvarIntegracaoEquipamentoAction, vincularEquipamentoLaboratorioAction, vincularEquipamentoSalaAction } from "@/modules/engenharia-clinica/integracoes-actions";

export const dynamic = "force-dynamic";
export const revalidate = 0;

type Equipamento = { id:string; patrimonio:string; nome:string; categoria:string; status:string; setor_id:string|null };
type Integracao = { id:string; equipamento_id:string; sistema_origem:string; tipo_integracao:string; protocolo:string|null; host:string|null; porta:number|null; ae_title:string|null; modalidade_dicom:string|null; endpoint:string|null; identificador_externo:string|null; ativo:boolean; status:string; ultimo_contato_em:string|null; ultima_falha_em:string|null; ultima_mensagem:string|null; equipamento:Equipamento|Equipamento[]|null };
type Lab = { id:string; codigo:string; nome:string; fabricante:string|null; modelo:string|null; protocolo_interface:string|null; endereco_interface:string|null; engenharia_equipamento_id:string|null };
type Sala = { id:string; codigo:string; nome:string; tipo:string|null; status:string|null };
type SalaVinculo = { id:string; sala_cirurgica_id:string; equipamento_id:string; obrigatorio:boolean; principal:boolean; sala:Sala|Sala[]|null; equipamento:Equipamento|Equipamento[]|null };
function one<T>(v:T|T[]|null){return Array.isArray(v)?v[0]??null:v;}
function fmt(v:string|null|undefined){return v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(v)):"—";}
function tone(s:string){const x=s.toLowerCase();if(["ok","online","operacional","ativo"].includes(x))return "bg-emerald-50 text-emerald-700";if(["falha","offline","indisponivel"].includes(x))return "bg-rose-50 text-rose-700";return "bg-amber-50 text-amber-700";}

export default async function IntegracoesEquipamentosPage({searchParams}:{searchParams:Promise<{sucesso?:string;erro?:string}>}){
  const sp=await searchParams;
  const {supabase,empresaId,unidadeId}=await getAssistencialContext();
  const [perm,equipRes,intRes,labRes,salasRes,vincRes]=await Promise.all([
    supabase.rpc("tem_permissao",{p_empresa:empresaId,p_unidade:unidadeId,p_codigo:"engenharia_clinica.gerenciar"}),
    supabase.from("engenharia_equipamentos").select("id,patrimonio,nome,categoria,status,setor_id").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).order("nome"),
    supabase.from("engenharia_integracoes_equipamentos").select("id,equipamento_id,sistema_origem,tipo_integracao,protocolo,host,porta,ae_title,modalidade_dicom,endpoint,identificador_externo,ativo,status,ultimo_contato_em,ultima_falha_em,ultima_mensagem,equipamento:engenharia_equipamentos(id,patrimonio,nome,categoria,status,setor_id)").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).order("sistema_origem"),
    supabase.from("laboratorio_equipamentos").select("id,codigo,nome,fabricante,modelo,protocolo_interface,endereco_interface,engenharia_equipamento_id").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).order("nome"),
    supabase.from("salas_cirurgicas").select("id,codigo,nome,tipo,status").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).eq("ativo",true).order("nome"),
    supabase.from("engenharia_sala_equipamentos").select("id,sala_cirurgica_id,equipamento_id,obrigatorio,principal,sala:salas_cirurgicas(id,codigo,nome,tipo,status),equipamento:engenharia_equipamentos(id,patrimonio,nome,categoria,status,setor_id)").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).eq("ativo",true),
  ]);
  const canManage=perm.data===true;
  const equipamentos=(equipRes.data??[]) as Equipamento[];
  const integracoes=(intRes.data??[]) as unknown as Integracao[];
  const labs=(labRes.data??[]) as Lab[];
  const salas=(salasRes.data??[]) as Sala[];
  const vinculos=(vincRes.data??[]) as unknown as SalaVinculo[];
  const falhas=integracoes.filter(i=>["falha","offline"].includes(i.status));
  return <SectionPage eyebrow="Engenharia Clínica / Integrações" title="Integrações com equipamentos" description="Vínculo do patrimônio hospitalar com analisadores, modalidades DICOM, equipamentos de salas e interfaces HL7/ASTM/DICOM.">
    <div className="mb-4"><Link href="/engenharia-clinica" className="text-sm font-bold text-brand-700">← Voltar à Engenharia Clínica</Link></div>
    {sp.sucesso?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">Operação concluída: {sp.sucesso.replaceAll("_"," ")}.</div>:null}
    {sp.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">Erro: {decodeURIComponent(sp.erro)}.</div>:null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Equipamentos" value={equipamentos.length}/><Kpi label="Integrações" value={integracoes.length}/><Kpi label="Falhas/offline" value={falhas.length} danger={falhas.length>0}/><Kpi label="Salas vinculadas" value={new Set(vinculos.map(v=>v.sala_cirurgica_id)).size}/></section>

    {canManage?<section className="mt-5 grid gap-5 xl:grid-cols-2">
      <form action={salvarIntegracaoEquipamentoAction} className="his-card grid gap-3 p-5 md:grid-cols-2"><div className="md:col-span-2"><h2 className="flex items-center gap-2 font-black"><Cable className="size-5"/>Cadastrar interface</h2><p className="text-sm text-slate-500">HL7, ASTM, DICOM, API ou integração serial/TCP.</p></div><select name="equipamento_id" required className="ui-input md:col-span-2" defaultValue=""><option value="">Equipamento *</option>{equipamentos.map(e=><option key={e.id} value={e.id}>{e.patrimonio} · {e.nome}</option>)}</select><select name="sistema_origem" className="ui-input" defaultValue="laboratorio"><option value="laboratorio">Laboratório</option><option value="imagem">Imagem / PACS</option><option value="centro_cirurgico">Centro Cirúrgico</option><option value="uti">UTI / monitorização</option><option value="dialise">Diálise</option><option value="outro">Outro</option></select><select name="tipo_integracao" className="ui-input" defaultValue="bidirecional"><option value="bidirecional">Bidirecional</option><option value="entrada">Entrada de dados</option><option value="saida">Saída de dados</option><option value="monitoramento">Monitoramento</option></select><input name="protocolo" className="ui-input" placeholder="Protocolo: HL7, ASTM, DICOM..."/><input name="identificador_externo" className="ui-input" placeholder="ID externo / código no equipamento"/><input name="host" className="ui-input" placeholder="Host / IP"/><input name="porta" type="number" className="ui-input" placeholder="Porta"/><input name="ae_title" className="ui-input" placeholder="AE Title DICOM"/><input name="modalidade_dicom" className="ui-input" placeholder="Modalidade: CT, MR, CR..."/><input name="endpoint" className="ui-input md:col-span-2" placeholder="Endpoint / URL / caminho da interface"/><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="ativo" defaultChecked/>Integração ativa</label><button className="ui-button-primary md:justify-self-end"><Network className="size-4"/>Salvar integração</button></form>

      <div className="his-card p-5"><h2 className="flex items-center gap-2 font-black"><FlaskConical className="size-5"/>Vincular analisador do Laboratório</h2><form action={vincularEquipamentoLaboratorioAction} className="mt-4 grid gap-3"><select name="laboratorio_equipamento_id" required className="ui-input" defaultValue=""><option value="">Equipamento do LIS *</option>{labs.map(l=><option key={l.id} value={l.id}>{l.codigo} · {l.nome} · {l.fabricante??""} {l.modelo??""}</option>)}</select><select name="equipamento_id" required className="ui-input" defaultValue=""><option value="">Patrimônio da Engenharia Clínica *</option>{equipamentos.map(e=><option key={e.id} value={e.id}>{e.patrimonio} · {e.nome}</option>)}</select><button className="ui-button-primary justify-self-end"><Stethoscope className="size-4"/>Vincular</button></form><div className="mt-4 space-y-2 text-sm">{labs.map(l=><div key={l.id} className="rounded-xl border p-3"><b>{l.codigo} · {l.nome}</b><p className="text-xs text-slate-500">Interface {l.protocolo_interface??"—"} · {l.endereco_interface??"—"} · patrimônio: {l.engenharia_equipamento_id?"vinculado":"não vinculado"}</p></div>)}</div></div>

      <div className="his-card p-5 xl:col-span-2"><h2 className="flex items-center gap-2 font-black"><MonitorCog className="size-5"/>Equipamentos por sala cirúrgica</h2><form action={vincularEquipamentoSalaAction} className="mt-4 grid gap-3 md:grid-cols-4"><select name="sala_cirurgica_id" required className="ui-input" defaultValue=""><option value="">Sala *</option>{salas.map(s=><option key={s.id} value={s.id}>{s.codigo} · {s.nome}</option>)}</select><select name="equipamento_id" required className="ui-input" defaultValue=""><option value="">Equipamento *</option>{equipamentos.map(e=><option key={e.id} value={e.id}>{e.patrimonio} · {e.nome}</option>)}</select><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="principal"/>Principal</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="obrigatorio"/>Obrigatório</label><button className="ui-button-primary md:col-span-4 md:justify-self-end">Vincular à sala</button></form><div className="mt-4 grid gap-2 md:grid-cols-2">{vinculos.map(v=>{const s=one(v.sala),e=one(v.equipamento);return <div key={v.id} className="rounded-xl border p-3 text-sm"><b>{s?.nome??"Sala"} · {e?.patrimonio} {e?.nome}</b><p className="text-xs text-slate-500">{v.principal?"Principal · ":""}{v.obrigatorio?"Obrigatório · ":""}status {e?.status??"—"}</p></div>})}</div></div>
    </section>:null}

    <section className="mt-5"><h2 className="mb-3 flex items-center gap-2 font-black"><RadioTower className="size-5"/>Saúde das integrações</h2><div className="space-y-3">{integracoes.map(i=>{const e=one(i.equipamento);return <article key={i.id} className="his-card p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><b>{e?.patrimonio} · {e?.nome}</b><span className={`rounded-full px-2 py-1 text-xs font-black ${tone(i.status)}`}>{i.status}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{i.sistema_origem} · {i.protocolo??i.tipo_integracao}</span></div><p className="mt-2 text-sm text-slate-600">{i.host??i.endpoint??"Sem endereço"}{i.porta?`:${i.porta}`:""} {i.ae_title?`· AE ${i.ae_title}`:""}</p><p className="mt-1 text-xs text-slate-400">Último contato {fmt(i.ultimo_contato_em)} · última falha {fmt(i.ultima_falha_em)} · {i.ultima_mensagem??"sem mensagem"}</p></div>{canManage?<form action={registrarTesteIntegracaoAction} className="flex flex-wrap gap-2"><input type="hidden" name="integracao_id" value={i.id}/><select name="status" className="ui-input" defaultValue="ok"><option value="ok">Teste OK</option><option value="falha">Falha</option><option value="offline">Offline</option></select><input name="mensagem" className="ui-input" placeholder="Retorno do teste"/><button className="ui-button-primary"><Activity className="size-4"/>Registrar teste</button></form>:null}</div></article>})}{!integracoes.length?<div className="his-card p-8 text-center text-sm text-slate-500"><CircleDot className="mx-auto mb-2 size-5"/>Nenhuma integração configurada.</div>:null}</div></section>
  </SectionPage>;
}

function Kpi({label,value,danger=false}:{label:string;value:number;danger?:boolean}){return <div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">{label}</p><p className={`mt-2 text-3xl font-black ${danger?"text-rose-700":"text-slate-950"}`}>{value}</p></div>}
