import Link from "next/link";
import { FileCheck2, ShieldAlert } from "lucide-react";
import { notFound } from "next/navigation";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { atualizarChecklistContaMedica, gerarChecklistContaMedica, liberarContaMedica } from "@/modules/corporativo/actions";
function one<T>(r:T|T[]|null){return Array.isArray(r)?r[0]??null:r;}
export default async function ContaMedicaDetalhe({params,searchParams}:{params:Promise<{processoId:string}>;searchParams:Promise<{erro?:string}>}){
 const {processoId}=await params; const qs=await searchParams; const supabase=await createClient();
 const [{data:p},{data:checklist},{data:pendencias},{data:docs}]=await Promise.all([
  supabase.from("contas_medicas_processos").select("id,status,conta_id,total_conta,total_autorizado,total_nao_autorizado,observacoes,atendimento:atendimentos(numero_atendimento),paciente:pacientes(nome_completo,ra,numero_registro),convenio:convenios(nome_fantasia),conta:contas_faturamento(id,competencia,auditoria_liberada,contas_medicas_liberada)").eq("id",processoId).maybeSingle(),
  supabase.from("contas_medicas_checklist_itens").select("id,codigo,descricao,obrigatorio,categoria_documento,status,ged_documento_id,observacoes").eq("processo_id",processoId).order("codigo"),
  supabase.from("contas_medicas_pendencias").select("id,tipo,severidade,descricao,resolvida").eq("processo_id",processoId).order("created_at",{ascending:false}),
  supabase.from("ged_documentos").select("id,titulo,categoria,nome_arquivo").eq("conta_faturamento_id",(await supabase.from("contas_medicas_processos").select("conta_id").eq("id",processoId).maybeSingle()).data?.conta_id??"").eq("status","ativo").order("created_at",{ascending:false})
 ]);
 if(!p) notFound(); const pac=one(p.paciente),at=one(p.atendimento),conv=one(p.convenio),conta=one(p.conta); const gerar=gerarChecklistContaMedica; const liberar=liberarContaMedica;
 return <SectionPage eyebrow="Receita / Contas Médicas" title={pac?.nome_completo??"Conta médica"} description={`Atendimento #${at?.numero_atendimento??"—"} · Registro #${pac?.numero_registro??"—"} · ${pac?.ra??"—"} · ${conv?.nome_fantasia??"Particular"}`}>
  {qs.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">Não foi possível liberar/processar: {qs.erro}.</div>:null}
  <div className="grid gap-4 md:grid-cols-4"><Info l="Competência" v={conta?.competencia??"—"}/><Info l="Total conta" v={`R$ ${Number(p.total_conta||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}`}/><Info l="Não autorizado" v={`R$ ${Number(p.total_nao_autorizado||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}`}/><Info l="Status" v={String(p.status).replaceAll("_"," ")}/></div>
  <section className="ui-card mt-6 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><FileCheck2 className="size-5 text-brand-700"/><div><h2 className="font-semibold">Checklist documental</h2><p className="text-sm text-slate-500">Itens obrigatórios devem estar OK ou Não aplicável antes da liberação TISS.</p></div></div>{!checklist?.length?<form action={gerar}><input type="hidden" name="processo_id" value={processoId}/><button className="ui-button-primary">Gerar checklist</button></form>:null}</div>
   <div className="mt-4 space-y-3">{checklist?.length?checklist.map(i=><form key={i.id} action={atualizarChecklistContaMedica} className="grid gap-3 rounded-xl border border-slate-200 p-4 lg:grid-cols-[1.4fr_180px_1fr_auto]"><input type="hidden" name="item_id" value={i.id}/><input type="hidden" name="processo_id" value={processoId}/><div><b className="text-sm">{i.codigo} · {i.descricao}</b><p className="mt-1 text-xs text-slate-500">{i.obrigatorio?"Obrigatório":"Opcional"}{i.categoria_documento?` · GED: ${i.categoria_documento}`:""}</p></div><select name="status" defaultValue={i.status} className="ui-input"><option value="pendente">Pendente</option><option value="ok">OK</option><option value="nao_aplicavel">Não aplicável</option><option value="divergente">Divergente</option></select><select name="ged_documento_id" defaultValue={i.ged_documento_id??""} className="ui-input"><option value="">Sem documento vinculado</option>{docs?.map(d=><option key={d.id} value={d.id}>{d.titulo}</option>)}</select><button className="ui-button-secondary">Salvar</button></form>):<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Checklist ainda não gerado.</p>}</div>
  </section>
  <section className="ui-card mt-6 p-5"><div className="flex items-center gap-2"><ShieldAlert className="size-5 text-amber-600"/><h2 className="font-semibold">Pendências</h2></div><div className="mt-4 space-y-2">{pendencias?.length?pendencias.map(x=><div key={x.id} className={`rounded-xl border p-3 text-sm ${x.resolvida?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><b className="capitalize">{x.severidade} · {x.tipo}</b><p>{x.descricao}</p></div>):<p className="text-sm text-slate-500">Nenhuma pendência registrada.</p>}</div></section>
  <div className="mt-6 flex flex-wrap gap-3"><Link href={`/faturamento/${p.conta_id}`} className="ui-button-secondary">Abrir conta</Link><Link href={`/ged?conta=${p.conta_id}`} className="ui-button-secondary">Abrir GED</Link><form action={liberar}><input type="hidden" name="processo_id" value={processoId}/><button className="ui-button-primary">Liberar para TISS</button></form></div>
 </SectionPage>;
}
function Info({l,v}:{l:string;v:string}){return <div className="ui-card p-4"><p className="text-xs uppercase text-slate-400">{l}</p><p className="mt-2 font-semibold capitalize">{v}</p></div>}
