import { AlertTriangle, FlaskConical, Microscope, PackageCheck, RefreshCw, TestTube2 } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { getAssistencialContext } from "@/modules/assistencial/context";
import { atualizarStatusAmostraLaboratorio, liberarResultadoLaboratorio, notificarResultadoCriticoLaboratorio, prepararAmostraLaboratorio, registrarResultadoLaboratorio } from "@/modules/assistencial/laboratorio-actions";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const fmt = (v?: string | null) => v ? new Date(v).toLocaleString("pt-BR") : "—";
const one = (v: any) => Array.isArray(v) ? v[0] ?? null : v;

export default async function LaboratorioPage({ searchParams }: { searchParams: Promise<{ sucesso?: string; erro?: string }> }) {
  const sp = await searchParams;
  const { supabase, unidadeId, empresaId } = await getAssistencialContext();
  const [solReq, amReq, resReq, analReq, equipReq] = await Promise.all([
    supabase.from("solicitacoes_exames").select("id,atendimento_id,exame,codigo_tuss,prioridade,status,created_at,atendimento:atendimentos(numero_atendimento,paciente:pacientes(nome_completo,ra,numero_registro))").eq("unidade_id", unidadeId).ilike("modalidade", "%laborat%").in("status", ["solicitado","coleta","processamento"]).order("created_at", { ascending: false }).limit(100),
    supabase.from("laboratorio_amostras").select("id,solicitacao_id,atendimento_id,codigo_amostra,accession_number,material,recipiente,prioridade,status,coleta_prevista_em,coletada_em,recebida_em,rejeitada_motivo,solicitacao:solicitacoes_exames(exame),atendimento:atendimentos(numero_atendimento,paciente:pacientes(nome_completo))").eq("unidade_id", unidadeId).order("created_at", { ascending: false }).limit(120),
    supabase.from("laboratorio_resultados").select("id,amostra_id,analito,resultado,valor_numerico,unidade_medida,flag,criticidade,valor_critico,liberado,liberado_em,notificado_em,notificado_a,created_at,engenharia:engenharia_equipamentos(patrimonio,nome),atendimento:atendimentos(numero_atendimento,paciente:pacientes(nome_completo))").eq("unidade_id", unidadeId).order("created_at", { ascending: false }).limit(150),
    supabase.from("laboratorio_catalogo_analitos").select("id,analito,codigo,unidade_medida,exame:laboratorio_catalogo_exames(descricao,codigo)").eq("empresa_id", empresaId).eq("ativo", true).order("analito").limit(1000),
    supabase.from("laboratorio_equipamentos").select("id,codigo,nome,fabricante,modelo,ativo,engenharia_equipamento_id,engenharia:engenharia_equipamentos(patrimonio,nome,status)").eq("empresa_id", empresaId).eq("unidade_id", unidadeId).eq("ativo", true).order("nome"),
  ]);
  const solicitacoes = (solReq.data ?? []) as any[];
  const amostras = (amReq.data ?? []) as any[];
  const resultados = (resReq.data ?? []) as any[];
  const analitos = (analReq.data ?? []) as any[];
  const equipamentos = (equipReq.data ?? []) as any[];
  const criticosAbertos = resultados.filter((r) => r.valor_critico && !r.notificado_em);
  const equipamentosDisponiveis = equipamentos.filter((e) => { const eng = one(e.engenharia); return !eng || ["operacional","reserva"].includes(eng.status); });

  return <SectionPage eyebrow="Assistencial / Apoio diagnóstico" title="Laboratório Clínico" description="Coleta rastreável, accession, cadeia da amostra, analisador integrado, resultados estruturados, criticidade, liberação e comunicação com read-back.">
    {sp.sucesso ? <div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">Operação concluída: {sp.sucesso}.</div> : null}
    {sp.erro ? <div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">Falha: {decodeURIComponent(sp.erro)}.</div> : null}

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      {[["Solicitações", solicitacoes.length, FlaskConical],["Amostras em fluxo", amostras.filter((a)=>!["rejeitada"].includes(a.status)).length, TestTube2],["Resultados", resultados.length, Microscope],["Analisadores disponíveis", equipamentosDisponiveis.length, Microscope],["Críticos sem comunicação", criticosAbertos.length, AlertTriangle]].map(([label,value,Icon]: any) => <div key={label} className="his-kpi"><div className="flex items-center justify-between"><p className="text-xs font-black uppercase tracking-wider text-slate-400">{label}</p><Icon className="size-5 text-brand-600"/></div><p className="mt-2 text-3xl font-black text-brand-950">{value}</p></div>)}
    </section>

    <section className="mt-5 grid gap-5 xl:grid-cols-[0.9fr_1.1fr]">
      <div className="his-card p-6"><div className="mb-4 flex items-center gap-3"><FlaskConical className="size-5 text-brand-700"/><div><h2 className="font-black">Solicitações aguardando coleta</h2><p className="text-sm text-slate-500">Gere etiqueta e accession sem perder o vínculo com o atendimento.</p></div></div><div className="space-y-3">{solicitacoes.length ? solicitacoes.map((s) => { const a=one(s.atendimento); const p=one(a?.paciente); return <form key={s.id} action={prepararAmostraLaboratorio} className="rounded-2xl border border-slate-100 p-4"><input type="hidden" name="solicitacao_id" value={s.id}/><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black text-slate-900">{s.exame}</p><p className="text-xs text-slate-500">{p?.nome_completo ?? "Paciente"} · Atend. #{a?.numero_atendimento ?? "—"} · {s.prioridade}</p></div><span className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-bold text-brand-700">{s.status}</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><input name="material" className="ui-input" placeholder="Material"/><input name="recipiente" className="ui-input" placeholder="Recipiente"/><select name="prioridade" defaultValue={s.prioridade ?? "rotina"} className="ui-input"><option value="rotina">Rotina</option><option value="urgente">Urgente</option><option value="emergencia">Emergência</option></select><input name="coleta_prevista_em" type="datetime-local" className="ui-input"/></div><button className="ui-button-primary mt-3">Gerar amostra / etiqueta</button></form>; }) : <p className="py-8 text-center text-sm text-slate-500">Nenhuma solicitação aguardando coleta.</p>}</div></div>

      <div className="his-card p-6"><div className="mb-4 flex items-center gap-3"><PackageCheck className="size-5 text-emerald-700"/><div><h2 className="font-black">Rastreio de amostras</h2><p className="text-sm text-slate-500">Coleta, recebimento e rejeição com motivo.</p></div></div><div className="space-y-3">{amostras.slice(0,30).map((a) => { const at=one(a.atendimento); const p=one(at?.paciente); const sol=one(a.solicitacao); return <div key={a.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-black">{a.codigo_amostra} · {sol?.exame ?? "Exame"}</p><p className="text-xs text-slate-500">{p?.nome_completo ?? "Paciente"} · accession {a.accession_number ?? "—"}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-700">{a.status}</span></div><p className="mt-2 text-xs text-slate-500">Prevista {fmt(a.coleta_prevista_em)} · coletada {fmt(a.coletada_em)} · recebida {fmt(a.recebida_em)}</p><form action={atualizarStatusAmostraLaboratorio} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="amostra_id" value={a.id}/>{a.status==="aguardando_coleta"?<button name="acao" value="coletar" className="ui-button-secondary">Confirmar coleta</button>:null}{a.status==="coletada"?<><input name="temperatura_recebimento" className="ui-input max-w-40" placeholder="Temperatura °C"/><button name="acao" value="receber" className="ui-button-primary">Receber amostra</button></>:null}{!["rejeitada","recebida"].includes(a.status)?<><input name="motivo" className="ui-input min-w-48 flex-1" placeholder="Motivo da rejeição"/><button name="acao" value="rejeitar" className="ui-button-secondary">Rejeitar</button></>:null}</form></div>; })}</div></div>
    </section>

    <section className="mt-5 grid gap-5 xl:grid-cols-[0.85fr_1.15fr]">
      <form action={registrarResultadoLaboratorio} className="his-card p-6"><div className="mb-4"><h2 className="font-black">Registrar resultado</h2><p className="text-sm text-slate-500">Selecione o analisador utilizado; equipamento vinculado e indisponível não pode processar resultado.</p></div><div className="grid gap-3"><select name="amostra_id" required defaultValue="" className="ui-input"><option value="">Selecione a amostra recebida</option>{amostras.filter((a)=>a.status==="recebida").map((a)=><option key={a.id} value={a.id}>{a.codigo_amostra} · {one(a.solicitacao)?.exame ?? "Exame"}</option>)}</select><select name="laboratorio_equipamento_id" defaultValue="" className="ui-input"><option value="">Processamento manual / sem analisador</option>{equipamentos.map((e)=>{const eng=one(e.engenharia);const ok=!eng||["operacional","reserva"].includes(eng.status);return <option key={e.id} value={e.id} disabled={!ok}>{e.codigo} · {e.nome}{eng?` · ${eng.patrimonio} · ${eng.status}`:" · sem patrimônio vinculado"}</option>;})}</select><select name="catalogo_analito_id" required defaultValue="" className="ui-input"><option value="">Selecione o analito</option>{analitos.map((a)=>{const e=one(a.exame);return <option key={a.id} value={a.id}>{e?.codigo ?? ""} {e?.descricao ?? ""} · {a.analito}</option>;})}</select><div className="grid gap-3 sm:grid-cols-2"><input name="resultado" className="ui-input" placeholder="Resultado textual"/><input name="valor_numerico" inputMode="decimal" className="ui-input" placeholder="Valor numérico"/></div><button className="ui-button-primary justify-self-end">Salvar resultado</button></div></form>

      <div className="his-card overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-black">Resultados recentes</h2><p className="text-sm text-slate-500">Liberação assinada e equipamento utilizado ficam rastreados.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Analito</th><th className="px-4 py-3">Resultado</th><th className="px-4 py-3">Equipamento</th><th className="px-4 py-3">Flag</th><th className="px-4 py-3">Ações</th></tr></thead><tbody className="divide-y divide-slate-100">{resultados.slice(0,50).map((r)=>{const at=one(r.atendimento);const p=one(at?.paciente);const eq=one(r.engenharia);return <tr key={r.id}><td className="px-4 py-4"><p className="font-bold">{r.analito}</p><p className="text-xs text-slate-500">{p?.nome_completo ?? "Paciente"}</p></td><td className="px-4 py-4">{r.resultado ?? r.valor_numerico ?? "—"} {r.unidade_medida ?? ""}</td><td className="px-4 py-4 text-xs">{eq?`${eq.patrimonio} · ${eq.nome}`:"Manual"}</td><td className="px-4 py-4"><span className={r.valor_critico?"font-black text-rose-600":"font-bold text-slate-600"}>{r.flag ?? "NORMAL"}</span></td><td className="px-4 py-4"><div className="flex flex-wrap gap-2">{!r.liberado?<form action={liberarResultadoLaboratorio}><input type="hidden" name="resultado_id" value={r.id}/><button className="ui-button-secondary">Liberar</button></form>:<span className="text-xs font-bold text-emerald-700">Liberado {fmt(r.liberado_em)}</span>}{r.valor_critico&&!r.notificado_em?<form action={notificarResultadoCriticoLaboratorio} className="flex flex-wrap gap-2"><input type="hidden" name="resultado_id" value={r.id}/><input name="notificado_a" required className="ui-input max-w-40" placeholder="Comunicado a"/><select name="meio" className="ui-input max-w-32" defaultValue="telefone"><option value="telefone">Telefone</option><option value="presencial">Presencial</option><option value="sistema">Sistema</option></select><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" name="readback"/>Read-back</label><button className="ui-button-primary">Registrar</button></form>:r.notificado_em?<span className="text-xs font-bold text-brand-700">Notificado: {r.notificado_a}</span>:null}</div></td></tr>;})}</tbody></table></div></div>
    </section>
    <a href="/assistencial/laboratorio" className="ui-button-secondary mt-5 inline-flex"><RefreshCw className="size-4"/>Atualizar painel</a>
  </SectionPage>;
}
