export const permissions = [
  "empresas.visualizar",
  "empresas.administrar",
  "estrutura.visualizar",
  "estrutura.criar",
  "estrutura.editar",
  "usuarios.visualizar",
  "usuarios.vincular",
  "usuarios.administrar",
  "pacientes.visualizar",
  "pacientes.criar",
  "pacientes.editar",
  "profissionais.visualizar",
  "profissionais.criar",
  "profissionais.editar",
  "convenios.visualizar",
  "convenios.criar",
  "convenios.editar",
  "catalogos.visualizar",
  "catalogos.criar",
  "catalogos.editar",
  "agenda.visualizar",
  "agenda.criar",
  "agenda.editar",
  "recepcao.visualizar",
  "recepcao.operar",
  "atendimentos.visualizar",
  "atendimentos.abrir",
  "atendimentos.transferir",
  "atendimentos.alta",
  "autorizacoes.visualizar",
  "autorizacoes.solicitar",
  "autorizacoes.decidir",
  "triagem.visualizar",
  "triagem.registrar",
  "fila_medica.visualizar",
  "fila_medica.operar",
  "prontuario.visualizar",
  "prontuario.evoluir",
  "prontuario.assinar",
  "prontuario.adendo",
  "prescricao.visualizar",
  "prescricao.criar",
  "prescricao.assinar",
  "prescricao.suspender",
  "assistencial.visualizar",
  "assistencial.registrar",
  "enfermagem.visualizar",
  "enfermagem.registrar",
  "enfermagem.checar",
  "farmacia.visualizar",
  "farmacia.validar",
  "farmacia.dispensar",
  "farmacia.devolver",
  "medicamentos.administrar",
  "laboratorio.visualizar",
  "laboratorio.coletar",
  "laboratorio.resultar",
  "laboratorio.liberar",
  "laboratorio.criticos",
  "imagem.visualizar",
  "imagem.agendar",
  "imagem.executar",
  "imagem.laudar",
  "imagem.liberar",
  "internacao.visualizar",
  "internacao.admitir",
  "internacao.movimentar",
  "internacao.alta",
  "centro_cirurgico.visualizar",
  "centro_cirurgico.operar",
  "nutricao.visualizar",
  "nutricao.operar",
  "hemoterapia.visualizar",
  "hemoterapia.operar",
  "ccih.visualizar",
  "ccih.operar",
  "uti.visualizar",
  "uti.operar",
  "compras.visualizar",
  "compras.solicitar",
  "compras.cotar",
  "compras.aprovar",
  "compras.receber",
  "estoque.visualizar",
  "estoque.movimentar",
  "estoque.inventariar",
  "comercial.visualizar",
  "comercial.editar",
  "auditoria.visualizar",
  "auditoria.analisar",
  "auditoria.liberar",
  "contas_medicas.visualizar",
  "contas_medicas.analisar",
  "contas_medicas.liberar",
  "faturamento.visualizar",
  "faturamento.criar",
  "faturamento.fechar",
  "tiss.visualizar",
  "tiss.gerar",
  "tiss.enviar",
  "tiss.retorno",
  "glosas.visualizar",
  "glosas.registrar",
  "glosas.recorrer",
  "financeiro.visualizar",
  "financeiro.receber",
  "financeiro.conciliar",
  "nfse.visualizar",
  "nfse.configurar",
  "nfse.emitir",
  "ged.visualizar",
  "ged.enviar",
  "ged.administrar",
  "diretoria.visualizar",
  "configuracoes.visualizar",
  "configuracoes.administrar",
] as const;

export type Permission = (typeof permissions)[number];

export function hasPermission(granted: readonly string[], required: Permission) {
  return granted.includes(required);
}

export function hasAnyPermission(
  granted: readonly string[],
  required: readonly Permission[],
) {
  return required.some((permission) => granted.includes(permission));
}

export function hasAllPermissions(
  granted: readonly string[],
  required: readonly Permission[],
) {
  return required.every((permission) => granted.includes(permission));
}
