import { Calculator, PackageCheck } from "lucide-react";
import { CadastrosWorkspaceNav, CadastroKpi } from "@/components/cadastros/cadastros-workspace-nav";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { adicionarItemPacote, salvarPacoteContrato, salvarRegraFaturamento } from "@/modules/comercial/regras-actions";
function one<T>(r:T|T[]|null){return Array.isArray(r)?r[0]??null:r;}
export default async function RegrasPage(){
 const supabase=await createClient();
 const [{data:contratos},{data:regras},{data:pacotes}]=await Promise.all([
  supabase.from("credenciamento_contratos").select("id,numero_contrato,convenio:convenios(nome_fantasia)").eq("status","ativo").order("created_at",{ascending:false}),
  supabase.from("contrato_regras_faturamento").select("id,categoria,codigo_regra,descricao,percentual,valor_fixo,prioridade,condicoes,vigencia_inicio,vigencia_fim,contrato:credenciamento_contratos(numero_contrato,convenio:convenios(nome_fantasia))").eq("ativo",true).order("prioridade"),
  supabase.from("contrato_pacotes").select("id,codigo,nome,valor,vigencia_inicio,vigencia_fim,inclusoes,exclusoes,contrato:credenciamento_contratos(numero_contrato,convenio:convenios(nome_fantasia)),itens:contrato_pacote_itens(id,codigo,tabela,quantidade_inclusa,cobranca_excedente)").eq("ativo",true).order("codigo")
 ]);
 const semVigencia=(regras??[]).filter(r=>!r.vigencia_inicio&&!r.vigencia_fim).length;
 return <SectionPage eyebrow="Comercial / Contratos" title="Regras avançadas e pacotes" description="Configure regras de cálculo e pacotes negociados, com prioridade, vigência, inclusões e exclusões por contrato.">
  <CadastrosWorkspaceNav active="/comercial/regras"/>
  <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><CadastroKpi label="Contratos ativos" value={contratos?.length??0}/><CadastroKpi label="Regras ativas" value={regras?.length??0}/><CadastroKpi label="Pacotes ativos" value={pacotes?.length??0}/><CadastroKpi label="Regras sem vigência" value={semVigencia} detail={semVigencia?"Revisar para evitar aplicação indefinida":"Todas as regras têm vigência"}/></section>
  <div className="mb-5 grid gap-3 md:grid-cols-3"><Guide title="Prioridade" text="Regras de menor prioridade numérica são avaliadas antes das demais."/><Guide title="Vigência" text="Evite regra aberta sem necessidade; preserve o histórico contratual."/><Guide title="Pacotes" text="Defina inclusões, exclusões e cobrança de excedentes de forma explícita."/></div>
  <div className="grid gap-6 xl:grid-cols-2">
   <form action={salvarRegraFaturamento} className="ui-card p-5"><div className="flex items-center gap-2"><Calculator className="size-5 text-brand-700"/><div><h2 className="font-semibold">Nova regra contratual</h2><p className="text-xs text-slate-500">Use para múltiplos, urgência, acomodação, auxiliares, anestesia e demais exceções.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2"><select name="contrato_id" required defaultValue="" className="ui-input"><option value="">Contrato</option>{contratos?.map(c=>{const v=one(c.convenio);return <option key={c.id} value={c.id}>{v?.nome_fantasia??"Convênio"} · {c.numero_contrato||"s/n"}</option>})}</select><select name="categoria" className="ui-input"><option value="procedimento">Procedimento</option><option value="cirurgia">Cirurgia</option><option value="sadt">SADT</option><option value="honorario">Honorário</option><option value="anestesia">Anestesia</option><option value="filme">Filme</option><option value="acomodacao">Acomodação</option><option value="urgencia">Urgência</option></select><input name="codigo_regra" className="ui-input" placeholder="Ex.: MULTIPLO_2, VIA_MESMA, URGENCIA"/><input name="descricao" className="ui-input" placeholder="Descrição da regra"/><input name="percentual" className="ui-input" placeholder="Percentual (ex.: 70)"/><input name="valor_fixo" className="ui-input" placeholder="Valor fixo opcional"/><input name="prioridade" defaultValue="100" className="ui-input" placeholder="Prioridade"/><label className="grid gap-1 text-xs font-semibold text-slate-500">Início<input type="date" name="vigencia_inicio" className="ui-input"/></label><label className="grid gap-1 text-xs font-semibold text-slate-500">Fim<input type="date" name="vigencia_fim" className="ui-input"/></label><textarea name="condicoes_json" className="ui-input md:col-span-2 min-h-24 font-mono text-xs" placeholder='Condições JSON opcional, ex.: {"sequencia":2,"mesma_via":true}'/><button className="ui-button-primary md:col-span-2">Salvar regra</button></div></form>
   <form action={salvarPacoteContrato} className="ui-card p-5"><div className="flex items-center gap-2"><PackageCheck className="size-5 text-emerald-600"/><div><h2 className="font-semibold">Novo pacote</h2><p className="text-xs text-slate-500">Agrupe serviços e defina o que está incluído ou será cobrado à parte.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2"><select name="contrato_id" required defaultValue="" className="ui-input"><option value="">Contrato</option>{contratos?.map(c=>{const v=one(c.convenio);return <option key={c.id} value={c.id}>{v?.nome_fantasia??"Convênio"} · {c.numero_contrato||"s/n"}</option>})}</select><input name="codigo" className="ui-input" placeholder="Código do pacote"/><input name="nome" className="ui-input" placeholder="Nome do pacote"/><input name="valor" className="ui-input" placeholder="Valor do pacote"/><label className="grid gap-1 text-xs font-semibold text-slate-500">Início<input type="date" name="vigencia_inicio" className="ui-input"/></label><label className="grid gap-1 text-xs font-semibold text-slate-500">Fim<input type="date" name="vigencia_fim" className="ui-input"/></label><textarea name="inclusoes" className="ui-input min-h-24" placeholder="Itens incluídos, um por linha"/><textarea name="exclusoes" className="ui-input min-h-24" placeholder="Itens excluídos, um por linha"/><button className="ui-button-primary md:col-span-2">Salvar pacote</button></div></form>
  </div>
  <section className="ui-card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold">Regras ativas</h2><p className="text-xs text-slate-500">A prioridade e a vigência determinam quando cada regra poderá afetar o cálculo.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Convênio</th><th className="px-4 py-3">Categoria</th><th className="px-4 py-3">Regra</th><th className="px-4 py-3">Prior.</th><th className="px-4 py-3">Percentual</th><th className="px-4 py-3">Valor fixo</th><th className="px-4 py-3">Vigência</th></tr></thead><tbody className="divide-y divide-slate-100">{regras?.length?regras.map(r=>{const c=one(r.contrato),v=c?one(c.convenio):null;return <tr key={r.id}><td className="px-4 py-3">{v?.nome_fantasia??"—"}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600">{r.categoria}</span></td><td className="px-4 py-3"><b>{r.codigo_regra}</b><div className="text-xs text-slate-500">{r.descricao}</div></td><td className="px-4 py-3 font-mono text-xs">{r.prioridade}</td><td className="px-4 py-3">{r.percentual??"—"}%</td><td className="px-4 py-3">{r.valor_fixo!=null?`R$ ${Number(r.valor_fixo).toLocaleString("pt-BR",{minimumFractionDigits:2})}`:"—"}</td><td className="px-4 py-3">{r.vigencia_inicio||"—"} → {r.vigencia_fim||"aberta"}</td></tr>}):<tr><td colSpan={7} className="p-8 text-center text-slate-500">Nenhuma regra ativa cadastrada.</td></tr>}</tbody></table></div></section>
  <section className="mt-6 grid gap-4">{pacotes?.length?pacotes.map(p=>{const c=one(p.contrato),v=c?one(c.convenio):null;const itens=Array.isArray(p.itens)?p.itens:[];return <div key={p.id} className="ui-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{p.codigo} · {p.nome}</h2><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">{itens.length} item(ns)</span></div><p className="mt-1 text-sm text-slate-500">{v?.nome_fantasia??"Convênio"} · R$ {Number(p.valor).toLocaleString("pt-BR",{minimumFractionDigits:2})}</p></div><span className="text-xs text-slate-400">{p.vigencia_inicio||"—"} → {p.vigencia_fim||"aberta"}</span></div><form action={adicionarItemPacote} className="mt-4 grid gap-3 md:grid-cols-5"><input type="hidden" name="pacote_id" value={p.id}/><input name="codigo" className="ui-input" placeholder="Código item"/><input name="tabela" className="ui-input" placeholder="Tabela"/><input name="quantidade_inclusa" className="ui-input" placeholder="Qtd inclusa"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="cobranca_excedente"/>Cobrar excedente</label><button className="ui-button-primary">Adicionar item</button></form>{itens.length?<div className="mt-4 flex flex-wrap gap-2">{itens.map(i=><span key={i.id} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm">{i.codigo}{i.tabela?` · ${i.tabela}`:""}{i.quantidade_inclusa?` · ${i.quantidade_inclusa}`:""}{i.cobranca_excedente?" · excedente":""}</span>)}</div>:<p className="mt-4 text-xs font-medium text-amber-700">Pacote ainda sem itens detalhados.</p>}</div>}):<div className="ui-card p-8 text-center text-slate-500">Nenhum pacote ativo cadastrado.</div>}</section>
 </SectionPage>;
}
function Guide({title,text}:{title:string;text:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><b className="text-sm text-slate-950">{title}</b><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>}
