import Link from "next/link";
import type { Route } from "next";
import { AlertTriangle, FlaskConical, Microscope, PackageCheck, RadioTower, TestTube2 } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { getAssistencialContext } from "@/modules/assistencial/context";
export const dynamic="force-dynamic"; export const revalidate=0;
export default async function LaboratorioCentralPage(){const {supabase,empresaId,unidadeId}=await getAssistencialContext();const[sRes,aRes,rRes,eRes]=await Promise.all([
 supabase.from("solicitacoes_exames").select("id,status",{count:"exact"}).eq("empresa_id",empresaId).eq("unidade_id",unidadeId).ilike("modalidade","%laborat%").in("status",["solicitado","coleta","processamento"]).limit(500),
 supabase.from("laboratorio_amostras").select("id,status").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).limit(500),
 supabase.from("laboratorio_resultados").select("id,valor_critico,notificado_em,liberado").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).order("created_at",{ascending:false}).limit(500),
 supabase.from("laboratorio_equipamentos").select("id,ativo,engenharia:engenharia_equipamentos(status)").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).eq("ativo",true)]);
 const amostras=aRes.data??[],resultados=rRes.data??[]; const criticos=resultados.filter(r=>r.valor_critico&&!r.notificado_em).length; const pendentes=resultados.filter(r=>!r.liberado).length;
 return <SectionPage eyebrow="Assistencial / Laboratório" title="Laboratório Clínico" description="Central operacional do pedido à liberação: coleta, amostra, processamento, validação, crítico, interface e rastreabilidade.">
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Solicitações abertas" value={sRes.data?.length??0}/><Kpi label="Aguardando coleta" value={amostras.filter(a=>a.status==="aguardando_coleta").length}/><Kpi label="Em processamento" value={amostras.filter(a=>["coletada","recebida","processamento"].includes(a.status)).length}/><Kpi label="Liberação pendente" value={pendentes}/><Kpi label="Críticos sem comunicação" value={criticos} warn={criticos>0}/></section>
 <section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Card href="/assistencial/laboratorio" icon={<TestTube2/>} title="Coleta e recebimento" text="Etiquetas, accession, coleta, cadeia de custódia, temperatura e rejeição com motivo."/><Card href="/assistencial/laboratorio" icon={<Microscope/>} title="Processamento e resultados" text="Analisador integrado ou processamento manual, analitos, flags e valores críticos."/><Card href="/assistencial/laboratorio" icon={<PackageCheck/>} title="Validação e liberação" text="Liberação rastreada e comunicação de valores críticos com read-back."/><Card href="/engenharia-clinica/integracoes" icon={<RadioTower/>} title="Interfaces e equipamentos" text="ASTM/HL7, analisadores e vínculo com Engenharia Clínica."/><Card href="/assistencial/laboratorio" icon={<AlertTriangle/>} title="Resultados críticos" text="Fila prioritária de resultados críticos ainda não comunicados."/><Card href="/laboratorio" icon={<FlaskConical/>} title="Catálogo e qualidade" text="Catálogo técnico, método, referência, recipiente, preparo e evolução para controle de qualidade."/></section>
 <section className="his-card mt-5 p-5"><h2 className="font-black">Equipamentos</h2><p className="mt-1 text-sm text-slate-500">{eRes.data?.length??0} analisador(es) ativo(s) configurado(s) nesta unidade. Equipamentos indisponíveis na Engenharia Clínica permanecem bloqueados para processamento.</p></section>
 </SectionPage>}
function Kpi({label,value,warn=false}:{label:string;value:number;warn?:boolean}){return <div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">{label}</p><p className={`mt-2 text-3xl font-black ${warn?"text-rose-700":"text-slate-950"}`}>{value}</p></div>}
function Card({href,icon,title,text}:{href:Route;icon:React.ReactNode;title:string;text:string}){return <Link href={href} className="his-card p-5 transition hover:-translate-y-0.5"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700">{icon}</span><h2 className="mt-4 font-black text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></Link>}
