import Link from "next/link";
import { Boxes, ClipboardCheck, PackageCheck, RotateCcw, ShieldCheck, Warehouse } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { getAssistencialContext } from "@/modules/assistencial/context";

export const dynamic="force-dynamic"; export const revalidate=0;
export default async function FarmaciaPage(){const {supabase,empresaId,unidadeId}=await getAssistencialContext();const[pRes,dRes,lRes,locRes]=await Promise.all([
 supabase.from("prescricoes").select("id,requer_validacao_farmaceutica,status",{count:"exact"}).eq("empresa_id",empresaId).eq("unidade_id",unidadeId).eq("tipo","medicamento").eq("status","ativa").not("assinado_em","is",null).limit(500),
 supabase.from("dispensacoes_medicamentos").select("id,status",{count:"exact"}).eq("empresa_id",empresaId).eq("unidade_id",unidadeId).in("status",["dispensado","parcial"]).limit(500),
 supabase.from("estoque_lotes").select("id,validade,quantidade").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).gt("quantidade",0).limit(3000),
 supabase.from("estoque_locais").select("id,nome,tipo_farmacia,ativo").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).eq("e_farmacia",true).eq("ativo",true).order("nome")]);
 const prescricoes=pRes.data??[],lotes=lRes.data??[],hoje=Date.now(),vence30=lotes.filter(l=>l.validade&&new Date(l.validade).getTime()>=hoje&&new Date(l.validade).getTime()<=hoje+30*86400000).length;
 return <SectionPage eyebrow="Assistencial / Farmácia" title="Farmácia Hospitalar" description="Central de validação farmacêutica, dispensação por farmácia, estoques, reposição, devoluções e rastreabilidade por lote.">
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Prescrições liberadas" value={prescricoes.length}/><Kpi label="Dispensações abertas" value={dRes.data?.length??0}/><Kpi label="Farmácias ativas" value={locRes.data?.length??0}/><Kpi label="Lotes vencendo 30d" value={vence30} warn={vence30>0}/></section>
 <section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Card href="/assistencial/medicamentos" icon={<ShieldCheck/>} title="Validação e dispensação" text="Validar prescrição, separar item principal e componentes, FEFO e baixa por lote."/><Card href="/estoque" icon={<Warehouse/>} title="Estoque por farmácia" text="Saldo separado entre Central, Satélite PS, Centro Cirúrgico e outras farmácias locais."/><Card href="/almoxarifado/requisicoes" icon={<Boxes/>} title="Reposição / requisições" text="Solicitar reposição ao Almoxarifado e acompanhar transferências para a farmácia de destino."/><Card href="/assistencial/medicamentos" icon={<RotateCcw/>} title="Devoluções" text="Registrar devolução vinculada à dispensação e recompor saldo com rastreabilidade."/><Card href="/prescricao" icon={<ClipboardCheck/>} title="Prescrições" text="Consultar prescrições finalizadas que alimentam o fluxo farmacêutico."/><Card href="/farmacia" icon={<PackageCheck/>} title="Inventário e indicadores" text="Base para inventário cíclico, divergências, validade, consumo e cobertura de estoque."/></section>
 <section className="his-card mt-5 p-5"><h2 className="font-black">Farmácias desta unidade</h2><div className="mt-3 flex flex-wrap gap-2">{(locRes.data??[]).map(l=><span key={l.id} className="rounded-full bg-brand-50 px-3 py-1.5 text-xs font-bold text-brand-700">{l.nome} · {l.tipo_farmacia??"farmácia"}</span>)}{!locRes.data?.length?<span className="text-sm text-slate-500">Nenhuma farmácia local configurada.</span>:null}</div></section>
 </SectionPage>}
function Kpi({label,value,warn=false}:{label:string;value:number;warn?:boolean}){return <div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">{label}</p><p className={`mt-2 text-3xl font-black ${warn?"text-amber-700":"text-slate-950"}`}>{value}</p></div>}
function Card({href,icon,title,text}:{href:string;icon:React.ReactNode;title:string;text:string}){return <Link href={href} className="his-card p-5 transition hover:-translate-y-0.5"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700">{icon}</span><h2 className="mt-4 font-black text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></Link>}
