import Link from "next/link";
import { notFound } from "next/navigation";
import { Activity, Fingerprint, HeartPulse, IdCard, Mail, MapPin, Phone, Stethoscope, UserRound } from "lucide-react";
import { CadastrosWorkspaceNav, CadastroKpi } from "@/components/cadastros/cadastros-workspace-nav";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { criarUrlFotoAssinada } from "@/modules/cadastros/fotos";

function dt(value:string|null|undefined){return value?new Date(value).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"}):"—";}
export default async function Paciente360Page({params}:{params:Promise<{pacienteId:string}>}){
 const {pacienteId}=await params;const supabase=await createClient();
 const [{data:paciente},{data:emails},{data:telefones},{data:enderecos},{data:atendimentos,count:totalAtendimentos},{count:biometrias},{count:tokens}]=await Promise.all([
  supabase.from("pacientes").select("id,nome_completo,nome_social,cpf,cns,rg,data_nascimento,sexo,telefone,email,cidade,uf,cep,logradouro,numero,bairro,numero_registro,ra,foto_path,ativo").eq("id",pacienteId).maybeSingle(),
  supabase.from("paciente_emails").select("id,email,tipo,principal").eq("paciente_id",pacienteId).order("principal",{ascending:false}),
  supabase.from("paciente_telefones").select("id,telefone,tipo,principal").eq("paciente_id",pacienteId).order("principal",{ascending:false}),
  supabase.from("paciente_enderecos").select("id,tipo,endereco,numero,complemento,bairro,cidade,estado,cep,principal").eq("paciente_id",pacienteId).order("principal",{ascending:false}),
  supabase.from("atendimentos").select("id,numero_atendimento,status,tipo_atendimento,data_abertura",{count:"exact"}).eq("paciente_id",pacienteId).order("data_abertura",{ascending:false}).limit(10),
  supabase.from("paciente_biometrias").select("id",{count:"exact",head:true}).eq("paciente_id",pacienteId).eq("ativo",true),
  supabase.from("paciente_convenio_tokens").select("id",{count:"exact",head:true}).eq("paciente_id",pacienteId),
 ]);
 if(!paciente)notFound();const foto=await criarUrlFotoAssinada(supabase,paciente.foto_path);const endereco=enderecos?.[0];
 return <SectionPage eyebrow="Cadastros / Pacientes / Ficha 360°" title={paciente.nome_social||paciente.nome_completo} description="Identificação, contatos, biometria e histórico assistencial do paciente em um único ponto.">
  <CadastrosWorkspaceNav active="/pacientes"/>
  <section className="ui-card mb-5 p-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-4"><span className="grid size-16 shrink-0 place-items-center overflow-hidden rounded-2xl bg-brand-50 text-xl font-black text-brand-700" style={foto?{backgroundImage:`url(${foto})`,backgroundPosition:"center",backgroundSize:"cover"}:undefined}>{foto?null:(paciente.nome_social||paciente.nome_completo).slice(0,1).toUpperCase()}</span><div><h2 className="text-xl font-black text-slate-950">{paciente.nome_social||paciente.nome_completo}</h2>{paciente.nome_social?<p className="mt-1 text-sm text-slate-500">Nome civil: {paciente.nome_completo}</p>:null}<p className="mt-1 text-sm font-medium text-brand-700">{paciente.ra} · Registro #{paciente.numero_registro}</p></div></div><div className="flex flex-wrap gap-2"><Link href={`/pacientes/${paciente.id}/identificacao`} className="ui-button-secondary"><Fingerprint className="size-4"/>Identificação</Link><Link href={`/atendimentos/novo?paciente=${paciente.id}`} className="ui-button-secondary"><HeartPulse className="size-4"/>Novo atendimento</Link><Link href={`/prontuario?paciente=${paciente.id}`} className="ui-button-primary"><Stethoscope className="size-4"/>Prontuário</Link></div></div></section>
  <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><CadastroKpi label="Atendimentos" value={totalAtendimentos??0}/><CadastroKpi label="Biometrias ativas" value={biometrias??0}/><CadastroKpi label="Tokens registrados" value={tokens??0}/><CadastroKpi label="Último atendimento" value={atendimentos?.[0]?.numero_atendimento?`#${atendimentos[0].numero_atendimento}`:"—"}/></section>
  <div className="grid gap-5 xl:grid-cols-3"><section className="ui-card p-5"><h2 className="flex items-center gap-2 font-bold"><IdCard className="size-5 text-brand-700"/>Identificação</h2><div className="mt-4 grid gap-3"><Info label="CPF" value={paciente.cpf||"—"}/><Info label="CNS" value={paciente.cns||"—"}/><Info label="RG" value={paciente.rg||"—"}/><Info label="Nascimento" value={paciente.data_nascimento?new Date(`${paciente.data_nascimento}T12:00:00`).toLocaleDateString("pt-BR"):"—"}/><Info label="Sexo" value={String(paciente.sexo||"—").replaceAll("_"," ")}/></div></section><section className="ui-card p-5"><h2 className="flex items-center gap-2 font-bold"><UserRound className="size-5 text-brand-700"/>Contatos</h2><div className="mt-4 space-y-3"><Contact icon={Mail} value={emails?.[0]?.email||paciente.email||"—"}/><Contact icon={Phone} value={telefones?.[0]?.telefone||paciente.telefone||"—"}/><Contact icon={MapPin} value={endereco?`${endereco.endereco}, ${endereco.numero||"s/n"} · ${endereco.cidade}/${endereco.estado}`:[paciente.logradouro,paciente.numero,paciente.cidade,paciente.uf].filter(Boolean).join(" · ")||"—"}/></div></section><section className="ui-card p-5"><h2 className="flex items-center gap-2 font-bold"><Activity className="size-5 text-brand-700"/>Segurança de identificação</h2><div className="mt-4 space-y-3"><Info label="Biometrias" value={`${biometrias??0} ativas`}/><Info label="Tokens de operadora" value={String(tokens??0)}/><Link href={`/pacientes/${paciente.id}/identificacao`} className="ui-button-secondary w-full justify-center">Gerenciar biometria e tokens</Link></div></section></div>
  <section className="ui-card mt-5 overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Histórico recente de atendimentos</h2><p className="mt-1 text-sm text-slate-500">Últimos episódios vinculados ao mesmo registro do paciente.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Atendimento</th><th className="px-4 py-3">Tipo</th><th className="px-4 py-3">Abertura</th><th className="px-4 py-3">Status</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{atendimentos?.length?atendimentos.map(a=><tr key={a.id}><td className="px-4 py-3 font-semibold">#{a.numero_atendimento}</td><td className="px-4 py-3">{a.tipo_atendimento}</td><td className="px-4 py-3">{dt(a.data_abertura)}</td><td className="px-4 py-3 capitalize">{String(a.status).replaceAll("_"," ")}</td><td className="px-4 py-3 text-right"><Link href={`/prontuario/${a.id}`} className="text-sm font-bold text-brand-700 hover:underline">Abrir prontuário</Link></td></tr>):<tr><td colSpan={5} className="p-8 text-center text-slate-500">Nenhum atendimento registrado.</td></tr>}</tbody></table></div></section>
 </SectionPage>;
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 font-medium text-slate-700">{value}</p></div>}
function Contact({icon:Icon,value}:{icon:typeof Mail;value:string}){return <div className="flex items-start gap-3 rounded-xl bg-slate-50 p-3"><Icon className="mt-0.5 size-4 text-slate-400"/><p className="text-sm font-medium text-slate-700">{value}</p></div>}
