import Link from "next/link";
import { FileCode2, GitCompareArrows, ReceiptText, Upload } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { importarXmlReferencia } from "@/modules/comercial/xml-reference-actions";
import { createClient } from "@/lib/supabase/server";

export const dynamic="force-dynamic";
export default async function ImportarXmlReferenciasPage({searchParams}:{searchParams:Promise<{erro?:string;importado?:string;tipo?:string;rejeitados?:string;consolidados?:string}>}){
  const qs=await searchParams;const supabase=await createClient();
  const [{count:equivalencias},{count:glosas},{data:fontes}]=await Promise.all([
    supabase.from("referencia_equivalencias").select("id",{count:"exact",head:true}),
    supabase.from("referencia_glosas").select("id",{count:"exact",head:true}),
    supabase.from("tabelas_comerciais_fontes").select("id,codigo,nome,tipo").in("tipo",["amb90","amb92","amb96","amb99","cbhpm","procedimentos_convenio"]).order("nome")
  ]);
  return <SectionPage eyebrow="Comercial / Tabelas / XML" title="Importação de tabelas e referências XML" description="Importe AMB, CBHPM, tabelas legadas de operadora, de-para AMB↔TUSS e catálogo de glosas sem misturar versões históricas." actions={<Link href="/comercial/tabelas" className="ui-button-secondary">← Tabelas comerciais</Link>}>
    {qs.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-medium text-rose-700">Falha na importação: {qs.erro}</div>:null}
    {qs.importado?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-medium text-emerald-700">Importação concluída: {qs.importado} registro(s) · {qs.tipo||"XML"}{Number(qs.rejeitados||0)>0?` · ${qs.rejeitados} rejeitado(s) para revisão`:""}{Number(qs.consolidados||0)>0?` · ${qs.consolidados} código(s) duplicado(s) consolidado(s)`:""}.</div>:null}
    <section className="grid gap-3 md:grid-cols-3"><div className="his-kpi"><GitCompareArrows className="size-5 text-brand-700"/><p className="mt-3 text-xs font-black uppercase text-slate-400">Equivalências AMB ↔ TUSS</p><p className="mt-1 text-3xl font-black text-slate-950">{equivalencias??0}</p></div><div className="his-kpi"><ReceiptText className="size-5 text-brand-700"/><p className="mt-3 text-xs font-black uppercase text-slate-400">Motivos de glosa</p><p className="mt-1 text-3xl font-black text-slate-950">{glosas??0}</p></div><div className="his-kpi"><FileCode2 className="size-5 text-brand-700"/><p className="mt-3 text-xs font-black uppercase text-slate-400">Fontes históricas</p><p className="mt-1 text-3xl font-black text-slate-950">{fontes?.length??0}</p></div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <form action={importarXmlReferencia} className="ui-card p-5"><div className="flex items-center gap-2"><Upload className="size-5 text-brand-700"/><h2 className="font-semibold">Importar XML</h2></div><p className="mt-2 text-sm leading-6 text-slate-500">O layout é detectado automaticamente. Para AMB, CBHPM e tabelas comerciais, informe a vigência real da edição. Se a edição anterior já estiver publicada, a reimportação cria uma nova versão em rascunho sem alterar o histórico.</p><div className="mt-5 grid gap-4"><label className="grid gap-1 text-sm font-semibold text-slate-700">Arquivo XML<input type="file" name="arquivo" accept=".xml,text/xml,application/xml" required className="ui-input"/></label><label className="grid gap-1 text-sm font-semibold text-slate-700">Início da vigência da edição comercial <span className="text-xs font-normal text-slate-400">Obrigatório somente para AMB / CBHPM / tabela da operadora</span><input type="date" name="vigencia_inicio" className="ui-input"/></label><button className="ui-button-primary w-fit"><Upload className="size-4"/>Importar e validar</button></div></form>
      <aside className="ui-card p-5"><h2 className="font-semibold">Layouts reconhecidos</h2><div className="mt-4 space-y-3 text-sm leading-6 text-slate-600"><p><b>AMB 90/92/96/99:</b> código, descrição, CH, auxiliares, porte cirúrgico, CH do anestesista e filme.</p><p><b>CBHPM 3/4/5/5-2009/2014:</b> porte, fração, valor de porte de origem, custo operacional/UCO, auxiliares, porte anestésico e filme.</p><p><b>AMIL PAR 06:</b> preservada como fonte comercial proprietária/legada.</p><p><b>deparatuss / dados:</b> equivalências AMB→TUSS; blocos incompletos ficam para revisão.</p><p><b>glosas:</b> catálogo mestre de código e motivo, separado das glosas reais de cada conta.</p></div></aside>
    </div>
    <section className="ui-card mt-5 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold">Fontes comerciais já reconhecidas</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Código</th><th className="px-4 py-3">Fonte</th><th className="px-4 py-3">Tipo</th></tr></thead><tbody className="divide-y divide-slate-100">{fontes?.length?fontes.map(f=><tr key={f.id}><td className="px-4 py-3 font-mono text-xs">{f.codigo}</td><td className="px-4 py-3 font-semibold">{f.nome}</td><td className="px-4 py-3">{f.tipo}</td></tr>):<tr><td colSpan={3} className="p-8 text-center text-slate-500">Nenhuma fonte histórica importada ainda.</td></tr>}</tbody></table></div></section>
  </SectionPage>;
}
