import Link from "next/link";
import { Calculator, FileCode2, FileSpreadsheet, Link2 } from "lucide-react";
import { CadastrosWorkspaceNav, CadastroKpi } from "@/components/cadastros/cadastros-workspace-nav";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { criarEdicaoProcedimentos, criarFonteProcedimentos, importarItensProcedimentos, vincularRegraProcedimentos } from "@/modules/comercial/procedimentos-actions";
function one<T>(r:T|T[]|null){return Array.isArray(r)?r[0]??null:r;}
export default async function ProcedimentosComerciaisPage({searchParams}:{searchParams:Promise<{erro?:string;importado?:string}>}){const qs=await searchParams;const supabase=await createClient();const [{data:fontes},{data:edicoes},{data:contratos},{data:regras}]=await Promise.all([
  supabase.from("tabelas_procedimentos_fontes").select("id,codigo,nome,metodologia,descricao,ativo").order("nome"),
  supabase.from("tabelas_procedimentos_edicoes").select("id,nome_edicao,referencia,vigencia_inicio,vigencia_fim,status,fonte:tabelas_procedimentos_fontes(nome,metodologia)").order("vigencia_inicio",{ascending:false}).limit(100),
  supabase.from("credenciamento_contratos").select("id,numero_contrato,status,convenio:convenios(nome_fantasia,registro_ans)").eq("status","ativo").order("created_at",{ascending:false}),
  supabase.from("contrato_regras_procedimentos").select("id,categoria,modo_edicao,valor_ch_hm,valor_ch_sadt,valor_uco,percentual_ajuste,adicional_urgencia_percentual,adicional_apartamento_percentual,fonte:tabelas_procedimentos_fontes(nome,metodologia),contrato:credenciamento_contratos(numero_contrato,convenio:convenios(nome_fantasia))").eq("ativo",true).order("created_at",{ascending:false}).limit(100)
]);const ativas=(edicoes??[]).filter(e=>e.status==="ativa").length;return <SectionPage eyebrow="Comercial / Procedimentos" title="Procedimentos, Exames e Honorários" description="Metodologias de cálculo, versões e regras contratuais por convênio." actions={<Link href="/comercial/tabelas/xml" className="ui-button-primary"><FileCode2 className="size-4"/>Importar AMB/CBHPM XML</Link>}>
<CadastrosWorkspaceNav active="/comercial/procedimentos"/>{qs.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">Falha: {qs.erro}</div>:null}{qs.importado?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">Itens importados com sucesso.</div>:null}<section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><CadastroKpi label="Fontes/metodologias" value={fontes?.length??0}/><CadastroKpi label="Edições ativas" value={ativas}/><CadastroKpi label="Contratos ativos" value={contratos?.length??0}/><CadastroKpi label="Regras vigentes" value={regras?.length??0}/></section>
<div className="mb-5 grid gap-3 md:grid-cols-4"><Step n="1" title="Fonte" text="AMB, CBHPM ou metodologia própria."/><Step n="2" title="Edição" text="Versão e vigência da tabela."/><Step n="3" title="Itens" text="Códigos e parâmetros de cálculo."/><Step n="4" title="Contrato" text="CH, UCO, percentuais e adicionais."/></div>
<div className="grid gap-6 xl:grid-cols-2"><form action={criarFonteProcedimentos} className="ui-card p-5"><h2 className="flex items-center gap-2 font-semibold"><FileSpreadsheet className="size-5 text-brand-700"/>Nova fonte/metodologia</h2><p className="mt-1 text-xs text-slate-500">Uma fonte representa a metodologia; cada atualização deve ser uma nova edição.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><input name="codigo" required className="ui-input" placeholder="Ex.: CBHPM, AMB90, AMB96"/><input name="nome" required className="ui-input" placeholder="Nome da tabela"/><select name="metodologia" required className="ui-input"><option value="tabela_propria">Tabela própria</option><option value="amb90">AMB 90</option><option value="amb92">AMB 92</option><option value="amb96">AMB 96</option><option value="amb99">AMB 99</option><option value="cbhpm">CBHPM</option><option value="outra">Outra</option></select><input name="descricao" className="ui-input" placeholder="Descrição"/><button className="ui-button-primary md:col-span-2">Salvar fonte</button></div></form>
<form action={criarEdicaoProcedimentos} className="ui-card p-5"><h2 className="font-semibold">Nova edição</h2><p className="mt-1 text-xs text-slate-500">Preserve as versões históricas; não sobrescreva uma edição antiga.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><select name="fonte_id" required defaultValue="" className="ui-input"><option value="">Fonte</option>{fontes?.map(f=><option key={f.id} value={f.id}>{f.nome} · {f.metodologia}</option>)}</select><input name="nome_edicao" required className="ui-input" placeholder="Ex.: CBHPM 2026 / AMB 92"/><input name="referencia" className="ui-input" placeholder="Referência/comunicado"/><label className="grid gap-1 text-xs font-semibold text-slate-500">Início<input name="vigencia_inicio" type="date" required className="ui-input"/></label><label className="grid gap-1 text-xs font-semibold text-slate-500">Fim<input name="vigencia_fim" type="date" className="ui-input"/></label><select name="status" defaultValue="ativa" className="ui-input"><option value="rascunho">Rascunho</option><option value="ativa">Ativa</option><option value="encerrada">Encerrada</option></select><button className="ui-button-primary md:col-span-2">Criar edição</button></div></form></div>
<div className="mt-6 grid gap-6 xl:grid-cols-2"><form action={importarItensProcedimentos} className="ui-card p-5" encType="multipart/form-data"><h2 className="font-semibold">Importar itens da edição</h2><p className="mt-1 text-sm text-slate-500">CSV permanece para bases próprias. Para AMB/CBHPM históricos, use o importador XML.</p><div className="mt-4 grid gap-3"><select name="edicao_id" required defaultValue="" className="ui-input"><option value="">Edição</option>{edicoes?.map(e=>{const f=one(e.fonte);return <option key={e.id} value={e.id}>{f?.nome??"Tabela"} · {e.nome_edicao}</option>})}</select><input type="file" name="arquivo" accept=".csv,text/csv" required className="ui-input"/><button className="ui-button-primary">Importar CSV</button></div></form>
<form action={vincularRegraProcedimentos} className="ui-card p-5"><h2 className="flex items-center gap-2 font-semibold"><Calculator className="size-5 text-brand-700"/>Regra contratual</h2><p className="mt-1 text-xs text-slate-500">Defina como esta categoria será calculada para o contrato.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><select name="contrato_id" required defaultValue="" className="ui-input"><option value="">Contrato/convênio</option>{contratos?.map(c=>{const conv=one(c.convenio);return <option key={c.id} value={c.id}>{conv?.nome_fantasia??"Convênio"} · {c.numero_contrato||"sem nº"}</option>})}</select><select name="categoria" className="ui-input"><option value="procedimentos">Procedimentos</option><option value="consultas">Consultas</option><option value="sadt">SADT</option><option value="exames">Exames</option><option value="honorarios">Honorários</option><option value="diarias">Diárias</option><option value="taxas">Taxas</option></select><select name="fonte_id" required defaultValue="" className="ui-input"><option value="">Tabela/metodologia</option>{fontes?.map(f=><option key={f.id} value={f.id}>{f.nome} · {f.metodologia}</option>)}</select><select name="modo_edicao" className="ui-input"><option value="vigente_data">Edição vigente na data</option><option value="edicao_fixa">Edição fixa</option></select><select name="edicao_fixa_id" defaultValue="" className="ui-input"><option value="">Edição fixa (opcional)</option>{edicoes?.map(e=><option key={e.id} value={e.id}>{e.nome_edicao}</option>)}</select><input name="valor_ch_hm" className="ui-input" placeholder="Valor CH/HM"/><input name="valor_ch_sadt" className="ui-input" placeholder="Valor CH/SADT"/><input name="valor_uco" className="ui-input" placeholder="Valor UCO"/><input name="percentual_ajuste" className="ui-input" placeholder="Ajuste % (ex.: -10)"/><input name="adicional_urgencia_percentual" className="ui-input" placeholder="Urgência %"/><input name="adicional_apartamento_percentual" className="ui-input" placeholder="Acomodação %"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="aplicar_urgencia"/>Aplicar adicional de urgência</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="aplicar_acomodacao"/>Aplicar adicional de acomodação</label><input type="date" name="vigencia_inicio" className="ui-input"/><input type="date" name="vigencia_fim" className="ui-input"/><button className="ui-button-primary md:col-span-2">Vincular regra ao contrato</button></div></form></div>
<section className="ui-card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="flex items-center gap-2 font-semibold"><Link2 className="size-5 text-brand-700"/>Regras vigentes</h2><p className="text-xs text-slate-500">Resumo das metodologias que efetivamente precificam as contas.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Convênio</th><th className="px-4 py-3">Categoria</th><th className="px-4 py-3">Metodologia</th><th className="px-4 py-3">CH/HM</th><th className="px-4 py-3">CH/SADT</th><th className="px-4 py-3">UCO</th><th className="px-4 py-3">Ajuste</th></tr></thead><tbody className="divide-y divide-slate-100">{regras?.length?regras.map(r=>{const f=one(r.fonte);const c=one(r.contrato);const conv=c?one(c.convenio):null;return <tr key={r.id}><td className="px-4 py-3 font-medium">{conv?.nome_fantasia??"—"}</td><td className="px-4 py-3">{r.categoria}</td><td className="px-4 py-3">{f?.metodologia??"—"}</td><td className="px-4 py-3">{r.valor_ch_hm??"—"}</td><td className="px-4 py-3">{r.valor_ch_sadt??"—"}</td><td className="px-4 py-3">{r.valor_uco??"—"}</td><td className="px-4 py-3">{r.percentual_ajuste}%</td></tr>}):<tr><td colSpan={7} className="px-4 py-8 text-center text-slate-500">Nenhuma regra contratual cadastrada.</td></tr>}</tbody></table></div></section></SectionPage>}
function Step({n,title,text}:{n:string;title:string;text:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-full bg-slate-950 text-xs font-black text-white">{n}</span><b className="text-sm text-slate-950">{title}</b></div><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></div>}
