import Link from "next/link";
import { CalendarClock, FileUp, ReceiptText, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { anexarDocumentoLote, atualizarDadosFinanceirosLote, registrarProtocoloEnvioOperadora } from "@/modules/tiss/actions";

function one<T>(rel:T|T[]|null){return Array.isArray(rel)?rel[0]??null:rel;}
export default async function FinanceiroLotePage({params}:{params:Promise<{loteId:string}>}){
  const {loteId}=await params; const supabase=await createClient();
  const [{data:lote},{data:anexos},{data:recebivel},{data:notas}] = await Promise.all([
    supabase.from("tiss_lotes").select("id,numero_lote,competencia,previsao_pagamento,protocolo_envio_operadora,origem_protocolo,observacoes_envio,status,valor_total,convenio:convenios(nome_fantasia)").eq("id",loteId).maybeSingle(),
    supabase.from("tiss_lote_anexos").select("id,tipo,nome_arquivo,mime_type,tamanho_bytes,observacao,created_at").eq("lote_id",loteId).order("created_at",{ascending:false}),
    supabase.from("financeiro_recebiveis").select("id,status,previsao_pagamento,valor_bruto,valor_glosa,valor_liquido_previsto,valor_recebido").eq("lote_id",loteId).maybeSingle(),
    supabase.from("notas_fiscais_servico").select("id,numero_nfse,numero_rps,status,valor_liquido").eq("lote_id",loteId).order("created_at",{ascending:false})
  ]);
  if(!lote) notFound(); const conv=one(lote.convenio); const atualizar=atualizarDadosFinanceirosLote.bind(null,loteId); const protocolo=registrarProtocoloEnvioOperadora.bind(null,loteId); const anexar=anexarDocumentoLote.bind(null,loteId);
  return <SectionPage eyebrow="Financeiro / TISS / Lote" title={`Financeiro do lote ${lote.numero_lote}`} description={`${conv?.nome_fantasia??"Convênio"} · controle financeiro, protocolo e documentos do faturamento`}>
    <div className="mb-5 flex flex-wrap gap-2"><Link href={`/faturamento/lotes/${loteId}`} className="ui-button-secondary">Voltar ao lote TISS</Link><Link href="/financeiro/notas-fiscais" className="ui-button-primary"><ReceiptText className="mr-2 inline size-4"/>Notas fiscais</Link></div>
    <div className="grid gap-4 md:grid-cols-4"><Card label="Status financeiro" value={recebivel?.status??"previsto"}/><Card label="Valor bruto" value={`R$ ${Number(recebivel?.valor_bruto??lote.valor_total??0).toLocaleString("pt-BR",{minimumFractionDigits:2})}`}/><Card label="Glosa" value={`R$ ${Number(recebivel?.valor_glosa??0).toLocaleString("pt-BR",{minimumFractionDigits:2})}`}/><Card label="Recebido" value={`R$ ${Number(recebivel?.valor_recebido??0).toLocaleString("pt-BR",{minimumFractionDigits:2})}`}/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2">
      <form action={atualizar} className="ui-card p-5"><div className="flex items-center gap-3"><CalendarClock className="size-5 text-brand-700"/><div><h2 className="font-semibold text-slate-900">Competência e previsão</h2><p className="text-sm text-slate-500">Podem ser ajustadas manualmente conforme o ciclo da operadora.</p></div></div><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="space-y-2 text-sm font-medium text-slate-700"><span>Competência *</span><input type="month" name="competencia" required defaultValue={lote.competencia??""} className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Previsão de pagamento</span><input type="date" name="previsao_pagamento" defaultValue={lote.previsao_pagamento??""} className="ui-input"/></label></div><button className="ui-button-primary mt-4">Salvar dados financeiros</button></form>
      <form action={protocolo} className="ui-card p-5"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-emerald-600"/><div><h2 className="font-semibold text-slate-900">Protocolo de envio da operadora</h2><p className="text-sm text-slate-500">Registre o protocolo gerado após o envio pelo portal ou webservice.</p></div></div><div className="mt-4 grid gap-3"><input name="protocolo_envio_operadora" required defaultValue={lote.protocolo_envio_operadora??""} placeholder="Número do protocolo" className="ui-input"/><select name="origem_protocolo" defaultValue={lote.origem_protocolo??"portal"} className="ui-input"><option value="portal">Portal da operadora</option><option value="webservice">Webservice</option><option value="email">E-mail</option><option value="sftp">SFTP</option><option value="outro">Outro</option></select><textarea name="observacoes_envio" rows={3} defaultValue={lote.observacoes_envio??""} placeholder="Observações do envio" className="ui-input"/></div><button className="ui-button-primary mt-4">Registrar protocolo</button></form>
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[0.8fr_1.2fr]">
      <form action={anexar} className="ui-card p-5"><div className="flex items-center gap-3"><FileUp className="size-5 text-brand-700"/><div><h2 className="font-semibold text-slate-900">Anexar documento</h2><p className="text-sm text-slate-500">Comprovante, protocolo, retorno, demonstrativo ou NFS-e.</p></div></div><div className="mt-4 grid gap-3"><select name="tipo" defaultValue="comprovante_envio" className="ui-input"><option value="comprovante_envio">Comprovante de envio</option><option value="protocolo">Protocolo</option><option value="retorno">Retorno</option><option value="demonstrativo">Demonstrativo</option><option value="nota_fiscal">Nota fiscal</option><option value="outro">Outro</option></select><input type="file" name="arquivo" required className="ui-input"/><textarea name="observacao" rows={2} placeholder="Observação" className="ui-input"/></div><button className="ui-button-primary mt-4">Anexar</button></form>
      <section className="ui-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Documentos e notas</h2></div><div className="p-5"><div className="space-y-2">{anexos?.length?anexos.map(a=><div key={a.id} className="rounded-xl border border-slate-200 p-3"><div className="flex justify-between gap-3"><strong className="text-sm text-slate-900">{a.nome_arquivo}</strong><span className="text-xs uppercase text-slate-400">{a.tipo}</span></div><p className="mt-1 text-xs text-slate-500">{a.observacao??"Sem observação"}</p></div>):<p className="text-sm text-slate-500">Nenhum anexo.</p>}</div>{notas?.length?<div className="mt-5 border-t border-slate-100 pt-4"><h3 className="text-sm font-semibold text-slate-900">NFS-e vinculadas</h3><div className="mt-2 space-y-2">{notas.map(n=><Link key={n.id} href={`/financeiro/notas-fiscais/${n.id}`} className="block rounded-xl bg-slate-50 p-3 text-sm hover:bg-slate-100"><b>{n.numero_nfse?`NFS-e ${n.numero_nfse}`:`RPS ${n.numero_rps??"—"}`}</b> · {n.status} · R$ {Number(n.valor_liquido||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}</Link>)}</div></div>:null}</div></section>
    </div>
  </SectionPage>;
}
function Card({label,value}:{label:string;value:string}){return <div className="ui-card p-4"><p className="text-xs uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 font-semibold capitalize text-slate-900">{value}</p></div>}
