import { ActionPanel } from "@/components/painel/action-panel";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { adicionarFornecedorCotacao, aprovarFornecedorCotacao, criarCotacaoCompra, criarSolicitacaoCompra } from "@/modules/corporativo/actions";

function one<T>(r:T|T[]|null){return Array.isArray(r)?r[0]??null:r;}

export default async function ComprasPage(){
  const supabase=await createClient();
  const [{data:sols},{data:pedidos},{data:cotacoes},{data:fornecedores}]=await Promise.all([
    supabase.from("compras_solicitacoes").select("id,numero,setor,prioridade,status,justificativa,created_at").order("created_at",{ascending:false}).limit(100),
    supabase.from("compras_pedidos").select("id,numero,data_pedido,previsao_entrega,valor_total,status,fornecedor:fornecedores(nome_fantasia,razao_social)").order("created_at",{ascending:false}).limit(100),
    supabase.from("compras_cotacoes").select("id,numero,status,validade,solicitacao:compras_solicitacoes(numero,setor),fornecedores:compras_cotacao_fornecedores(id,fornecedor_id,valor_total,prazo_entrega_dias,condicao_pagamento,frete,selecionado,fornecedor:fornecedores(nome_fantasia,razao_social))").order("created_at",{ascending:false}).limit(50),
    supabase.from("fornecedores").select("id,nome_fantasia,razao_social").eq("ativo",true).order("nome_fantasia")
  ]);
  const abertas=(sols??[]).filter(s=>!["concluida","cancelada"].includes(s.status)).length;
  const cotacoesAbertas=(cotacoes??[]).filter(c=>!["aprovada","cancelada"].includes(c.status)).length;

  return <SectionPage eyebrow="Gestão / Suprimentos" title="Compras" description="Solicitação → cotação → aprovação → pedido, em uma única área de trabalho.">
    <section className="grid gap-3 sm:grid-cols-3"><Kpi label="Solicitações abertas" value={abertas}/><Kpi label="Cotações em andamento" value={cotacoesAbertas}/><Kpi label="Pedidos" value={pedidos?.length??0}/></section>

    <div className="mt-5">
      <ActionPanel title="Nova operação de compras" description="Abra uma solicitação ou inicie a cotação de uma solicitação existente.">
        <div className="grid gap-5 xl:grid-cols-2">
          <form action={criarSolicitacaoCompra} className="rounded-2xl border border-slate-200 bg-white p-4"><h3 className="font-bold text-slate-900">Nova solicitação</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><input name="setor" className="ui-input" placeholder="Setor solicitante"/><select name="prioridade" className="ui-input"><option value="normal">Normal</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select><input name="justificativa" className="ui-input md:col-span-2" placeholder="Justificativa"/><div className="md:col-span-2 flex justify-end"><button className="ui-button-primary">Criar solicitação</button></div></div></form>
          <form action={criarCotacaoCompra} className="rounded-2xl border border-slate-200 bg-white p-4"><h3 className="font-bold text-slate-900">Abrir cotação</h3><div className="mt-4 grid gap-3"><select name="solicitacao_id" required defaultValue="" className="ui-input"><option value="">Selecione a solicitação</option>{sols?.filter(s=>["solicitada","aprovada","em_cotacao"].includes(s.status)).map(s=><option key={s.id} value={s.id}>{s.numero} · {s.setor||"Sem setor"}</option>)}</select><div className="grid gap-3 md:grid-cols-2"><input name="validade" type="date" className="ui-input"/><input name="observacoes" className="ui-input" placeholder="Observações"/></div><div className="flex justify-end"><button className="ui-button-primary">Criar cotação</button></div></div></form>
        </div>
      </ActionPanel>
    </div>

    <section className="ui-card mt-5 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-900">Cotações comparativas</h2><p className="mt-1 text-xs text-slate-500">Adicione propostas e aprove o fornecedor sem sair da mesma tela.</p></div><div className="divide-y divide-slate-100">{cotacoes?.length?cotacoes.map(c=>{const s=one(c.solicitacao);const propostas=Array.isArray(c.fornecedores)?c.fornecedores:[];return <details key={c.id} className="group"><summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3 p-5 hover:bg-slate-50"><div><b>{c.numero}</b><p className="text-sm text-slate-500">{s?.numero??"—"} · {s?.setor??"—"} · {propostas.length} proposta(s)</p></div><span className="text-xs font-semibold capitalize text-brand-700">{c.status.replaceAll("_"," ")}</span></summary><div className="border-t border-slate-100 bg-slate-50/40 p-5"><form action={adicionarFornecedorCotacao} className="grid gap-2 lg:grid-cols-[1fr_150px_120px_180px_120px_auto]"><input type="hidden" name="cotacao_id" value={c.id}/><select name="fornecedor_id" required defaultValue="" className="ui-input"><option value="">Fornecedor</option>{fornecedores?.map(f=><option key={f.id} value={f.id}>{f.nome_fantasia||f.razao_social}</option>)}</select><input name="valor_total" placeholder="Valor" className="ui-input"/><input name="frete" placeholder="Frete" className="ui-input"/><input name="condicao_pagamento" placeholder="Pagamento" className="ui-input"/><input name="prazo_entrega_dias" type="number" placeholder="Prazo dias" className="ui-input"/><button className="ui-button-secondary">Adicionar</button></form><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{propostas.map(p=>{const f=one(p.fornecedor);return <div key={p.id} className={`rounded-xl border p-4 ${p.selecionado?"border-emerald-300 bg-emerald-50":"border-slate-200 bg-white"}`}><div className="flex justify-between gap-2"><b>{f?.nome_fantasia||f?.razao_social||"Fornecedor"}</b>{p.selecionado?<span className="text-xs font-semibold text-emerald-700">Selecionado</span>:null}</div><p className="mt-2 text-lg font-bold">R$ {(Number(p.valor_total||0)+Number(p.frete||0)).toLocaleString("pt-BR",{minimumFractionDigits:2})}</p><p className="text-xs text-slate-500">Prazo {p.prazo_entrega_dias??"—"} dias · {p.condicao_pagamento||"Sem condição"}</p>{!p.selecionado?<form action={aprovarFornecedorCotacao} className="mt-3"><input type="hidden" name="cotacao_id" value={c.id}/><input type="hidden" name="fornecedor_id" value={p.fornecedor_id}/><button className="ui-button-secondary">Aprovar fornecedor</button></form>:null}</div>})}</div></div></details>}):<p className="p-6 text-sm text-slate-500">Nenhuma cotação.</p>}</div></section>

    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="ui-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">Solicitações</h2></div><div className="divide-y divide-slate-100">{sols?.length?sols.map(s=><div key={s.id} className="p-4"><div className="flex justify-between gap-3"><strong>{s.numero}</strong><span className="text-xs font-semibold text-brand-700">{s.status.replaceAll("_"," ")}</span></div><p className="mt-1 text-sm text-slate-500">{s.setor||"Sem setor"} · Prioridade {s.prioridade}</p><p className="mt-1 text-sm text-slate-600">{s.justificativa||"Sem justificativa"}</p></div>):<p className="p-6 text-sm text-slate-500">Nenhuma solicitação.</p>}</div></section><section className="ui-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">Pedidos</h2></div><div className="divide-y divide-slate-100">{pedidos?.length?pedidos.map(p=>{const f=one(p.fornecedor);return <div key={p.id} className="p-4"><div className="flex justify-between gap-3"><strong>{p.numero}</strong><span className="text-xs font-semibold text-brand-700">{p.status}</span></div><p className="mt-1 text-sm text-slate-500">{f?.nome_fantasia||f?.razao_social||"Fornecedor"}</p><p className="mt-1 text-sm font-medium">R$ {Number(p.valor_total||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}</p></div>}):<p className="p-6 text-sm text-slate-500">Nenhum pedido.</p>}</div></section></div>
  </SectionPage>;
}

function Kpi({label,value}:{label:string;value:number}){return <div className="his-kpi"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p></div>}
