import Link from "next/link";
import { ArrowRight, FileText, PackageCheck, Scale } from "lucide-react";
import { ActionPanel } from "@/components/painel/action-panel";
import { SectionPage } from "@/components/painel/section-page";
import { asRoute } from "@/lib/route-cast";
import { requireAnyPermission } from "@/lib/permissions/server";
import { criarSolicitacaoCompra } from "@/modules/compras/actions";

function one<T>(value: T | T[] | null) { return Array.isArray(value) ? value[0] ?? null : value; }

export default async function ComprasPage({ searchParams }: { searchParams: Promise<{ erro?: string; pedido?: string }> }) {
  const sp = await searchParams;
  const { supabase, empresaId, unidadeId } = await requireAnyPermission(["compras.visualizar", "compras.solicitar", "compras.cotar", "compras.aprovar", "compras.gerenciar", "compras.receber"]);
  const [solicitarGrant, gerenciarGrant, { data: sols }, { data: pedidos }, { data: cotacoes }] = await Promise.all([
    supabase.rpc("tem_permissao", { p_empresa: empresaId, p_unidade: unidadeId, p_codigo: "compras.solicitar" }),
    supabase.rpc("tem_permissao", { p_empresa: empresaId, p_unidade: unidadeId, p_codigo: "compras.gerenciar" }),
    supabase.from("compras_solicitacoes").select("id,numero,setor,prioridade,status,justificativa,created_at,itens:compras_solicitacao_itens(id)").eq("empresa_id", empresaId).eq("unidade_id", unidadeId).order("created_at", { ascending: false }).limit(100),
    supabase.from("compras_pedidos").select("id,numero,cotacao_id,data_pedido,previsao_entrega,valor_total,status,fornecedor:fornecedores(nome_fantasia,razao_social),itens:compras_pedido_itens(id,quantidade,quantidade_recebida)").eq("empresa_id", empresaId).eq("unidade_id", unidadeId).order("created_at", { ascending: false }).limit(100),
    supabase.from("compras_cotacoes").select("id,numero,status,validade,solicitacao:compras_solicitacoes(numero,setor),fornecedores:compras_cotacao_fornecedores(id,itens_cotados,itens_total,selecionado)").eq("empresa_id", empresaId).eq("unidade_id", unidadeId).order("created_at", { ascending: false }).limit(100),
  ]);
  const canSolicitar = solicitarGrant.data === true || gerenciarGrant.data === true;
  const abertas = (sols ?? []).filter((s) => !["concluida", "cancelada", "pedido_emitido"].includes(s.status)).length;
  const cotacoesAbertas = (cotacoes ?? []).filter((c) => ["aberta", "em_analise"].includes(c.status)).length;
  const pedidosPendentes = (pedidos ?? []).filter((p) => !["recebido", "cancelado"].includes(p.status)).length;

  return <SectionPage eyebrow="Gestão / Suprimentos" title="Compras" description="Solicitação MATMED → cotação item a item → aprovação → pedido → recebimento por lote → estoque e financeiro, com rastreabilidade de ponta a ponta.">
    {sp.pedido ? <div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">Pedido de compra gerado com sucesso.</div> : null}
    {sp.erro ? <div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">Não foi possível concluir a operação solicitada.</div> : null}
    <section className="grid gap-3 sm:grid-cols-4"><Kpi label="Solicitações abertas" value={abertas} /><Kpi label="Cotações em andamento" value={cotacoesAbertas} /><Kpi label="Pedidos" value={pedidos?.length ?? 0} /><Kpi label="A receber" value={pedidosPendentes} /></section>

    {canSolicitar ? <div className="mt-5"><ActionPanel title="Nova solicitação" description="Crie a necessidade e, na tela seguinte, selecione materiais, medicamentos, OPME ou gases do catálogo mestre."><form action={criarSolicitacaoCompra} className="grid gap-3 lg:grid-cols-[1fr_180px_1.5fr_auto]"><input name="setor" className="ui-input" placeholder="Setor solicitante" /><select name="prioridade" className="ui-input"><option value="normal">Normal</option><option value="alta">Alta</option><option value="urgente">Urgente</option></select><input name="justificativa" className="ui-input" placeholder="Justificativa" /><button className="ui-button-primary">Criar e adicionar itens</button></form></ActionPanel></div> : null}

    <section className="ui-card mt-5 overflow-hidden"><header className="border-b border-slate-100 px-5 py-4"><h2 className="font-black text-slate-900">Solicitações</h2><p className="mt-1 text-xs text-slate-500">Abra para revisar itens, referências e gerar/reabrir a cotação.</p></header><div className="divide-y divide-slate-100">{sols?.length ? sols.map((s) => { const itens = Array.isArray(s.itens) ? s.itens.length : 0; return <Link key={s.id} href={asRoute(`/compras/solicitacoes/${s.id}`)} className="flex flex-wrap items-center justify-between gap-3 p-5 hover:bg-slate-50"><div><div className="flex items-center gap-2"><FileText className="size-4 text-brand-600" /><strong>{s.numero}</strong></div><p className="mt-1 text-sm text-slate-500">{s.setor || "Sem setor"} · Prioridade {s.prioridade} · {itens} item(ns)</p><p className="mt-1 text-sm text-slate-600">{s.justificativa || "Sem justificativa"}</p></div><div className="flex items-center gap-3"><span className="text-xs font-semibold capitalize text-brand-700">{s.status.replaceAll("_", " ")}</span><ArrowRight className="size-4 text-slate-400" /></div></Link>; }) : <p className="p-6 text-sm text-slate-500">Nenhuma solicitação.</p>}</div></section>

    <section className="ui-card mt-5 overflow-hidden"><header className="border-b border-slate-100 px-5 py-4"><h2 className="font-black text-slate-900">Cotações comparativas</h2><p className="mt-1 text-xs text-slate-500">Preço só é comparável quando a quantidade ofertada cobre integralmente o item solicitado.</p></header><div className="divide-y divide-slate-100">{cotacoes?.length ? cotacoes.map((c) => { const solicitacao = one(c.solicitacao); const fornecedores = Array.isArray(c.fornecedores) ? c.fornecedores : []; const completos = fornecedores.filter((f) => f.itens_total > 0 && f.itens_cotados >= f.itens_total).length; return <Link key={c.id} href={asRoute(`/compras/cotacoes/${c.id}`)} className="flex flex-wrap items-center justify-between gap-3 p-5 hover:bg-slate-50"><div><div className="flex items-center gap-2"><Scale className="size-4 text-brand-600" /><strong>{c.numero}</strong></div><p className="mt-1 text-sm text-slate-500">{solicitacao?.numero || "—"} · {solicitacao?.setor || "Sem setor"} · {fornecedores.length} fornecedor(es) · {completos} completo(s)</p></div><div className="flex items-center gap-3"><span className="text-xs font-semibold capitalize text-brand-700">{c.status.replaceAll("_", " ")}</span><ArrowRight className="size-4 text-slate-400" /></div></Link>; }) : <p className="p-6 text-sm text-slate-500">Nenhuma cotação.</p>}</div></section>

    <section className="ui-card mt-5 overflow-hidden"><header className="border-b border-slate-100 px-5 py-4"><h2 className="font-black text-slate-900">Pedidos e recebimento</h2><p className="mt-1 text-xs text-slate-500">Abra o pedido para conferir entrega parcial, lote, validade, divergência, estoque e documento fiscal.</p></header><div className="divide-y divide-slate-100">{pedidos?.length ? pedidos.map((p) => { const fornecedor = one(p.fornecedor); const itens = Array.isArray(p.itens) ? p.itens : []; const qtd = itens.reduce((t, item) => t + Number(item.quantidade ?? 0), 0); const recebida = itens.reduce((t, item) => t + Number(item.quantidade_recebida ?? 0), 0); const pendente = Math.max(qtd - recebida, 0); return <Link key={p.id} href={asRoute(`/compras/pedidos/${p.id}`)} className="flex flex-wrap items-center justify-between gap-3 p-5 hover:bg-slate-50"><div><div className="flex items-center gap-2"><PackageCheck className="size-4 text-brand-600" /><strong>{p.numero}</strong></div><p className="mt-1 text-sm text-slate-500">{fornecedor?.nome_fantasia || fornecedor?.razao_social || "Fornecedor"} · {p.previsao_entrega ? `previsão ${new Date(`${p.previsao_entrega}T12:00:00`).toLocaleDateString("pt-BR")}` : "sem previsão"}</p><p className="mt-1 text-xs font-semibold text-slate-500">Recebido {recebida.toLocaleString("pt-BR")} / {qtd.toLocaleString("pt-BR")} · pendente {pendente.toLocaleString("pt-BR")}</p></div><div className="flex items-center gap-4"><div className="text-right"><p className="font-black text-slate-950">R$ {Number(p.valor_total || 0).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</p><p className="text-xs font-semibold capitalize text-brand-700">{p.status.replaceAll("_", " ")}</p></div><ArrowRight className="size-4 text-slate-400" /></div></Link>; }) : <p className="p-6 text-sm text-slate-500">Nenhum pedido.</p>}</div></section>
  </SectionPage>;
}

function Kpi({ label, value }: { label: string; value: number }) { return <div className="his-kpi"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p></div>; }
