import Link from "next/link";
import { Database, PackageSearch, Upload } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { criarEdicaoTabela, criarFonteTabela, importarItensTabela, salvarValoresPortesCbhpm, vincularTabelaContrato } from "@/modules/comercial/tabelas-actions";

function one<T>(r:T|T[]|null){return Array.isArray(r)?r[0]??null:r;}

export default async function TabelasComerciaisPage({searchParams}:{searchParams:Promise<{erro?:string;importado?:string;portes?:string}>}){
  const qs=await searchParams; const supabase=await createClient();
  const [{data:fontes},{data:edicoes},{data:contratos},{data:convenios}] = await Promise.all([
    supabase.from("tabelas_comerciais_fontes").select("id,codigo,nome,tipo,proprietaria,ativo").order("nome"),
    supabase.from("tabelas_comerciais_edicoes").select("id,fonte_id,convenio_id,nome_edicao,referencia,vigencia_inicio,vigencia_fim,status,metodo_calculo,valor_uco,fonte:tabelas_comerciais_fontes(nome,tipo),convenio:convenios(nome_fantasia),itens:tabelas_comerciais_itens(count)").order("vigencia_inicio",{ascending:false}).limit(100),
    supabase.from("credenciamento_contratos").select("id,numero_contrato,status,convenio:convenios(nome_fantasia)").eq("status","ativo").order("created_at",{ascending:false}),
    supabase.from("convenios").select("id,nome_fantasia").eq("ativo",true).order("nome_fantasia")
  ]);
  const edicoesCbhpm=(edicoes??[]).filter(e=>one(e.fonte)?.tipo==="cbhpm");
  return <SectionPage eyebrow="Comercial / Tabelas" title="Tabelas comerciais e referenciais" description="Gerencie tabela própria, TUSS/TISS, AMB, CBHPM, SIMPRO, BRASÍNDICE, CMED e OPME por edição, vigência e contrato." actions={<Link href="/comercial/tabelas/itens" className="btn-secondary"><PackageSearch className="size-4"/>Itens assistenciais / MATMED</Link>}>
    {qs.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">Falha: {qs.erro}</div>:null}{qs.importado?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{qs.importado} item(ns) importado(s) com sucesso.</div>:null}{qs.portes?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">Valores de portes CBHPM atualizados.</div>:null}
    <div className="mb-6 grid gap-3 md:grid-cols-3"><div className="his-card p-4"><b className="text-sm text-slate-900">TISS / TUSS</b><p className="mt-1 text-xs leading-5 text-slate-500">Tabela 00 para códigos próprios, 98 para pacotes e 18/19/20/22 quando existir código TUSS vigente.</p></div><div className="his-card p-4"><b className="text-sm text-slate-900">Brasíndice / SIMPRO</b><p className="mt-1 text-xs leading-5 text-slate-500">Fontes comerciais licenciadas, mantidas por edição e vigência. Não substituem o código da tabela usado no TISS.</p></div><div className="his-card p-4"><b className="text-sm text-slate-900">CMED / ANVISA</b><p className="mt-1 text-xs leading-5 text-slate-500">Referência regulatória de medicamentos, com PF/PMC/PMVG e demais campos conforme o arquivo importado.</p></div></div>
    <div className="grid gap-6 xl:grid-cols-2">
      <form action={criarFonteTabela} className="ui-card p-5"><div className="flex items-center gap-2"><Database className="size-5 text-brand-700"/><h2 className="font-semibold">Nova fonte</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input name="codigo" required className="ui-input" placeholder="Código interno"/><input name="nome" required className="ui-input" placeholder="Nome da tabela"/><select name="tipo" className="ui-input"><option value="amb90">AMB 90</option><option value="amb92">AMB 92</option><option value="amb96">AMB 96</option><option value="amb99">AMB 99</option><option value="cbhpm">CBHPM</option><option value="procedimentos_convenio">Procedimentos próprios do convênio</option><option value="simpro">SIMPRO</option><option value="brasindice">BRASÍNDICE</option><option value="cmed">CMED / ANVISA</option><option value="opme_convenio">OPME do convênio</option><option value="propria_convenio">Tabela própria do convênio</option><option value="propria_hospital">Tabela própria do hospital</option><option value="medicamentos_convenio">Medicamentos do convênio</option><option value="materiais_convenio">Materiais do convênio</option><option value="outra">Outra</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="proprietaria"/>Tabela proprietária/licenciada</label><textarea name="observacoes" className="ui-input md:col-span-2" rows={2} placeholder="Observações"/><button className="ui-button-primary">Salvar fonte</button></div></form>
      <form action={criarEdicaoTabela} className="ui-card p-5"><h2 className="font-semibold">Nova edição</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><select name="fonte_id" required className="ui-input" defaultValue=""><option value="">Fonte</option>{fontes?.map(f=><option key={f.id} value={f.id}>{f.nome}</option>)}</select><select name="convenio_id" className="ui-input" defaultValue=""><option value="">Geral / todos os convênios</option>{convenios?.map(c=><option key={c.id} value={c.id}>{c.nome_fantasia}</option>)}</select><input name="nome_edicao" required className="ui-input" placeholder="Ex.: Brasíndice Ago/2026 / CMED 08/2026"/><input name="referencia" className="ui-input" placeholder="Referência/edição"/><select name="metodo_calculo" className="ui-input"><option value="fixo">Valor fixo / referência</option><option value="ch_hm_sadt">CH / HM / SADT</option><option value="cbhpm">CBHPM porte + UCO</option></select><input name="valor_uco" className="ui-input" placeholder="Valor UCO da edição (CBHPM)"/><input type="date" name="vigencia_inicio" required className="ui-input"/><input type="date" name="vigencia_fim" className="ui-input"/><select name="status" className="ui-input"><option value="rascunho">Rascunho</option><option value="vigente">Vigente</option></select><button className="ui-button-primary">Criar edição</button></div></form>
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2">
      <form action={importarItensTabela} className="ui-card p-5"><div className="flex items-center gap-2"><Upload className="size-5 text-brand-700"/><h2 className="font-semibold">Importar itens CSV</h2></div><p className="mt-1 text-sm leading-6 text-slate-500">Além de código/descrição/valor, aceita categoria, codigo_interno, TUSS, código próprio 00/98, fabricante, ANVISA, Brasíndice, SIMPRO, EAN/GTIN, GGREM, PF, PMC, PMVG, ICMS e lista CMED.</p><div className="mt-4 grid gap-3"><select name="edicao_id" required className="ui-input" defaultValue=""><option value="">Selecione a edição</option>{edicoes?.map(e=>{const f=one(e.fonte);const c=one(e.convenio);return <option key={e.id} value={e.id}>{f?.nome} · {e.nome_edicao}{c?` · ${c.nome_fantasia}`:""}</option>})}</select><input type="file" name="arquivo" accept=".csv,text/csv" required className="ui-input"/><button className="ui-button-primary">Importar</button></div></form>
      <form action={vincularTabelaContrato} className="ui-card p-5"><h2 className="font-semibold">Vincular ao contrato e parametrizar</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><select name="contrato_id" required className="ui-input" defaultValue=""><option value="">Contrato</option>{contratos?.map(c=>{const v=one(c.convenio);return <option key={c.id} value={c.id}>{v?.nome_fantasia} · {c.numero_contrato||"Sem nº"}</option>})}</select><select name="fonte_id" required className="ui-input" defaultValue=""><option value="">Fonte</option>{fontes?.map(f=><option key={f.id} value={f.id}>{f.nome}</option>)}</select><select name="categoria" className="ui-input"><option value="procedimentos">Procedimentos / exames</option><option value="opme">OPME</option><option value="medicamentos">Medicamentos</option><option value="materiais">Materiais</option><option value="taxas">Taxas</option><option value="diarias">Diárias</option><option value="gases">Gases medicinais</option><option value="geral">Geral</option></select><select name="modo_edicao" className="ui-input"><option value="vigente_na_data">Edição vigente na data</option><option value="edicao_fixa">Edição fixa do contrato</option></select><select name="edicao_fixa_id" className="ui-input" defaultValue=""><option value="">Sem edição fixa</option>{edicoes?.map(e=><option key={e.id} value={e.id}>{e.nome_edicao}</option>)}</select><input name="percentual_ajuste" className="ui-input" placeholder="Ajuste % (ex.: -10 ou 5)"/><input name="valor_ch" className="ui-input" placeholder="Valor CH negociado"/><input name="valor_hm" className="ui-input" placeholder="Valor HM negociado"/><input name="valor_sadt" className="ui-input" placeholder="Valor SADT negociado"/><input name="valor_uco_contratual" className="ui-input" placeholder="UCO contratual (se diferente)"/><input name="urgencia_percentual" className="ui-input" placeholder="Adicional urgência %"/><input name="apartamento_percentual" className="ui-input" placeholder="Adicional apartamento %"/><input name="horario_especial_regra" className="ui-input md:col-span-2" placeholder="Regra/observação de horário especial do contrato"/><input name="prioridade" className="ui-input" defaultValue="100" placeholder="Prioridade"/><input name="arredondamento_casas" className="ui-input" defaultValue="2" placeholder="Casas decimais"/><button className="ui-button-primary">Vincular regra</button></div></form>
    </div>
    {edicoesCbhpm.length?<form action={salvarValoresPortesCbhpm} className="ui-card mt-6 p-5"><h2 className="font-semibold">Valores dos portes CBHPM</h2><p className="mt-1 text-sm text-slate-500">Cadastre os valores monetários dos portes para a edição escolhida. O UCO fica na edição ou pode ser sobrescrito no contrato.</p><div className="mt-4 grid gap-3"><select name="edicao_id" required className="ui-input max-w-md" defaultValue=""><option value="">Edição CBHPM</option>{edicoesCbhpm.map(e=><option key={e.id} value={e.id}>{e.nome_edicao}</option>)}</select><div className="grid gap-2 sm:grid-cols-3 md:grid-cols-6 xl:grid-cols-7">{Array.from({length:14},(_,i)=>i+1).flatMap(n=>["A","B","C"].map(l=><input key={`${n}${l}`} name={`porte_${n}${l}`} className="ui-input" placeholder={`${n}${l}`}/>))}</div><button className="ui-button-primary w-fit">Salvar portes</button></div></form>:null}
    <section className="ui-card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold">Edições cadastradas</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Fonte</th><th className="px-4 py-3">Edição</th><th className="px-4 py-3">Método</th><th className="px-4 py-3">Convênio</th><th className="px-4 py-3">Vigência</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{edicoes?.length?edicoes.map(e=>{const f=one(e.fonte),c=one(e.convenio);return <tr key={e.id}><td className="px-4 py-3"><b>{f?.nome}</b><div className="text-xs text-slate-400">{f?.tipo}</div></td><td className="px-4 py-3">{e.nome_edicao}<div className="text-xs text-slate-400">{e.referencia||"—"}</div></td><td className="px-4 py-3">{e.metodo_calculo}</td><td className="px-4 py-3">{c?.nome_fantasia||"Geral"}</td><td className="px-4 py-3">{e.vigencia_inicio} → {e.vigencia_fim||"aberta"}</td><td className="px-4 py-3 capitalize">{e.status}</td></tr>}):<tr><td colSpan={6} className="p-8 text-center text-slate-500">Nenhuma edição cadastrada.</td></tr>}</tbody></table></div></section>
  </SectionPage>;
}