import { Database, Upload } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { criarEdicaoTabela, criarFonteTabela, importarItensTabela, vincularTabelaContrato } from "@/modules/comercial/tabelas-actions";

function one<T>(r:T|T[]|null){return Array.isArray(r)?r[0]??null:r;}

export default async function TabelasComerciaisPage({searchParams}:{searchParams:Promise<{erro?:string;importado?:string}>}){
  const qs=await searchParams; const supabase=await createClient();
  const [{data:fontes},{data:edicoes},{data:contratos},{data:convenios}] = await Promise.all([
    supabase.from("tabelas_comerciais_fontes").select("id,codigo,nome,tipo,proprietaria,ativo").order("nome"),
    supabase.from("tabelas_comerciais_edicoes").select("id,fonte_id,convenio_id,nome_edicao,referencia,vigencia_inicio,vigencia_fim,status,fonte:tabelas_comerciais_fontes(nome,tipo),convenio:convenios(nome_fantasia),itens:tabelas_comerciais_itens(count)").order("vigencia_inicio",{ascending:false}).limit(100),
    supabase.from("credenciamento_contratos").select("id,numero_contrato,status,convenio:convenios(nome_fantasia)").eq("status","ativo").order("created_at",{ascending:false}),
    supabase.from("convenios").select("id,nome_fantasia").eq("ativo",true).order("nome_fantasia")
  ]);
  return <SectionPage eyebrow="Comercial / Tabelas" title="Tabelas comerciais versionadas" description="Gerencie SIMPRO, BRASÍNDICE, OPME e tabelas próprias de convênio por edição e vigência, sem perder histórico.">
    {qs.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">Falha: {qs.erro}</div>:null}{qs.importado?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">Itens importados com sucesso.</div>:null}
    <div className="grid gap-6 xl:grid-cols-2">
      <form action={criarFonteTabela} className="ui-card p-5"><div className="flex items-center gap-2"><Database className="size-5 text-brand-700"/><h2 className="font-semibold">Nova fonte</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input name="codigo" required className="ui-input" placeholder="Código interno"/><input name="nome" required className="ui-input" placeholder="Nome da tabela"/><select name="tipo" className="ui-input"><option value="simpro">SIMPRO</option><option value="brasindice">BRASÍNDICE</option><option value="opme_convenio">OPME do convênio</option><option value="propria_convenio">Tabela própria do convênio</option><option value="medicamentos_convenio">Medicamentos do convênio</option><option value="materiais_convenio">Materiais do convênio</option><option value="outra">Outra</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="proprietaria"/>Tabela proprietária/licenciada</label><textarea name="observacoes" className="ui-input md:col-span-2" rows={2} placeholder="Observações"/><button className="ui-button-primary">Salvar fonte</button></div></form>
      <form action={criarEdicaoTabela} className="ui-card p-5"><h2 className="font-semibold">Nova edição</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><select name="fonte_id" required className="ui-input" defaultValue=""><option value="">Fonte</option>{fontes?.map(f=><option key={f.id} value={f.id}>{f.nome}</option>)}</select><select name="convenio_id" className="ui-input" defaultValue=""><option value="">Geral / todos os convênios</option>{convenios?.map(c=><option key={c.id} value={c.id}>{c.nome_fantasia}</option>)}</select><input name="nome_edicao" required className="ui-input" placeholder="Ex.: Setembro/2026"/><input name="referencia" className="ui-input" placeholder="Referência/edição"/><input type="date" name="vigencia_inicio" required className="ui-input"/><input type="date" name="vigencia_fim" className="ui-input"/><select name="status" className="ui-input"><option value="rascunho">Rascunho</option><option value="vigente">Vigente</option></select><button className="ui-button-primary">Criar edição</button></div></form>
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2">
      <form action={importarItensTabela} className="ui-card p-5"><div className="flex items-center gap-2"><Upload className="size-5 text-brand-700"/><h2 className="font-semibold">Importar itens CSV</h2></div><p className="mt-1 text-sm text-slate-500">Colunas mínimas: codigo, descricao, valor. Opcionais: fabricante, codigo_fabricante, codigo_anvisa, codigo_tuss, apresentacao, unidade.</p><div className="mt-4 grid gap-3"><select name="edicao_id" required className="ui-input" defaultValue=""><option value="">Selecione a edição</option>{edicoes?.map(e=>{const f=one(e.fonte);const c=one(e.convenio);return <option key={e.id} value={e.id}>{f?.nome} · {e.nome_edicao}{c?` · ${c.nome_fantasia}`:""}</option>})}</select><input type="file" name="arquivo" accept=".csv,text/csv" required className="ui-input"/><button className="ui-button-primary">Importar</button></div></form>
      <form action={vincularTabelaContrato} className="ui-card p-5"><h2 className="font-semibold">Vincular ao contrato</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><select name="contrato_id" required className="ui-input" defaultValue=""><option value="">Contrato</option>{contratos?.map(c=>{const v=one(c.convenio);return <option key={c.id} value={c.id}>{v?.nome_fantasia} · {c.numero_contrato||"Sem nº"}</option>})}</select><select name="fonte_id" required className="ui-input" defaultValue=""><option value="">Fonte</option>{fontes?.map(f=><option key={f.id} value={f.id}>{f.nome}</option>)}</select><select name="categoria" className="ui-input"><option value="opme">OPME</option><option value="medicamentos">Medicamentos</option><option value="materiais">Materiais</option><option value="geral">Geral</option></select><select name="modo_edicao" className="ui-input"><option value="vigente_na_data">Edição vigente na data</option><option value="edicao_fixa">Edição fixa do contrato</option></select><select name="edicao_fixa_id" className="ui-input" defaultValue=""><option value="">Sem edição fixa</option>{edicoes?.map(e=><option key={e.id} value={e.id}>{e.nome_edicao}</option>)}</select><input name="percentual_ajuste" className="ui-input" placeholder="Ajuste % (ex.: -10 ou 5)"/><input name="prioridade" className="ui-input" defaultValue="100" placeholder="Prioridade"/><button className="ui-button-primary">Vincular regra</button></div></form>
    </div>
    <section className="ui-card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold">Edições cadastradas</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Fonte</th><th className="px-4 py-3">Edição</th><th className="px-4 py-3">Convênio</th><th className="px-4 py-3">Vigência</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{edicoes?.length?edicoes.map(e=>{const f=one(e.fonte),c=one(e.convenio);return <tr key={e.id}><td className="px-4 py-3"><b>{f?.nome}</b><div className="text-xs text-slate-400">{f?.tipo}</div></td><td className="px-4 py-3">{e.nome_edicao}<div className="text-xs text-slate-400">{e.referencia||"—"}</div></td><td className="px-4 py-3">{c?.nome_fantasia||"Geral"}</td><td className="px-4 py-3">{e.vigencia_inicio} → {e.vigencia_fim||"aberta"}</td><td className="px-4 py-3 capitalize">{e.status}</td></tr>}):<tr><td colSpan={5} className="p-8 text-center text-slate-500">Nenhuma edição cadastrada.</td></tr>}</tbody></table></div></section>
  </SectionPage>;
}
