import { ActionPanel } from "@/components/painel/action-panel";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { criarMovimentoEstoque } from "@/modules/corporativo/actions";

function one<T>(r:T|T[]|null){return Array.isArray(r)?r[0]??null:r;}

export default async function AlmoxarifadoPage(){
  const supabase=await createClient();
  const [{data:produtos},{data:locais},{data:lotes},{data:movs}]=await Promise.all([
    supabase.from("estoque_produtos").select("id,codigo,descricao,tipo,unidade_medida,estoque_minimo").eq("ativo",true).order("descricao").limit(300),
    supabase.from("estoque_locais").select("id,nome,tipo").eq("ativo",true).order("nome"),
    supabase.from("estoque_lotes").select("id,numero_lote,validade,quantidade,custo_unitario,produto:estoque_produtos(codigo,descricao),local:estoque_locais(nome)").order("validade",{ascending:true}).limit(200),
    supabase.from("estoque_movimentos").select("id,tipo,quantidade,motivo,created_at,produto:estoque_produtos(codigo,descricao),origem:estoque_locais!estoque_movimentos_local_origem_id_fkey(nome),destino:estoque_locais!estoque_movimentos_local_destino_id_fkey(nome),atendimento:atendimentos(numero_atendimento,paciente:pacientes(nome_completo,ra,numero_registro))").order("created_at",{ascending:false}).limit(100)
  ]);
  const vencendo=(lotes??[]).filter(l=>l.validade&&new Date(l.validade).getTime()<=Date.now()+30*24*60*60*1000).length;
  const saldoTotal=(lotes??[]).reduce((total,l)=>total+Number(l.quantidade??0),0);

  return <SectionPage eyebrow="Gestão / Suprimentos" title="Estoque" description="Posição por lote, validade, transferências e consumo assistencial em uma visão única.">
    <section className="grid gap-3 sm:grid-cols-3"><Kpi label="Produtos ativos" value={produtos?.length??0}/><Kpi label="Saldo em lotes" value={saldoTotal}/><Kpi label="Lotes vencendo em 30 dias" value={vencendo}/></section>

    <div className="mt-5"><ActionPanel title="Registrar movimento" description="Entrada, saída, transferência, devolução, ajuste ou consumo vinculado ao paciente."><form action={criarMovimentoEstoque} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select name="produto_id" required defaultValue="" className="ui-input"><option value="">Produto</option>{produtos?.map(p=><option key={p.id} value={p.id}>{p.codigo} · {p.descricao}</option>)}</select><select name="tipo" className="ui-input"><option value="entrada">Entrada</option><option value="saida">Saída</option><option value="transferencia">Transferência</option><option value="consumo_paciente">Consumo paciente</option><option value="devolucao">Devolução</option><option value="ajuste">Ajuste</option></select><input name="quantidade" required inputMode="decimal" className="ui-input" placeholder="Quantidade"/><input name="atendimento_id" className="ui-input" placeholder="Atendimento ID (opcional)"/><select name="local_origem_id" defaultValue="" className="ui-input"><option value="">Local origem</option>{locais?.map(l=><option key={l.id} value={l.id}>{l.nome}</option>)}</select><select name="local_destino_id" defaultValue="" className="ui-input"><option value="">Local destino</option>{locais?.map(l=><option key={l.id} value={l.id}>{l.nome}</option>)}</select><input name="motivo" className="ui-input md:col-span-2" placeholder="Motivo/observação"/><div className="md:col-span-2 xl:col-span-4 flex justify-end"><button className="ui-button-primary">Registrar movimento</button></div></form></ActionPanel></div>

    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="ui-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-900">Posição por lote</h2><p className="mt-1 text-xs text-slate-500">Ordenado por validade para facilitar giro e prevenção de perdas.</p></div><div className="max-h-[720px] divide-y divide-slate-100 overflow-y-auto">{lotes?.length?lotes.map(l=>{const p=one(l.produto);const local=one(l.local);const perto=l.validade&&new Date(l.validade).getTime()<=Date.now()+30*24*60*60*1000;return <div key={l.id} className="p-4"><div className="flex justify-between gap-3"><strong>{p?.descricao??"Produto"}</strong><span className="font-semibold">{Number(l.quantidade)} un.</span></div><p className="mt-1 text-sm text-slate-500">{local?.nome??"Local"} · Lote {l.numero_lote||"—"}</p><p className={`mt-1 text-xs font-semibold ${perto?"text-amber-700":"text-slate-400"}`}>Validade {l.validade||"—"}{perto?" · atenção":""}</p></div>}):<p className="p-6 text-sm text-slate-500">Sem estoque lançado.</p>}</div></section><section className="ui-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-900">Movimentos recentes</h2><p className="mt-1 text-xs text-slate-500">Rastreabilidade de entrada, saída, transferência e consumo.</p></div><div className="max-h-[720px] divide-y divide-slate-100 overflow-y-auto">{movs?.length?movs.map(m=>{const p=one(m.produto);const at=one(m.atendimento);const pac=at?one(at.paciente):null;return <div key={m.id} className="p-4"><div className="flex justify-between gap-3"><strong>{p?.descricao??"Produto"}</strong><span className="text-sm font-semibold text-brand-700">{m.tipo.replaceAll("_"," ")} · {Number(m.quantidade)}</span></div>{at?<p className="mt-1 text-sm text-slate-500">Atendimento #{at.numero_atendimento} · {pac?.nome_completo} · {pac?.ra}</p>:null}<p className="mt-1 text-xs text-slate-400">{m.motivo||"Sem observação"}</p></div>}):<p className="p-6 text-sm text-slate-500">Nenhum movimento.</p>}</div></section></div>
  </SectionPage>;
}

function Kpi({label,value}:{label:string;value:number}){return <div className="his-kpi"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p></div>}
