import Link from "next/link";
import { Boxes, ClipboardCheck, ClipboardList, PackageSearch, RefreshCw } from "lucide-react";
import { ActionPanel } from "@/components/painel/action-panel";
import { SectionPage } from "@/components/painel/section-page";
import { getAssistencialContext } from "@/modules/assistencial/context";
import { movimentarEstoqueOperacionalAction } from "@/modules/almoxarifado/estoque-actions";

export const dynamic = "force-dynamic";
export const revalidate = 0;

function one<T>(r:T|T[]|null){return Array.isArray(r)?r[0]??null:r;}
function fmtDate(value:string|null|undefined){return value?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(`${value}T12:00:00`)):"—";}

export default async function AlmoxarifadoPage({searchParams}:{searchParams:Promise<{sucesso?:string;erro?:string}>}){
  const sp=await searchParams;
  const {supabase,empresaId,unidadeId}=await getAssistencialContext();
  const [{data:produtos},{data:locais},{data:lotes},{data:movs}]=await Promise.all([
    supabase.from("estoque_produtos").select("id,codigo,descricao,tipo,unidade_medida,estoque_minimo,codigo_tuss,codigo_brasindice,codigo_simpro,codigo_anvisa,item:item_assistencial_id(id,categoria,tabela_tiss_codigo,codigo_tuss,codigo_tabela_propria,codigo_anvisa,codigo_brasindice,codigo_simpro)").eq("empresa_id",empresaId).eq("ativo",true).order("descricao").limit(500),
    supabase.from("estoque_locais").select("id,nome,tipo").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).eq("ativo",true).order("nome"),
    supabase.from("estoque_lotes").select("id,numero_lote,validade,quantidade,custo_unitario,status,produto:estoque_produtos(id,codigo,descricao),local:estoque_locais(id,nome)").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).order("validade",{ascending:true}).limit(1000),
    supabase.from("estoque_movimentos").select("id,tipo,quantidade,motivo,created_at,produto:estoque_produtos(codigo,descricao),origem:estoque_locais!estoque_movimentos_local_origem_id_fkey(nome),destino:estoque_locais!estoque_movimentos_local_destino_id_fkey(nome),atendimento:atendimentos(numero_atendimento,paciente:pacientes(nome_completo,ra,numero_registro))").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).order("created_at",{ascending:false}).limit(120)
  ]);
  const vencendo=(lotes??[]).filter(l=>l.validade&&new Date(`${l.validade}T12:00:00`).getTime()<=Date.now()+30*24*60*60*1000&&new Date(`${l.validade}T12:00:00`).getTime()>=Date.now()-24*60*60*1000).length;
  const vencidos=(lotes??[]).filter(l=>l.validade&&new Date(`${l.validade}T12:00:00`).getTime()<Date.now()-24*60*60*1000&&Number(l.quantidade??0)>0).length;
  const saldoTotal=(lotes??[]).reduce((total,l)=>total+Number(l.quantidade??0),0);
  const vinculados=(produtos??[]).filter(p=>one(p.item)).length;
  const lotesMovimentaveis=(lotes??[]).filter(l=>Number(l.quantidade??0)>0);

  return <SectionPage eyebrow="Gestão / Suprimentos" title="Estoque" description="Saldo físico por local, lote e validade, com movimentos transacionais e rastreabilidade até compras, requisições, inventário e atendimento." actions={<div className="flex flex-wrap gap-2"><Link href="/almoxarifado/requisicoes" className="btn-secondary"><ClipboardList className="size-4"/>Requisições</Link><Link href="/almoxarifado/inventarios" className="btn-secondary"><ClipboardCheck className="size-4"/>Inventários</Link><Link href="/almoxarifado/reposicao" className="btn-secondary"><RefreshCw className="size-4"/>Reposição</Link><Link href="/comercial/tabelas/itens" className="btn-secondary"><PackageSearch className="size-4"/>MATMED</Link></div>}>
    {sp.sucesso?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">Operação concluída: {sp.sucesso.replaceAll("_"," ")}.</div>:null}
    {sp.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">Operação bloqueada: {decodeURIComponent(sp.erro)}.</div>:null}

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi label="Produtos ativos" value={produtos?.length??0}/><Kpi label="Vinculados ao catálogo" value={vinculados}/><Kpi label="Saldo físico" value={saldoTotal}/><Kpi label="Vencendo 30 dias" value={vencendo}/><Kpi label="Lotes vencidos c/ saldo" value={vencidos}/></section>

    <div className="mt-5"><ActionPanel title="Movimento operacional" description="O movimento agora atua sobre um lote real e altera o saldo na mesma transação. Ajustes de divergência devem ser feitos pelo Inventário."><form action={movimentarEstoqueOperacionalAction} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select name="lote_id" required defaultValue="" className="ui-input xl:col-span-2"><option value="">Lote / produto / local *</option>{lotesMovimentaveis.map(l=>{const p=one(l.produto),local=one(l.local);return <option key={l.id} value={l.id}>{p?.codigo??"—"} · {p?.descricao??"Produto"} · {local?.nome??"Local"} · lote {l.numero_lote??"s/lote"} · saldo {Number(l.quantidade)}</option>})}</select><select name="tipo" defaultValue="saida" className="ui-input"><option value="saida">Saída</option><option value="transferencia">Transferência</option><option value="consumo_paciente">Consumo paciente</option><option value="entrada">Entrada manual</option><option value="devolucao">Devolução</option></select><input name="quantidade" type="number" min="0.0001" step="0.0001" required className="ui-input" placeholder="Quantidade"/><select name="local_destino_id" defaultValue="" className="ui-input"><option value="">Destino (transferência)</option>{locais?.map(l=><option key={l.id} value={l.id}>{l.nome}</option>)}</select><input name="atendimento_id" className="ui-input" placeholder="Atendimento ID (consumo paciente)"/><input name="motivo" className="ui-input md:col-span-2" placeholder="Motivo / observação"/><div className="md:col-span-2 xl:col-span-4 flex justify-end"><button className="ui-button-primary">Registrar movimento</button></div></form></ActionPanel></div>

    <section className="his-card mt-5 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold text-slate-900">Produtos e codificação</h2><p className="mt-1 text-xs text-slate-500">O estoque controla saldo; o cadastro mestre controla TISS/TUSS, ANVISA e referências Brasíndice/SIMPRO.</p></div><Boxes className="size-5 text-brand-700"/></div><div className="max-h-[520px] overflow-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Produto</th><th className="px-4 py-3">Tipo</th><th className="px-4 py-3">TISS</th><th className="px-4 py-3">Referências</th><th className="px-4 py-3">Mínimo global</th></tr></thead><tbody className="divide-y divide-slate-100">{produtos?.length?produtos.map(p=>{const item=one(p.item);return <tr key={p.id}><td className="px-4 py-3"><b>{p.descricao}</b><div className="text-xs text-slate-400">{p.codigo} · {p.unidade_medida}</div></td><td className="px-4 py-3 capitalize">{item?.categoria?.replaceAll("_"," ")??p.tipo.replaceAll("_"," ")}</td><td className="px-4 py-3">{item?<><b>Tabela {item.tabela_tiss_codigo}</b><div className="text-xs text-slate-500">{item.codigo_tuss?`TUSS ${item.codigo_tuss}`:`Próprio ${item.codigo_tabela_propria??"—"}`}</div></>:<><b className="text-amber-700">Legado</b><div className="text-xs text-slate-500">{p.codigo_tuss?`TUSS ${p.codigo_tuss}`:"Sem vínculo mestre"}</div></>}</td><td className="px-4 py-3 text-xs text-slate-600"><div>{item?.codigo_anvisa??p.codigo_anvisa?`ANVISA ${item?.codigo_anvisa??p.codigo_anvisa}`:"ANVISA —"}</div><div>{item?.codigo_brasindice??p.codigo_brasindice?`Brasíndice ${item?.codigo_brasindice??p.codigo_brasindice}`:"Brasíndice —"}</div><div>{item?.codigo_simpro??p.codigo_simpro?`SIMPRO ${item?.codigo_simpro??p.codigo_simpro}`:"SIMPRO —"}</div></td><td className="px-4 py-3 font-semibold">{Number(p.estoque_minimo??0)}</td></tr>}):<tr><td colSpan={5} className="p-8 text-center text-slate-500">Nenhum produto ativo.</td></tr>}</tbody></table></div></section>

    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="ui-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-900">Posição por lote</h2><p className="mt-1 text-xs text-slate-500">Ordenado por validade para giro FEFO e prevenção de perdas.</p></div><div className="max-h-[720px] divide-y divide-slate-100 overflow-y-auto">{lotes?.length?lotes.map(l=>{const p=one(l.produto);const local=one(l.local);const perto=l.validade&&new Date(`${l.validade}T12:00:00`).getTime()<=Date.now()+30*24*60*60*1000;return <div key={l.id} className="p-4"><div className="flex justify-between gap-3"><strong>{p?.descricao??"Produto"}</strong><span className="font-semibold">{Number(l.quantidade)} un.</span></div><p className="mt-1 text-sm text-slate-500">{local?.nome??"Local"} · Lote {l.numero_lote||"—"} · {l.status}</p><p className={`mt-1 text-xs font-semibold ${perto?"text-amber-700":"text-slate-400"}`}>Validade {fmtDate(l.validade)}{perto?" · atenção":""}</p></div>}):<p className="p-6 text-sm text-slate-500">Sem estoque lançado.</p>}</div></section><section className="ui-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-900">Movimentos recentes</h2><p className="mt-1 text-xs text-slate-500">Rastreabilidade de entrada, saída, transferência, consumo e ajustes de inventário.</p></div><div className="max-h-[720px] divide-y divide-slate-100 overflow-y-auto">{movs?.length?movs.map(m=>{const p=one(m.produto);const at=one(m.atendimento);const pac=at?one(at.paciente):null;return <div key={m.id} className="p-4"><div className="flex justify-between gap-3"><strong>{p?.descricao??"Produto"}</strong><span className="text-sm font-semibold text-brand-700">{m.tipo.replaceAll("_"," ")} · {Number(m.quantidade)}</span></div>{at?<p className="mt-1 text-sm text-slate-500">Atendimento #{at.numero_atendimento} · {pac?.nome_completo} · {pac?.ra}</p>:null}<p className="mt-1 text-xs text-slate-400">{m.motivo||"Sem observação"}</p></div>}):<p className="p-6 text-sm text-slate-500">Nenhum movimento.</p>}</div></section></div>
  </SectionPage>;
}

function Kpi({label,value}:{label:string;value:number}){return <div className="his-kpi"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{Number(value).toLocaleString("pt-BR",{maximumFractionDigits:2})}</p></div>}
