import { Building2, Landmark } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { salvarConfiguracaoNfse } from "@/modules/nfse/actions";

export default async function ConfiguracaoNfsePage({searchParams}:{searchParams:Promise<{sucesso?:string;erro?:string}>}){
  const qs=await searchParams; const supabase=await createClient();
  const {data:configs}=await supabase.from("nfse_configuracoes").select("id,municipio_ibge,municipio_nome,uf,provedor,modo,ambiente,endpoint_url,wsdl_url,versao,codigo_servico_municipal,item_lista_servico,codigo_tributacao_municipio,inscricao_municipal,auth_tipo,auth_usuario_ref,auth_segredo_ref,certificado_ref,ativo").order("municipio_nome");
  return <SectionPage eyebrow="Configurações / NFS-e" title="Prefeituras e emissão de NFS-e" description="Configure emissão manual pelo portal municipal ou integração por API/webservice de cada prefeitura.">
    {qs.sucesso?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">Configuração salva.</div>:null}{qs.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">Não foi possível salvar a configuração.</div>:null}
    <form action={salvarConfiguracaoNfse} className="ui-card p-6"><div className="flex items-center gap-3"><Landmark className="size-5 text-brand-700"/><div><h2 className="font-semibold text-slate-900">Nova configuração municipal</h2><p className="text-sm text-slate-500">Credenciais devem ser referências a secrets/variáveis seguras, nunca senhas em texto puro.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><input name="municipio_ibge" required placeholder="Código IBGE" className="ui-input"/><input name="municipio_nome" required placeholder="Município" className="ui-input"/><input name="uf" required maxLength={2} placeholder="UF" className="ui-input"/><input name="provedor" placeholder="Provedor NFS-e" className="ui-input"/><select name="modo" defaultValue="manual" className="ui-input"><option value="manual">Portal / Manual</option><option value="webservice">Webservice</option><option value="api">API</option></select><select name="ambiente" defaultValue="homologacao" className="ui-input"><option value="homologacao">Homologação</option><option value="producao">Produção</option></select><input name="endpoint_url" placeholder="Endpoint/API" className="ui-input md:col-span-2"/><input name="wsdl_url" placeholder="WSDL" className="ui-input md:col-span-2"/><input name="versao" placeholder="Versão/layout" className="ui-input"/><input name="inscricao_municipal" placeholder="Inscrição municipal" className="ui-input"/><input name="codigo_servico_municipal" placeholder="Código serviço municipal" className="ui-input"/><input name="item_lista_servico" placeholder="Item LC 116" className="ui-input"/><input name="codigo_tributacao_municipio" placeholder="Código tributação município" className="ui-input md:col-span-2"/><select name="auth_tipo" defaultValue="nenhuma" className="ui-input"><option value="nenhuma">Sem autenticação</option><option value="basic">Basic</option><option value="bearer">Bearer</option><option value="header">Header</option><option value="mtls">Certificado/mTLS</option></select><input name="auth_usuario_ref" placeholder="Secret ref usuário" className="ui-input"/><input name="auth_segredo_ref" placeholder="Secret ref senha/token" className="ui-input"/><input name="certificado_ref" placeholder="Secret/path certificado" className="ui-input"/></div><div className="mt-5 flex justify-end"><button className="ui-button-primary">Salvar configuração</button></div></form>
    <section className="ui-card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Configurações existentes</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Município</th><th className="px-4 py-3">Provedor</th><th className="px-4 py-3">Modo</th><th className="px-4 py-3">Ambiente</th><th className="px-4 py-3">Endpoint</th></tr></thead><tbody className="divide-y divide-slate-100">{configs?.length?configs.map(c=><tr key={c.id}><td className="px-4 py-3"><div className="flex items-center gap-2"><Building2 className="size-4 text-brand-700"/><span>{c.municipio_nome}/{c.uf}</span></div><div className="text-xs text-slate-400">IBGE {c.municipio_ibge}</div></td><td className="px-4 py-3">{c.provedor??"—"}</td><td className="px-4 py-3 capitalize">{c.modo}</td><td className="px-4 py-3 capitalize">{c.ambiente}</td><td className="px-4 py-3 max-w-sm truncate">{c.endpoint_url||c.wsdl_url||"Portal manual"}</td></tr>):<tr><td colSpan={5} className="px-4 py-8 text-center text-slate-500">Nenhuma prefeitura configurada.</td></tr>}</tbody></table></div></section>
  </SectionPage>;
}
