import { Building2, Landmark, ShieldCheck } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { requireAnyPermission } from "@/lib/permissions/server";
import { salvarConfiguracaoNfse } from "@/modules/nfse/actions";
import { NFSE_PROVIDERS } from "@/modules/nfse/providers";

export default async function ConfiguracaoNfsePage({searchParams}:{searchParams:Promise<{sucesso?:string;erro?:string}>}){
  const qs=await searchParams;
  const {supabase,empresaId,unidadeId}=await requireAnyPermission(["nfse.visualizar","nfse.configurar","nfse.gerenciar"]);
  const [configsRes,configGrant,manageGrant]=await Promise.all([
    supabase.from("nfse_configuracoes").select("id,municipio_ibge,municipio_nome,uf,provedor,modo,ambiente,endpoint_url,wsdl_url,versao,codigo_servico_municipal,item_lista_servico,codigo_tributacao_municipio,inscricao_municipal,auth_tipo,auth_usuario_ref,auth_segredo_ref,certificado_ref,ativo").order("municipio_nome"),
    unidadeId?supabase.rpc("tem_permissao",{p_empresa:empresaId,p_unidade:unidadeId,p_codigo:"nfse.configurar"}):Promise.resolve({data:false}),
    unidadeId?supabase.rpc("tem_permissao",{p_empresa:empresaId,p_unidade:unidadeId,p_codigo:"nfse.gerenciar"}):Promise.resolve({data:false}),
  ]);
  const configs=configsRes.data??[];
  const canEdit=configGrant.data===true||manageGrant.data===true;
  const errorMessage=qs.erro==="permissao"?"Seu perfil não possui permissão para configurar NFS-e.":qs.erro==="unidade"?"Selecione uma unidade antes de configurar NFS-e.":qs.erro?"Não foi possível salvar a configuração. Revise os campos e o provedor selecionado.":null;

  return <SectionPage eyebrow="Configurações / NFS-e" title="Prefeituras e emissão de NFS-e" description="Configure o Padrão Nacional/SEFIN ou conectores municipais por prefeitura. Cadastro técnico não significa homologação do provedor municipal.">
    {qs.sucesso?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">Configuração salva pelo fluxo RBAC.</div>:null}{errorMessage?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{errorMessage}</div>:null}

    <div className="mb-5 grid gap-3 lg:grid-cols-2">
      <div className="rounded-2xl border border-brand-100 bg-brand-50 p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-5 text-brand-700"/><div><h2 className="font-black text-brand-950">Padrão Nacional / SEFIN</h2><p className="mt-1 text-sm text-brand-800">Integração REST com mTLS. A emissão automática só deve ser usada após DPS XML assinada, certificado A1 e homologação efetiva do ambiente configurado.</p></div></div></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex gap-3"><Landmark className="mt-0.5 size-5 text-slate-600"/><div><h2 className="font-black text-slate-950">Prefeituras com provedor próprio</h2><p className="mt-1 text-sm text-slate-600">ABRASF, GINFES, ISS.Net, SimplISS, Betha e outros variam por município. URL, WSDL, autenticação e layout precisam ser homologados antes de liberar emissão automática.</p></div></div></div>
    </div>

    {canEdit&&unidadeId?<form action={salvarConfiguracaoNfse} className="ui-card p-6"><div className="flex items-center gap-3"><Landmark className="size-5 text-brand-700"/><div><h2 className="font-semibold text-slate-900">Configuração municipal</h2><p className="text-sm text-slate-500">Se município e ambiente já existirem nesta unidade, o RPC atualiza o mesmo registro. Credenciais são referências a secrets, nunca senhas em texto puro.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <input name="municipio_ibge" required placeholder="Código IBGE" className="ui-input"/><input name="municipio_nome" required placeholder="Município" className="ui-input"/><input name="uf" required maxLength={2} placeholder="UF" className="ui-input"/>
      <select name="provedor" defaultValue="padrao_nacional" className="ui-input"><option value="">Portal / sem provedor</option>{Object.entries(NFSE_PROVIDERS).map(([value,p])=><option key={value} value={value}>{p.label}</option>)}</select>
      <select name="modo" defaultValue="api" className="ui-input"><option value="manual">Portal / Manual</option><option value="webservice">Webservice</option><option value="api">API</option></select><select name="ambiente" defaultValue="homologacao" className="ui-input"><option value="homologacao">Homologação</option><option value="producao">Produção</option></select>
      <input name="endpoint_url" placeholder="Endpoint/API (automático no Padrão Nacional)" className="ui-input md:col-span-2"/><input name="wsdl_url" placeholder="WSDL para provedor municipal legado" className="ui-input md:col-span-2"/>
      <input name="versao" placeholder="Versão/layout" className="ui-input"/><input name="inscricao_municipal" placeholder="Inscrição municipal" className="ui-input"/><input name="codigo_servico_municipal" placeholder="Código serviço municipal" className="ui-input"/><input name="item_lista_servico" placeholder="Item LC 116" className="ui-input"/><input name="codigo_tributacao_municipio" placeholder="Código tributação município" className="ui-input md:col-span-2"/>
      <select name="auth_tipo" defaultValue="mtls" className="ui-input"><option value="nenhuma">Sem autenticação</option><option value="basic">Basic</option><option value="bearer">Bearer</option><option value="header">Header</option><option value="mtls">Certificado/mTLS</option></select><input name="auth_usuario_ref" placeholder="Secret ref usuário" className="ui-input"/><input name="auth_segredo_ref" placeholder="Variável da senha do PFX" className="ui-input"/><input name="certificado_ref" placeholder="Variável com PFX Base64" className="ui-input"/>
    </div><div className="mt-5 rounded-xl bg-slate-50 px-4 py-3 text-xs text-slate-600"><strong>Certificado:</strong> para o Padrão Nacional, o campo de certificado referencia a variável segura do Vercel com o PFX A1 em Base64; a senha fica em outra variável segura.</div><div className="mt-5 flex justify-end"><button className="ui-button-primary">Salvar configuração</button></div></form>:<div className="ui-card p-5 text-sm text-slate-600">{unidadeId?"Você pode consultar as configurações, mas não possui permissão para alterá-las.":"Selecione uma unidade para criar ou alterar configurações NFS-e."}</div>}

    <section className="ui-card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Configurações existentes</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Município</th><th className="px-4 py-3">Provedor</th><th className="px-4 py-3">Modo</th><th className="px-4 py-3">Ambiente</th><th className="px-4 py-3">Endpoint</th></tr></thead><tbody className="divide-y divide-slate-100">{configs.length?configs.map(c=><tr key={c.id}><td className="px-4 py-3"><div className="flex items-center gap-2"><Building2 className="size-4 text-brand-700"/><span>{c.municipio_nome}/{c.uf}</span></div><div className="text-xs text-slate-400">IBGE {c.municipio_ibge}</div></td><td className="px-4 py-3">{c.provedor?NFSE_PROVIDERS[c.provedor as keyof typeof NFSE_PROVIDERS]?.label??c.provedor:"—"}</td><td className="px-4 py-3 capitalize">{c.modo}</td><td className="px-4 py-3 capitalize">{c.ambiente}</td><td className="px-4 py-3 max-w-sm truncate">{c.endpoint_url||c.wsdl_url||"Portal manual"}</td></tr>):<tr><td colSpan={5} className="px-4 py-8 text-center text-slate-500">Nenhuma prefeitura visível no escopo atual.</td></tr>}</tbody></table></div></section>
  </SectionPage>;
}
