import { Cable, ShieldCheck } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { salvarConfiguracaoWebservice } from "@/modules/tiss/webservices/actions";

function one<T>(rel:T|T[]|null){return Array.isArray(rel)?rel[0]??null:rel;}

export default async function TissWebservicesPage({searchParams}:{searchParams:Promise<{erro?:string;sucesso?:string}>}){
  const qs=await searchParams; const supabase=await createClient();
  const [{data:convenios},{data:configs}] = await Promise.all([
    supabase.from("convenios").select("id,nome_fantasia,registro_ans").eq("ativo",true).order("nome_fantasia"),
    supabase.from("tiss_webservice_configuracoes").select("id,ambiente,ativo,versao_comunicacao,transporte,endpoint_url,wsdl_url,tipo_autenticacao,codigo_prestador_operadora,timeout_ms,convenio:convenios(nome_fantasia,registro_ans)").order("updated_at",{ascending:false})
  ]);
  return <SectionPage eyebrow="Configurações / TISS" title="Webservices das operadoras" description="Configure homologação e produção por convênio. Segredos e certificados são referenciados por variáveis seguras, nunca armazenados em texto puro.">
    {qs.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">Não foi possível salvar a configuração.</div>:null}
    {qs.sucesso?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">Configuração salva com sucesso.</div>:null}
    <div className="grid gap-6 xl:grid-cols-[1fr_0.9fr]">
      <form action={salvarConfiguracaoWebservice} className="ui-card p-6"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><Cable className="size-5"/></span><div><h2 className="font-semibold text-slate-900">Nova configuração</h2><p className="text-sm text-slate-500">Use os dados técnicos fornecidos pela operadora para o prestador.</p></div></div><div className="grid gap-4 md:grid-cols-2">
        <label className="space-y-2 text-sm font-medium text-slate-700 md:col-span-2"><span>Operadora *</span><select name="convenio_id" required defaultValue="" className="ui-input"><option value="">Selecione</option>{convenios?.map(c=><option key={c.id} value={c.id}>{c.nome_fantasia} · ANS {c.registro_ans??"—"}</option>)}</select></label>
        <label className="space-y-2 text-sm font-medium text-slate-700"><span>Ambiente</span><select name="ambiente" defaultValue="homologacao" className="ui-input"><option value="homologacao">Homologação</option><option value="producao">Produção</option></select></label>
        <label className="space-y-2 text-sm font-medium text-slate-700"><span>Versão comunicação</span><select name="versao_comunicacao" defaultValue="04.03.00" className="ui-input"><option value="04.03.00">04.03.00</option><option value="01.06.00">01.06.00</option></select></label>
        <label className="space-y-2 text-sm font-medium text-slate-700"><span>Transporte</span><select name="transporte" defaultValue="soap" className="ui-input"><option value="soap">SOAP</option><option value="http_xml">HTTP XML</option><option value="sftp">SFTP</option><option value="manual">Manual</option></select></label>
        <label className="space-y-2 text-sm font-medium text-slate-700"><span>Autenticação</span><select name="tipo_autenticacao" defaultValue="nenhuma" className="ui-input"><option value="nenhuma">Nenhuma</option><option value="basic">Basic</option><option value="bearer">Bearer</option><option value="cabecalho">Cabeçalho customizado</option><option value="certificado_mtls">Certificado mTLS</option></select></label>
        <label className="space-y-2 text-sm font-medium text-slate-700 md:col-span-2"><span>Endpoint</span><input name="endpoint_url" type="url" className="ui-input" placeholder="https://operadora.../tiss"/></label>
        <label className="space-y-2 text-sm font-medium text-slate-700 md:col-span-2"><span>WSDL</span><input name="wsdl_url" type="url" className="ui-input" placeholder="https://operadora.../service?wsdl"/></label>
        <label className="space-y-2 text-sm font-medium text-slate-700"><span>SOAPAction</span><input name="soap_action" className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Namespace</span><input name="namespace_operacao" className="ui-input"/></label>
        <label className="space-y-2 text-sm font-medium text-slate-700"><span>Operação envio</span><input name="operacao_envio" className="ui-input" placeholder="recepcaoLoteGuias"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Operação retorno/status</span><input name="operacao_status" className="ui-input"/></label>
        <label className="space-y-2 text-sm font-medium text-slate-700"><span>Cód. prestador na operadora</span><input name="codigo_prestador_operadora" className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Usuário</span><input name="usuario" className="ui-input" autoComplete="off"/></label>
        <label className="space-y-2 text-sm font-medium text-slate-700"><span>Referência do segredo</span><input name="segredo_referencia" className="ui-input" placeholder="OPERADORA_X_TISS_PASSWORD"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Referência do token</span><input name="token_referencia" className="ui-input" placeholder="OPERADORA_X_TISS_TOKEN"/></label>
        <label className="space-y-2 text-sm font-medium text-slate-700"><span>Referência certificado</span><input name="certificado_referencia" className="ui-input" placeholder="OPERADORA_X_CERT_PATH"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Senha certificado (ref.)</span><input name="certificado_senha_referencia" className="ui-input"/></label>
        <label className="space-y-2 text-sm font-medium text-slate-700"><span>Header customizado</span><input name="header_nome" className="ui-input"/></label><label className="space-y-2 text-sm font-medium text-slate-700"><span>Timeout (ms)</span><input name="timeout_ms" type="number" defaultValue={30000} min={1000} max={180000} className="ui-input"/></label>
        <label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" name="ativo" defaultChecked/> Ativo</label><label className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" name="validar_tls" defaultChecked/> Validar TLS</label>
        <label className="space-y-2 text-sm font-medium text-slate-700 md:col-span-2"><span>Observações</span><textarea name="observacoes" rows={3} className="ui-input"/></label>
      </div><button className="ui-button-primary mt-5">Salvar configuração</button></form>
      <section className="ui-card p-6"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-emerald-600"/><div><h2 className="font-semibold text-slate-900">Configurações existentes</h2><p className="text-sm text-slate-500">Homologação e produção ficam separadas por operadora.</p></div></div><div className="mt-4 space-y-3">{configs?.length?configs.map(c=>{const conv=one(c.convenio);return <div key={c.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{conv?.nome_fantasia??"Operadora"}</p><p className="text-xs text-slate-500">ANS {conv?.registro_ans??"—"} · {c.ambiente} · comunicação {c.versao_comunicacao}</p></div><span className={`rounded-full px-2 py-1 text-xs font-semibold ${c.ativo?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{c.ativo?"ativa":"inativa"}</span></div><p className="mt-2 text-sm text-slate-600">{c.transporte.toUpperCase()} · {c.tipo_autenticacao} · timeout {c.timeout_ms}ms</p><p className="mt-1 truncate text-xs text-slate-400">{c.endpoint_url||c.wsdl_url||"Sem endpoint configurado"}</p></div>}):<p className="text-sm text-slate-500">Nenhum webservice configurado.</p>}</div></section>
    </div>
  </SectionPage>;
}
