import Link from "next/link";
import type { Route } from "next";
import { ArrowLeft, FileCheck2, FileText, HeartOff, Printer, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { SectionPage } from "@/components/painel/section-page";
import { getAssistencialContext } from "@/modules/assistencial/context";
import { cancelarDocumentoClinico, salvarDocumentoClinico } from "@/modules/documentos-clinicos/actions";

const one=<T,>(v:T|T[]|null)=>Array.isArray(v)?v[0]??null:v;
const fmt=(v:string|null|undefined)=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(v)):"—";
type Doc={id:string;tipo:string;titulo:string;conteudo:string;status:string;cid10:string|null;dias_afastamento:number|null;assinado_em:string|null;created_at:string;motivo_cancelamento:string|null;profissional:{nome_completo:string|null}|{nome_completo:string|null}[]|null};
type Paciente={nome_completo:string|null;ra:string|null;numero_registro:number|null;cpf:string|null};
export const dynamic="force-dynamic"; export const revalidate=0;

export default async function DocumentosAtendimentoPage({params,searchParams}:{params:Promise<{atendimentoId:string}>;searchParams:Promise<{erro?:string;sucesso?:string}>}){
 const {atendimentoId}=await params; const sp=await searchParams; const {supabase,empresaId,unidadeId}=await getAssistencialContext();
 const [{data:at},{data:docs}]=await Promise.all([
  supabase.from("atendimentos").select("id,numero_atendimento,ambiente_assistencial,paciente:pacientes(nome_completo,ra,numero_registro,cpf)").eq("id",atendimentoId).eq("empresa_id",empresaId).eq("unidade_id",unidadeId).maybeSingle(),
  supabase.from("documentos_clinicos_atendimento").select("id,tipo,titulo,conteudo,status,cid10,dias_afastamento,assinado_em,created_at,motivo_cancelamento,profissional:profissionais(nome_completo)").eq("atendimento_id",atendimentoId).eq("empresa_id",empresaId).eq("unidade_id",unidadeId).order("created_at",{ascending:false}),
 ]); if(!at)notFound(); const p=one(at.paciente) as Paciente|null; const documentos=(docs??[]) as unknown as Doc[]; const ps=at.ambiente_assistencial==="pronto_atendimento";
 const opcoes=ps?[["atestado","Atestado médico"],["declaracao_comparecimento","Declaração de comparecimento"],["alta_pronto_atendimento","Alta do Pronto Atendimento"],["resumo_alta","Resumo de alta"],["orientacoes_alta","Orientações de alta"],["encaminhamento_svo","Encaminhamento ao SVO"],["declaracao_obito","Registro/documentação de óbito"],["relatorio_medico","Relatório médico"]]:[["atestado","Atestado médico"],["declaracao_comparecimento","Declaração de comparecimento"],["alta_ambulatorial","Alta ambulatorial"],["orientacoes_alta","Orientações/retorno"],["relatorio_medico","Relatório médico"]];
 return <SectionPage eyebrow={`Prontuário / ${ps?"Pronto Atendimento":"Ambulatório"}`} title="Documentos clínicos" description={`${p?.nome_completo??"Paciente"} · Atend. #${at.numero_atendimento??"—"} · RA ${p?.ra??"—"}`}>
  <div className="mb-4 flex flex-wrap gap-2"><Link href={`/prontuario/${atendimentoId}/clinico` as Route} className="ui-button-secondary"><ArrowLeft className="size-4"/>Atendimento médico</Link><Link href={`/prontuario/${atendimentoId}` as Route} className="ui-button-secondary">Resumo do prontuário</Link></div>
  {sp.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">Não foi possível concluir a operação documental.</div>:null}{sp.sucesso?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">Documento atualizado com sucesso.</div>:null}
  <section className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><form action={salvarDocumentoClinico} className="his-card p-6"><input type="hidden" name="atendimento_id" value={atendimentoId}/><div className="flex items-center gap-3"><FileCheck2 className="size-5 text-brand-700"/><div><h2 className="font-black">Emitir documento</h2><p className="text-sm text-slate-500">O tipo disponível respeita o ambiente assistencial do episódio.</p></div></div><div className="mt-5 grid gap-3"><select name="tipo" required className="ui-input" defaultValue=""><option value="">Selecione o tipo *</option>{opcoes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input name="titulo" required className="ui-input" placeholder="Título do documento"/><textarea name="conteudo" required rows={8} className="ui-input" placeholder="Conteúdo clínico/documental"/><div className="grid gap-3 sm:grid-cols-2"><input name="cid10" className="ui-input" placeholder="CID-10, quando pertinente"/><input name="dias_afastamento" type="number" min="0" className="ui-input" placeholder="Dias de afastamento"/><input name="data_inicio" type="date" className="ui-input"/><input name="data_fim" type="date" className="ui-input"/><input name="acompanhante_nome" className="ui-input sm:col-span-2" placeholder="Acompanhante, se aplicável"/></div>{ps?<div className="rounded-2xl border border-slate-200 p-4"><p className="mb-3 text-xs font-black uppercase text-slate-500">Campos específicos de SVO / óbito</p><div className="grid gap-3"><input name="destino_svo" className="ui-input" placeholder="Destino / Serviço de Verificação de Óbito"/><input name="causa_obito_imediata" className="ui-input" placeholder="Causa imediata registrada"/><input name="causa_obito_antecedente" className="ui-input" placeholder="Causa antecedente"/><input name="causa_obito_basica" className="ui-input" placeholder="Causa básica"/></div><p className="mt-2 text-xs text-slate-500">Este registro do HIS não substitui sistemas/formulários oficiais de declaração de óbito exigidos pela legislação e autoridade sanitária.</p></div>:null}<div className="flex justify-end gap-2"><button name="acao" value="salvar" className="ui-button-secondary">Salvar rascunho</button><button name="acao" value="assinar" className="ui-button-primary"><ShieldCheck className="size-4"/>Salvar e assinar</button></div></div></form>
  <div className="his-card overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-black">Documentos do episódio</h2><p className="text-sm text-slate-500">Histórico assinado, rascunhos e cancelamentos.</p></div><div className="divide-y divide-slate-100">{documentos.map(d=>{const prof=one(d.profissional);return <article key={d.id} className="p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><FileText className="size-4 text-brand-700"/><h3 className="font-black">{d.titulo}</h3><span className={`rounded-full px-2 py-1 text-xs font-bold ${d.status==="assinado"?"bg-emerald-50 text-emerald-700":d.status==="cancelado"?"bg-rose-50 text-rose-700":"bg-amber-50 text-amber-700"}`}>{d.status}</span></div><p className="mt-1 text-xs text-slate-500">{d.tipo.replaceAll("_"," ")} · {fmt(d.created_at)} · {prof?.nome_completo??"Profissional"}</p><p className="mt-3 whitespace-pre-wrap text-sm text-slate-700">{d.conteudo}</p>{d.motivo_cancelamento?<p className="mt-2 text-xs font-bold text-rose-700">Cancelado: {d.motivo_cancelamento}</p>:null}</div><div className="flex gap-2">{d.status==="assinado"?<Link href={`/prontuario/${atendimentoId}/documentos/${d.id}/imprimir` as Route} className="ui-button-secondary"><Printer className="size-4"/>Imprimir</Link>:null}</div></div>{d.status!=="cancelado"?<form action={cancelarDocumentoClinico} className="mt-3 flex flex-wrap gap-2 border-t border-slate-100 pt-3"><input type="hidden" name="atendimento_id" value={atendimentoId}/><input type="hidden" name="documento_id" value={d.id}/><input name="motivo_cancelamento" required className="ui-input flex-1" placeholder="Motivo para cancelar este documento"/><button className="ui-button-secondary"><HeartOff className="size-4"/>Cancelar</button></form>:null}</article>})}{!documentos.length?<div className="p-10 text-center text-sm text-slate-500">Nenhum documento emitido neste atendimento.</div>:null}</div></div></section>
 </SectionPage>;
}
