import { Clock3, Stethoscope, UserRoundCheck } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { assumirPaciente } from "@/modules/fila-medica/actions";

function one<T>(rel: T | T[] | null): T | null { return Array.isArray(rel) ? rel[0] ?? null : rel; }
function norm(v: string | null | undefined) { return (v ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }

export default async function FilaMedicaPage({ searchParams }: { searchParams: Promise<{ erro?: string }> }) {
  const { erro } = await searchParams;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  let profissional = user ? (await supabase.from("profissionais").select("id,nome_completo,especialidade").eq("usuario_id", user.id).eq("ativo", true).maybeSingle()).data : null;
  if (!profissional && user?.email) profissional = (await supabase.from("profissionais").select("id,nome_completo,especialidade").ilike("email", user.email).eq("ativo", true).limit(1).maybeSingle()).data;
  const { data: fila } = await supabase.from("encaminhamentos_assistenciais").select("id,atendimento_id,especialidade,prioridade,created_at,status,paciente:pacientes(nome_completo,ra,numero_registro),atendimento:atendimentos(numero_atendimento),triagem:atendimentos(triagens(classificacao_risco,queixa_principal,pressao_arterial,frequencia_cardiaca,saturacao_o2,temperatura_c))").eq("status", "aguardando_profissional").order("created_at", { ascending: true }).limit(200);
  const especialidadeProf = norm(profissional?.especialidade);
  const visiveis = (fila ?? []).filter((item) => { const esp = norm(item.especialidade); return especialidadeProf && (especialidadeProf.includes(esp) || esp.includes(especialidadeProf)); });

  return <SectionPage eyebrow="Assistencial / Médico" title="Minha fila médica" description="Pacientes encaminhados pela triagem para a especialidade vinculada ao profissional logado.">
    {erro ? <div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">Não foi possível assumir o paciente. Verifique vínculo profissional e especialidade.</div> : null}
    {!profissional ? <div className="ui-card p-6"><div className="flex items-center gap-3"><UserRoundCheck className="size-5 text-amber-600"/><div><h2 className="font-semibold text-slate-900">Usuário ainda não vinculado a um profissional</h2><p className="mt-1 text-sm text-slate-500">Vincule este usuário ao cadastro profissional para ativar a fila por especialidade.</p></div></div></div> : <div className="mb-5 rounded-2xl border border-brand-100 bg-brand-50/60 p-4"><div className="flex items-center gap-3"><Stethoscope className="size-5 text-brand-700"/><div><p className="font-semibold text-brand-950">{profissional.nome_completo}</p><p className="text-sm text-brand-700">Especialidade: {profissional.especialidade || "não informada"}</p></div></div></div>}
    <div className="space-y-3">{visiveis.length ? visiveis.map((item) => { const paciente=one(item.paciente); const atendimento=one(item.atendimento); const triagemRel=one(item.triagem); const triagem=triagemRel && "triagens" in triagemRel ? one((triagemRel as { triagens?: unknown }).triagens as never) as { classificacao_risco?: string; queixa_principal?: string; pressao_arterial?: string; frequencia_cardiaca?: number; saturacao_o2?: number; temperatura_c?: number } | null : null; return <div key={item.id} className="ui-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="font-semibold text-slate-900">{paciente?.nome_completo ?? "Paciente"}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.prioridade === "emergencia" ? "bg-rose-100 text-rose-700" : item.prioridade === "preferencial" ? "bg-amber-100 text-amber-700" : "bg-emerald-100 text-emerald-700"}`}>{item.prioridade ?? "normal"}</span></div><p className="mt-1 text-sm text-slate-500">Atendimento #{atendimento?.numero_atendimento ?? "—"} · Registro #{paciente?.numero_registro ?? "—"} · {paciente?.ra ?? "—"}</p><p className="mt-2 text-sm text-slate-700"><b>Especialidade:</b> {item.especialidade}</p>{triagem?.queixa_principal ? <p className="mt-1 text-sm text-slate-700"><b>Queixa:</b> {triagem.queixa_principal}</p> : null}<div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500">{triagem?.pressao_arterial ? <span>PA {triagem.pressao_arterial}</span> : null}{triagem?.frequencia_cardiaca ? <span>FC {triagem.frequencia_cardiaca}</span> : null}{triagem?.saturacao_o2 ? <span>SpO₂ {triagem.saturacao_o2}%</span> : null}{triagem?.temperatura_c ? <span>Temp. {triagem.temperatura_c}°C</span> : null}<span className="flex items-center gap-1"><Clock3 className="size-3"/>{new Date(item.created_at).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</span></div></div><form action={assumirPaciente}><input type="hidden" name="encaminhamento_id" value={item.id}/><button className="ui-button-primary">Chamar e assumir</button></form></div></div>; }) : <div className="ui-card p-8 text-center text-sm text-slate-500">Nenhum paciente aguardando para esta especialidade.</div>}</div>
  </SectionPage>;
}
