import { AlertTriangle, FileCode2, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { gerarXmlPreliminar, registrarGlosa, registrarProtocolo } from "@/modules/tiss/actions";

function one<T>(rel:T|T[]|null){return Array.isArray(rel)?rel[0]??null:rel;}

export default async function LotePage({params,searchParams}:{params:Promise<{loteId:string}>;searchParams:Promise<{erro?:string;xml?:string}>}){
  const {loteId}=await params; const qs=await searchParams; const supabase=await createClient();
  const [{data:lote},{data:links},{data:protocolos},{data:glosas},{data:xmls}] = await Promise.all([
    supabase.from("tiss_lotes").select("id,numero_lote,competencia,status,quantidade_guias,valor_total,xsd_validado,erros_validacao,protocolo_operadora,convenio:convenios(nome_fantasia,registro_ans),versao:tiss_versoes(organizacional,conteudo_estrutura,tuss,comunicacao_principal)").eq("id",loteId).maybeSingle(),
    supabase.from("tiss_lote_guias").select("guia:tiss_guias(id,numero_guia_prestador,tipo_guia,status,valor_total,paciente:pacientes(nome_completo,ra,numero_registro))").eq("lote_id",loteId),
    supabase.from("tiss_protocolos").select("id,numero_protocolo,data_protocolo,status,valor_apresentado,valor_processado,valor_liberado,valor_glosa,created_at").eq("lote_id",loteId).order("created_at",{ascending:false}),
    supabase.from("tiss_glosas").select("id,codigo_glosa,descricao_glosa,valor_glosado,status,guia:tiss_guias(numero_guia_prestador)").eq("lote_id",loteId).order("created_at",{ascending:false}),
    supabase.from("tiss_xmls").select("id,tipo_mensagem,versao_comunicacao,xsd_validado,erros_validacao,created_at").eq("lote_id",loteId).order("created_at",{ascending:false})
  ]);
  if(!lote) notFound(); const conv=one(lote.convenio); const versao=one(lote.versao);
  const gerar=gerarXmlPreliminar.bind(null,loteId); const protocolo=registrarProtocolo.bind(null,loteId); const glosa=registrarGlosa.bind(null,loteId);
  return <SectionPage eyebrow="Financeiro / TISS / Lote" title={`Lote ${lote.numero_lote}`} description={`${conv?.nome_fantasia??"Convênio"} · ANS ${conv?.registro_ans??"—"} · Competência ${lote.competencia??"—"}`}>
    {qs.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">Falha na operação: {qs.erro}.</div>:null}
    {qs.xml?<div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800"><b>XML preliminar criado somente para conferência interna.</b> Ele não é mensagem TISS válida para envio enquanto não houver validação contra o XSD oficial ANS.</div>:null}
    <div className="grid gap-4 md:grid-cols-4"><Info label="Status" value={String(lote.status).replaceAll("_"," ")}/><Info label="Guias" value={String(lote.quantidade_guias)}/><Info label="Valor" value={`R$ ${Number(lote.valor_total||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}`}/><Info label="XSD" value={lote.xsd_validado?"Validado":"Não validado"}/></div>
    <section className="ui-card mt-6 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-semibold text-slate-900">Versões TISS aplicadas</h2><p className="mt-1 text-sm text-slate-500">Conteúdo {versao?.conteudo_estrutura??"—"} · TUSS {versao?.tuss??"—"} · Comunicação {versao?.comunicacao_principal??"—"}</p></div><form action={gerar}><button className="ui-button-secondary"><FileCode2 className="mr-2 inline size-4"/>Gerar XML preliminar</button></form></div>{!lote.xsd_validado?<div className="mt-4 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><AlertTriangle className="size-5 shrink-0"/><p>Envio bloqueado até instalação e validação com o XSD oficial correspondente.</p></div>:<div className="mt-4 flex gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><ShieldCheck className="size-5 shrink-0"/><p>Lote validado contra XSD.</p></div>}</section>
    <section className="ui-card mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Guias do lote</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Guia</th><th className="px-4 py-3">Paciente</th><th className="px-4 py-3">Tipo</th><th className="px-4 py-3">Valor</th></tr></thead><tbody className="divide-y divide-slate-100">{links?.map((link,i)=>{const g=one(link.guia);const p=g?one(g.paciente):null;return g?<tr key={g.id}><td className="px-4 py-3 font-semibold">{g.numero_guia_prestador}</td><td className="px-4 py-3">{p?.nome_completo??"—"}<div className="text-xs text-slate-400">Registro #{p?.numero_registro??"—"} · {p?.ra??"—"}</div></td><td className="px-4 py-3">{g.tipo_guia}</td><td className="px-4 py-3">R$ {Number(g.valor_total||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}</td></tr>:null})}</tbody></table></div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><form action={protocolo} className="ui-card p-5"><h2 className="font-semibold text-slate-900">Registrar protocolo/retorno</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><input name="numero_protocolo" required placeholder="Número do protocolo" className="ui-input"/><input name="data_protocolo" type="date" className="ui-input"/><select name="status" defaultValue="recebido" className="ui-input"><option value="recebido">Recebido</option><option value="em_analise">Em análise</option><option value="processado">Processado</option><option value="rejeitado">Rejeitado</option><option value="pago_parcial">Pago parcial</option><option value="pago">Pago</option></select><input name="valor_apresentado" placeholder="Valor apresentado" className="ui-input"/><input name="valor_processado" placeholder="Valor processado" className="ui-input"/><input name="valor_liberado" placeholder="Valor liberado" className="ui-input"/><input name="valor_glosa" placeholder="Valor glosa" className="ui-input"/><textarea name="observacoes" rows={2} placeholder="Observações" className="ui-input md:col-span-2"/></div><button className="ui-button-primary mt-4">Salvar protocolo</button></form>
    <form action={glosa} className="ui-card p-5"><h2 className="font-semibold text-slate-900">Registrar glosa</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><select name="protocolo_id" defaultValue="" className="ui-input"><option value="">Sem protocolo específico</option>{protocolos?.map(p=><option key={p.id} value={p.id}>{p.numero_protocolo}</option>)}</select><select name="guia_id" defaultValue="" className="ui-input"><option value="">Selecione a guia</option>{links?.map(link=>{const g=one(link.guia);return g?<option key={g.id} value={g.id}>{g.numero_guia_prestador}</option>:null})}</select><input name="codigo_glosa" required placeholder="Código da glosa" className="ui-input"/><input name="valor_glosado" required placeholder="Valor glosado" className="ui-input"/><textarea name="descricao_glosa" rows={3} placeholder="Descrição/motivo" className="ui-input md:col-span-2"/></div><button className="ui-button-primary mt-4">Registrar glosa</button></form></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="ui-card p-5"><h2 className="font-semibold text-slate-900">Protocolos</h2><div className="mt-4 space-y-3">{protocolos?.length?protocolos.map(p=><div key={p.id} className="rounded-xl border border-slate-200 p-3"><div className="flex justify-between"><strong>{p.numero_protocolo}</strong><span className="text-xs capitalize text-slate-500">{String(p.status).replaceAll("_"," ")}</span></div><p className="mt-1 text-sm text-slate-500">Glosa R$ {Number(p.valor_glosa||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}</p></div>):<p className="text-sm text-slate-500">Nenhum protocolo.</p>}</div></section><section className="ui-card p-5"><h2 className="font-semibold text-slate-900">Glosas</h2><div className="mt-4 space-y-3">{glosas?.length?glosas.map(g=>{const guia=one(g.guia);return <div key={g.id} className="rounded-xl border border-rose-200 bg-rose-50 p-3"><div className="flex justify-between"><strong>{g.codigo_glosa}</strong><span className="text-sm font-semibold text-rose-700">R$ {Number(g.valor_glosado).toLocaleString("pt-BR",{minimumFractionDigits:2})}</span></div><p className="mt-1 text-sm text-slate-600">Guia {guia?.numero_guia_prestador??"—"} · {g.descricao_glosa??"Sem descrição"}</p></div>}):<p className="text-sm text-slate-500">Nenhuma glosa.</p>}</div></section></div>
    {xmls?.length?<section className="ui-card mt-6 p-5"><h2 className="font-semibold text-slate-900">Artefatos XML</h2><div className="mt-3 space-y-2">{xmls.map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{x.tipo_mensagem}</b> · comunicação {x.versao_comunicacao} · {x.xsd_validado?"XSD validado":"não validado"}</div>)}</div></section>:null}
  </SectionPage>;
}
function Info({label,value}:{label:string;value:string}){return <div className="ui-card p-4"><p className="text-xs font-medium uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 font-semibold capitalize text-slate-900">{value}</p></div>}
