import Link from "next/link";
import { BookOpenCheck, DatabaseZap, Filter, Plus, Search } from "lucide-react";
import { CadastrosWorkspaceNav, CadastroKpi } from "@/components/cadastros/cadastros-workspace-nav";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";

const nomesTipo: Record<string, string> = { tipo_profissional: "Tipo de profissional", especialidade: "Especialidade", cbo: "CBO", cid10: "CID-10", tuss: "TUSS", tipo_atendimento: "Tipo de atendimento", motivo_classificacao: "Motivo / classificação" };

export default async function CatalogosPage({ searchParams }: { searchParams: Promise<{ sucesso?: string;q?:string;tipo?:string }> }) {
  const { sucesso,q:rawQ,tipo:rawTipo } = await searchParams;const q=rawQ?.trim().slice(0,80)||"";const tipo=rawTipo?.trim()||"";
  const supabase = await createClient();
  let req=supabase.from("catalogos").select("id,tipo,codigo,descricao,vigencia_inicio,vigencia_fim",{count:"exact"}).eq("ativo", true);
  if(tipo)req=req.eq("tipo",tipo);if(q)req=req.or(`codigo.ilike.%${q.replace(/[,%()]/g," ")}%,descricao.ilike.%${q.replace(/[,%()]/g," ")}%`);
  const { data, error,count } = await req.order("tipo").order("descricao").limit(300);
  const {data:tiposRows}=await supabase.from("catalogos").select("tipo").eq("ativo",true).limit(5000);
  const tipos=[...new Set((tiposRows??[]).map(r=>r.tipo))].sort();const semVigencia=(data??[]).filter(i=>!i.vigencia_inicio&&!i.vigencia_fim).length;

  return <SectionPage eyebrow="Cadastros / Catálogos" title="Catálogos assistenciais" description="Domínios, códigos clínicos e referências centralizadas para todos os módulos do HIS." actions={<div className="flex flex-wrap gap-2"><Link href="/catalogos/ans" className="ui-button-primary"><DatabaseZap className="size-4"/>Consultar TUSS / ANS</Link><Link href="/catalogos/novo" className="ui-button-secondary"><Plus className="size-4"/>Novo item</Link></div>}>
    <CadastrosWorkspaceNav active="/catalogos"/>
    {sucesso === "cadastrado" ? <div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">Item de catálogo cadastrado com sucesso.</div> : null}
    <section className="mb-5 grid gap-3 sm:grid-cols-3"><CadastroKpi label="Itens encontrados" value={count??data?.length??0}/><CadastroKpi label="Tipos de catálogo" value={tipos.length}/><CadastroKpi label="Sem vigência" value={semVigencia} detail={semVigencia?"Revisar conforme fonte regulatória":"Todos os itens exibidos têm vigência"}/></section>
    <section className="ui-card overflow-hidden">
      <div className="space-y-4 border-b border-slate-100 p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><BookOpenCheck className="size-5" /></span><div><h2 className="font-semibold text-slate-900">Base de referências</h2><p className="text-sm text-slate-500">Filtre por domínio e localize pelo código ou descrição.</p></div></div><form className="grid gap-2 md:grid-cols-[1fr_260px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input name="q" defaultValue={q} className="ui-input pl-9" placeholder="Código ou descrição..."/></div><div className="relative"><Filter className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><select name="tipo" defaultValue={tipo} className="ui-input pl-9"><option value="">Todos os tipos</option>{tipos.map(t=><option key={t} value={t}>{nomesTipo[t]??t}</option>)}</select></div><button className="ui-button-secondary">Aplicar filtros</button></form></div>
      {error ? <p className="p-6 text-sm text-red-700">Não foi possível consultar os catálogos. Confirme migration e permissões.</p> : data?.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50/80 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Tipo</th><th className="px-5 py-3">Código</th><th className="px-5 py-3">Descrição</th><th className="px-5 py-3">Vigência</th><th className="px-5 py-3">Situação</th></tr></thead><tbody className="divide-y divide-slate-100">{data.map((item) => {const vigente=!item.vigencia_fim||new Date(`${item.vigencia_fim}T23:59:59`).getTime()>=Date.now();return <tr key={item.id} className="transition hover:bg-slate-50/70"><td className="px-5 py-4"><span className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-semibold text-brand-700">{nomesTipo[item.tipo] ?? item.tipo}</span></td><td className="px-5 py-4 font-mono text-xs font-bold text-slate-900">{item.codigo}</td><td className="px-5 py-4 text-slate-700">{item.descricao}</td><td className="px-5 py-4 text-slate-600">{item.vigencia_inicio || item.vigencia_fim ? `${item.vigencia_inicio || "…"} — ${item.vigencia_fim || "aberta"}` : "Sem vigência definida"}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${vigente?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{vigente?"Vigente":"Encerrado"}</span></td></tr>})}</tbody></table></div> : <div className="p-10 text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-slate-100 text-slate-400"><BookOpenCheck className="size-5" /></span><h3 className="mt-3 font-semibold text-slate-900">Nenhum item encontrado</h3><p className="mt-1 text-sm text-slate-500">Altere os filtros ou cadastre um novo item.</p></div>}
    </section>
  </SectionPage>;
}
