import Link from "next/link";
import type { Route } from "next";
import { CalendarDays, FileText, Pill, Stethoscope, FlaskConical, ScanLine } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { requireAnyPermission } from "@/lib/permissions/server";
import { assumirPaciente } from "@/modules/fila-medica/actions";

type Rel<T>=T|T[]|null;
type Paciente={nome_completo:string|null;ra:string|null;numero_registro:number|null;data_nascimento:string|null};
type Enc={id:string;status:string;especialidade:string|null;prioridade:string|null};
type Atendimento={id:string;numero_atendimento:string|number|null;status:string;data_abertura:string|null;especialidade_destino:string|null;paciente:Rel<Paciente>;encaminhamentos:Rel<Enc>};
function one<T>(v:Rel<T>){return Array.isArray(v)?v[0]??null:v}
function quando(v:string|null){return v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(v)):"—"}
export const dynamic="force-dynamic"; export const revalidate=0;
export default async function AmbulatorioPage(){const {supabase,empresaId,unidadeId}=await requireAnyPermission(["prontuario.visualizar","atendimentos.visualizar"]);if(!unidadeId)return null;
 const {data}=await supabase.from("atendimentos").select("id,numero_atendimento,status,data_abertura,especialidade_destino,paciente:pacientes(nome_completo,ra,numero_registro,data_nascimento),encaminhamentos:encaminhamentos_assistenciais(id,status,especialidade,prioridade)").eq("empresa_id",empresaId).eq("unidade_id",unidadeId).eq("ambiente_assistencial","ambulatorial").in("status",["aberto","em_espera","em_atendimento"]).order("data_abertura",{ascending:true}).limit(200);
 const itens=(data??[]) as Atendimento[];return <SectionPage eyebrow="Assistencial / Ambulatório" title="Ambulatório" description="Fila médica ambulatorial separada do Pronto Atendimento, com ações clínicas e documentais do episódio.">
 <section className="grid gap-3 sm:grid-cols-3"><Kpi label="Na fila" value={itens.filter(i=>i.status==="em_espera").length}/><Kpi label="Em atendimento" value={itens.filter(i=>i.status==="em_atendimento").length}/><Kpi label="Total aberto" value={itens.length}/></section>
 <section className="mt-5 space-y-3">{itens.map(a=>{const p=one(a.paciente);const enc=Array.isArray(a.encaminhamentos)?a.encaminhamentos.find(e=>["aguardando_profissional","em_atendimento"].includes(e.status))??a.encaminhamentos[0]??null:a.encaminhamentos;const clinico=`/prontuario/${a.id}/clinico` as Route,presc=`/prontuario/${a.id}/prescricao` as Route,docs=`/prontuario/${a.id}/documentos` as Route,lab=`/assistencial/laboratorio?atendimento=${a.id}` as Route,img=`/assistencial/imagem?atendimento=${a.id}` as Route;return <article key={a.id} className="ui-card p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black text-slate-950">{p?.nome_completo??"Paciente"}</h2><span className="rounded-full bg-sky-50 px-2.5 py-1 text-xs font-bold text-sky-700">Ambulatorial</span></div><p className="mt-1 text-sm text-slate-500">Atend. #{a.numero_atendimento??"—"} · RA {p?.ra??"—"} · Registro #{p?.numero_registro??"—"}</p><p className="mt-2 text-sm"><b>Especialidade:</b> {a.especialidade_destino??enc?.especialidade??"—"}</p><p className="mt-1 text-xs text-slate-400"><CalendarDays className="mr-1 inline size-3"/>{quando(a.data_abertura)}</p></div><div className="flex flex-wrap gap-2">{enc?.status==="aguardando_profissional"?<form action={assumirPaciente}><input type="hidden" name="encaminhamento_id" value={enc.id}/><button className="ui-button-primary"><Stethoscope className="size-4"/>Chamar e assumir</button></form>:<Link href={clinico} className="ui-button-primary"><Stethoscope className="size-4"/>Atendimento</Link>}<Link href={presc} className="ui-button-secondary"><Pill className="size-4"/>Prescrição</Link><Link href={lab} className="ui-button-secondary"><FlaskConical className="size-4"/>Exames</Link><Link href={img} className="ui-button-secondary"><ScanLine className="size-4"/>Imagem</Link><Link href={docs} className="ui-button-secondary"><FileText className="size-4"/>Documentos</Link></div></div></article>})}{!itens.length?<div className="ui-card p-10 text-center text-sm text-slate-500">Nenhum atendimento ambulatorial aberto.</div>:null}</section></SectionPage>}
function Kpi({label,value}:{label:string;value:number}){return <div className="his-kpi"><p className="text-xs font-black uppercase text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p></div>}
