import Link from "next/link";
import { notFound } from "next/navigation";
import { BadgeCheck, BriefcaseBusiness, CalendarDays, IdCard, Mail, MapPin, Phone, Stethoscope } from "lucide-react";
import { CadastrosWorkspaceNav, CadastroKpi } from "@/components/cadastros/cadastros-workspace-nav";
import { ProfessionalTissProfileForm } from "@/components/cadastros/professional-tiss-profile-form";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { criarUrlFotoAssinada } from "@/modules/cadastros/fotos";
function dataBr(v:string|null|undefined){return v?new Date(`${v}T12:00:00`).toLocaleDateString("pt-BR"):"—";}
export default async function Profissional360Page({params}:{params:Promise<{profissionalId:string}>}){
 const {profissionalId}=await params;const supabase=await createClient();
 const [{data:p},{data:emails},{data:telefones},{data:enderecos},{data:contratos},{count:atendimentos},{data:cboRows},{data:councilRows}]=await Promise.all([
  supabase.from("profissionais").select("id,nome_completo,cpf,rg,data_nascimento,conselho,codigo_conselho_ans,numero_conselho,uf_conselho,especialidade,cbo,habilitado_tiss,telefone,email,foto_path,ativo,tipo_profissional_catalogo_id").eq("id",profissionalId).maybeSingle(),
  supabase.from("profissional_emails").select("id,email,tipo,principal").eq("profissional_id",profissionalId).order("principal",{ascending:false}),
  supabase.from("profissional_telefones").select("id,telefone,tipo,principal").eq("profissional_id",profissionalId).order("principal",{ascending:false}),
  supabase.from("profissional_enderecos").select("id,tipo,endereco,numero,bairro,cidade,estado,cep,principal").eq("profissional_id",profissionalId).order("principal",{ascending:false}),
  supabase.from("profissional_contratos").select("id,tipo_contrato,matricula,data_inicio,data_fim,carga_horaria_semanal,tipo_remuneracao,valor_remuneracao,observacoes,ativo").eq("profissional_id",profissionalId).order("data_inicio",{ascending:false}),
  supabase.from("atendimentos").select("id",{count:"exact",head:true}).eq("profissional_id",profissionalId),
  supabase.from("ans_fhir_dominios_ativos").select("codigo,display,versao").eq("tabela",24).neq("codigo","999999").order("display"),
  supabase.from("ans_fhir_dominios_ativos").select("codigo,display,versao").eq("tabela",26).order("ordem"),
 ]);
 if(!p)notFound();
 const foto=await criarUrlFotoAssinada(supabase,p.foto_path);const contratoAtual=contratos?.find(c=>c.ativo)??contratos?.[0];const endereco=enderecos?.[0];const tissReady=p.habilitado_tiss===true;
 const cboOptions=(cboRows??[]).map(item=>({code:item.codigo,label:item.display}));const councilOptions=(councilRows??[]).map(item=>({code:item.codigo,label:item.display}));const sourceVersion=cboRows?.[0]?.versao??councilRows?.[0]?.versao??"não informada";
 return <SectionPage eyebrow="Cadastros / Profissionais / Ficha 360°" title={p.nome_completo} description="Habilitação, vínculos, contatos e contexto assistencial do profissional.">
  <CadastrosWorkspaceNav active="/profissionais"/>
  <section className="ui-card mb-5 p-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-4"><span className="grid size-16 shrink-0 place-items-center overflow-hidden rounded-2xl bg-brand-50 text-xl font-black text-brand-700" style={foto?{backgroundImage:`url(${foto})`,backgroundPosition:"center",backgroundSize:"cover"}:undefined}>{foto?null:p.nome_completo.slice(0,1).toUpperCase()}</span><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black text-slate-950">{p.nome_completo}</h2>{tissReady?<span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700"><BadgeCheck className="mr-1 inline size-3.5"/>Pronto TISS</span>:<span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">Não usa TISS</span>}</div><p className="mt-1 text-sm text-slate-500">{p.especialidade||"Ocupação não vinculada ao TISS"}{p.cbo?` · CBO ${p.cbo}`:""}</p></div></div><div className="flex flex-wrap gap-2"><Link href="/cadastros/tiss" className="ui-button-secondary">Prontidão TISS</Link><Link href={`/agenda?profissional=${p.id}`} className="ui-button-secondary"><CalendarDays className="size-4"/>Agenda</Link><Link href={`/fila-medica?profissional=${p.id}`} className="ui-button-primary"><Stethoscope className="size-4"/>Fila assistencial</Link></div></div></section>
  <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><CadastroKpi label="Atendimentos" value={atendimentos??0}/><CadastroKpi label="Contratos" value={contratos?.length??0}/><CadastroKpi label="Vínculo atual" value={contratoAtual?.tipo_contrato||"—"}/><CadastroKpi label="TISS" value={tissReady?"Pronto":"Não habilitado"} detail={tissReady?"Domínios TUSS 24/26 validados":"Sem obrigação regulatória neste cadastro"}/></section>
  <div className="grid gap-5 xl:grid-cols-3"><section className="ui-card p-5 xl:col-span-2"><h2 className="flex items-center gap-2 font-bold"><IdCard className="size-5 text-brand-700"/>Habilitação</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Info label="CPF" value={p.cpf||"—"}/><Info label="Conselho" value={[p.conselho,p.numero_conselho,p.uf_conselho].filter(Boolean).join(" ")||"—"}/><Info label="Especialidade / ocupação" value={p.especialidade||"—"}/><Info label="CBO" value={p.cbo||"—"}/></div><ProfessionalTissProfileForm profissionalId={p.id} numeroConselho={p.numero_conselho} ufConselho={p.uf_conselho} cbo={p.cbo} codigoConselhoAns={p.codigo_conselho_ans} habilitadoTiss={p.habilitado_tiss} cboOptions={cboOptions} councilOptions={councilOptions} sourceVersion={sourceVersion}/></section><section className="ui-card p-5"><h2 className="flex items-center gap-2 font-bold"><BriefcaseBusiness className="size-5 text-brand-700"/>Vínculo atual</h2><div className="mt-4 grid gap-3"><Info label="Contrato" value={contratoAtual?.tipo_contrato||"—"}/><Info label="Matrícula" value={contratoAtual?.matricula||"—"}/><Info label="Vigência" value={contratoAtual?`${dataBr(contratoAtual.data_inicio)} → ${contratoAtual.data_fim?dataBr(contratoAtual.data_fim):"aberta"}`:"—"}/><Info label="Carga horária" value={contratoAtual?.carga_horaria_semanal?`${contratoAtual.carga_horaria_semanal}h/semana`:"—"}/></div></section></div>
  <section className="ui-card mt-5 p-5"><h2 className="font-bold">Contatos</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><Contact icon={Mail} value={emails?.[0]?.email||p.email||"—"}/><Contact icon={Phone} value={telefones?.[0]?.telefone||p.telefone||"—"}/><Contact icon={MapPin} value={endereco?`${endereco.endereco}, ${endereco.numero||"s/n"} · ${endereco.cidade}/${endereco.estado}`:"—"}/></div></section>
  <section className="ui-card mt-5 overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Histórico de vínculos</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Tipo</th><th className="px-4 py-3">Matrícula</th><th className="px-4 py-3">Início</th><th className="px-4 py-3">Fim</th><th className="px-4 py-3">Remuneração</th></tr></thead><tbody className="divide-y divide-slate-100">{contratos?.length?contratos.map(c=><tr key={c.id}><td className="px-4 py-3 font-medium capitalize">{c.tipo_contrato}</td><td className="px-4 py-3">{c.matricula||"—"}</td><td className="px-4 py-3">{dataBr(c.data_inicio)}</td><td className="px-4 py-3">{c.data_fim?dataBr(c.data_fim):"Aberto"}</td><td className="px-4 py-3">{c.tipo_remuneracao||"—"}</td></tr>):<tr><td colSpan={5} className="p-8 text-center text-slate-500">Nenhum vínculo cadastrado.</td></tr>}</tbody></table></div></section>
 </SectionPage>;
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 font-medium text-slate-700">{value}</p></div>}
function Contact({icon:Icon,value}:{icon:typeof Mail;value:string}){return <div className="flex items-start gap-3 rounded-xl bg-slate-50 p-3"><Icon className="mt-0.5 size-4 text-slate-400"/><p className="text-sm font-medium text-slate-700">{value}</p></div>}
