export type KnowledgeBaseLink = {
  label: string;
  href: string;
};

export type KnowledgeBaseArticle = {
  slug: string;
  title: string;
  category: string;
  audience: string[];
  summary: string;
  steps: string[];
  warnings?: string[];
  links: KnowledgeBaseLink[];
  keywords: string[];
  sourceDocs: string[];
};

export const knowledgeBaseArticles: KnowledgeBaseArticle[] = [
  {
    slug: "visao-geral-fluxo-his",
    title: "Entenda o fluxo geral do MedSync HIS",
    category: "Primeiros passos",
    audience: ["Todos os usuários"],
    summary: "Como o mesmo atendimento/RA percorre Recepção, Assistência, Auditoria, Faturamento e Financeiro sem criar episódios paralelos.",
    steps: [
      "Identifique o paciente e localize um atendimento existente antes de criar um novo episódio.",
      "Abra a jornada pela Agenda ou Recepção/Admissão, conforme a origem do atendimento.",
      "Continue pelo mesmo atendimento para Triagem, Autorização, Fila Médica, Prontuário e setores assistenciais.",
      "Após a alta, acompanhe o mesmo ciclo em Auditoria, Contas Médicas, Faturamento/TISS e Financeiro.",
      "Quando um módulo oferecer link para a próxima etapa, confirme que o paciente e o número do atendimento permanecem os mesmos.",
    ],
    warnings: ["Não crie um segundo atendimento apenas para trocar de setor dentro da mesma jornada assistencial."],
    links: [{ label: "Visão geral", href: "/painel" }, { label: "Atendimentos", href: "/atendimentos" }],
    keywords: ["fluxo", "ra", "atendimento", "jornada", "episódio", "primeiros passos"],
    sourceDocs: ["docs/MANUAL.md"],
  },
  {
    slug: "recepcao-senhas-admissao",
    title: "Recepção, senhas e abertura do atendimento",
    category: "Atendimento",
    audience: ["Recepção", "Admissão"],
    summary: "Passo a passo para chamar a senha, confirmar o paciente e abrir o atendimento sem perder a jornada em andamento.",
    steps: [
      "Chame a senha na Recepção e confirme a identificação do paciente.",
      "Pesquise o paciente antes de cadastrar um novo registro.",
      "Confirme dados cadastrais e selecione Particular ou Convênio.",
      "Para Convênio, informe plano/carteirinha e cumpra as verificações de identificação configuradas.",
      "Conclua a admissão; a navegação para Autorização ou Triagem só ocorre depois que o atendimento/RA for criado com sucesso.",
    ],
    warnings: ["Erros de cobertura ou identificação devem ser corrigidos no mesmo formulário; não abra outro atendimento para contornar a validação."],
    links: [{ label: "Recepção e senhas", href: "/senhas" }, { label: "Atendimentos", href: "/atendimentos" }],
    keywords: ["recepção", "senha", "admissão", "cpf", "carteirinha", "convênio"],
    sourceDocs: ["docs/MANUAL.md", "docs/MANUAL_CADASTRO_PACIENTE_ADMISSAO_TISS.md"],
  },
  {
    slug: "cadastro-paciente",
    title: "Cadastrar e localizar pacientes com segurança",
    category: "Atendimento",
    audience: ["Recepção", "Cadastro", "Admissão"],
    summary: "Como pesquisar antes de cadastrar, confirmar documentos e evitar duplicidade de paciente.",
    steps: [
      "Pesquise por nome, CPF, RA ou número de registro antes de iniciar um novo cadastro.",
      "Confira nome completo, nascimento, documentos e contatos do registro encontrado.",
      "Somente crie um novo paciente quando a pesquisa não localizar o cadastro correto.",
      "Complete os campos obrigatórios e revise os dados antes de continuar a admissão.",
      "Ao retornar para a jornada assistencial, mantenha a mesma senha/agendamento que originou o cadastro quando o sistema tiver preservado esse contexto.",
    ],
    warnings: ["Duplicidade de paciente fragmenta o prontuário longitudinal e pode gerar divergências de faturamento."],
    links: [{ label: "Pacientes", href: "/pacientes" }, { label: "Nova admissão", href: "/atendimentos/novo" }],
    keywords: ["paciente", "cadastro", "cpf", "ra", "duplicidade", "registro"],
    sourceDocs: ["docs/MANUAL.md", "docs/MANUAL_CADASTRO_PACIENTE_ADMISSAO_TISS.md"],
  },
  {
    slug: "autorizacoes-guias",
    title: "Guias, autorizações e identificação do beneficiário",
    category: "Atendimento",
    audience: ["Central de Guias", "Recepção", "Faturamento"],
    summary: "Como registrar guia, senha, protocolo e autorização mantendo o vínculo com o mesmo atendimento.",
    steps: [
      "Abra o atendimento correto na Central de Guias/Autorizações.",
      "Informe os dados da guia, senha, protocolo, validade e procedimentos autorizados quando aplicáveis.",
      "Execute biometria/token somente quando a regra do convênio exigir e reutilize identificação válida conforme a configuração institucional.",
      "Salve a autorização; sucesso e erro permanecem na própria tela.",
      "Quando a autorização liberar uma próxima etapa assistencial, use a navegação oferecida pelo sistema para continuar a mesma jornada.",
    ],
    warnings: ["Não edite diretamente o banco para forçar liberação de guia ou identificação."],
    links: [{ label: "Central de Guias", href: "/central-guias" }, { label: "Autorizações", href: "/autorizacoes" }],
    keywords: ["guia", "autorização", "senha", "protocolo", "biometria", "token"],
    sourceDocs: ["docs/MANUAL.md"],
  },
  {
    slug: "triagem-fila-medica",
    title: "Triagem e entrada na Fila Médica",
    category: "Assistencial",
    audience: ["Enfermagem", "Triagem", "Corpo clínico"],
    summary: "Como registrar a Triagem e encaminhar o paciente sem perder dados já coletados.",
    steps: [
      "Chame ou rechame o paciente pela tela de Triagem.",
      "Registre queixa, classificação, sinais vitais e especialidade de destino conforme os dados disponíveis.",
      "Salve a Triagem; erros permanecem inline e não apagam os campos preenchidos.",
      "Se houver guia pendente, o atendimento aguarda a Central de Guias sem exigir nova Triagem.",
      "Na Fila Médica, o profissional assume o paciente e só então o sistema abre o prontuário do atendimento correspondente.",
    ],
    warnings: ["Concluir a Triagem encerra apenas essa etapa; não encerra o atendimento hospitalar."],
    links: [{ label: "Triagem", href: "/triagem" }, { label: "Fila Médica", href: "/fila-medica" }],
    keywords: ["triagem", "risco", "sinais vitais", "fila médica", "encaminhamento"],
    sourceDocs: ["docs/MANUAL.md"],
  },
  {
    slug: "prontuario-prescricao",
    title: "Prontuário longitudinal e prescrição",
    category: "Assistencial",
    audience: ["Médicos", "Equipe assistencial"],
    summary: "Como trabalhar no mesmo episódio, consultar contexto assistencial e registrar prescrição sem criar prontuários paralelos.",
    steps: [
      "Abra o prontuário pelo atendimento/RA correto.",
      "Revise o contexto do episódio, incluindo Triagem, cobertura, autorização e fatos assistenciais disponíveis.",
      "Registre anamnese/evolução, avaliações e demais documentos na subárea correspondente.",
      "Inclua itens da prescrição no rascunho; salvamentos comuns devem ocorrer em segundo plano.",
      "Assine/feche a prescrição conforme o fluxo institucional antes da liberação aos setores executores.",
    ],
    warnings: ["Não selecione outro paciente durante a execução de uma ação iniciada a partir do prontuário atual."],
    links: [{ label: "Prontuário", href: "/prontuario" }, { label: "Prescrição", href: "/prescricao" }],
    keywords: ["prontuário", "prescrição", "anamnese", "evolução", "avaliação", "medicação"],
    sourceDocs: ["docs/MANUAL.md"],
  },
  {
    slug: "enfermagem-administracao",
    title: "Enfermagem: evolução e administração à beira-leito",
    category: "Assistencial",
    audience: ["Enfermagem"],
    summary: "Como evoluir o paciente e checar medicamentos preservando identificação, lote, dispensação e dupla checagem.",
    steps: [
      "Abra a Enfermagem pelo setor ou pelo atalho do atendimento para manter o paciente filtrado.",
      "Registre a evolução e aguarde a confirmação inline do salvamento.",
      "Na administração, confirme paciente, prescrição, dose, via e dispensação/lote quando disponíveis.",
      "Realize a dupla checagem e informe o segundo profissional quando a regra exigir.",
      "Registre recusa, omissão ou justificativa quando o medicamento não for administrado conforme previsto.",
    ],
    warnings: ["A administração à beira-leito é domínio da Enfermagem e não deve ser duplicada na Farmácia."],
    links: [{ label: "Central Assistencial", href: "/assistencial" }, { label: "Enfermagem", href: "/assistencial/enfermagem" }],
    keywords: ["enfermagem", "evolução", "administração", "beira-leito", "lote", "dupla checagem"],
    sourceDocs: ["docs/MANUAL.md"],
  },
  {
    slug: "farmacia-fefo",
    title: "Farmácia: validar, dispensar e devolver medicamentos",
    category: "Assistencial",
    audience: ["Farmácia"],
    summary: "Fluxo de conciliação, validação farmacêutica, dispensação FEFO e devolução integrado à prescrição.",
    steps: [
      "Abra a tela de medicamentos e localize a prescrição/atendimento correto.",
      "Registre a conciliação medicamentosa quando aplicável.",
      "Faça a validação farmacêutica antes da dispensação quando o fluxo exigir.",
      "Dispense o item principal ou seus componentes preservando FEFO, lote e saldo.",
      "Registre devoluções pela operação própria para manter a rastreabilidade do estoque e do atendimento.",
    ],
    warnings: ["Não substitua os RPCs de dispensação/devolução por atualização manual de saldo."],
    links: [{ label: "Medicamentos / Farmácia", href: "/assistencial/medicamentos" }],
    keywords: ["farmácia", "fefo", "dispensação", "validação", "conciliação", "devolução"],
    sourceDocs: ["docs/MANUAL.md"],
  },
  {
    slug: "laboratorio-lis",
    title: "Laboratório/LIS: da amostra ao laudo",
    category: "Apoio diagnóstico",
    audience: ["Laboratório", "Patologia clínica"],
    summary: "Fluxo de bancada e laudo com accession, cadeia de custódia, resultados, criticidade e liberação.",
    steps: [
      "Prepare a amostra a partir da solicitação vinculada ao atendimento.",
      "Atualize coleta/recebimento/rejeição e demais eventos da cadeia de custódia pela bancada.",
      "Encaminhe a amostra ao setor/bancada de processamento.",
      "Registre os resultados dos analitos e execute a validação técnica.",
      "Para resultado crítico, registre comunicação, meio e read-back quando aplicável.",
      "Inicie o laudo; após a criação confirmada, o sistema abre o editor. Rascunho, validação, crítico, liberação e retificação permanecem no editor sem reload.",
    ],
    warnings: ["Não crie amostra ou laudo desvinculado do atendimento apenas para testar o fluxo."],
    links: [{ label: "Laboratório", href: "/assistencial/laboratorio" }, { label: "Laudos LIS", href: "/assistencial/laboratorio/laudos" }],
    keywords: ["laboratório", "lis", "amostra", "accession", "analito", "resultado", "laudo"],
    sourceDocs: ["docs/MANUAL.md", "docs/MANUAL_LABORATORIO_LIS.md"],
  },
  {
    slug: "imagem-ris-pacs",
    title: "Diagnóstico por Imagem/RIS e PACS",
    category: "Apoio diagnóstico",
    audience: ["Radiologia", "Diagnóstico por Imagem"],
    summary: "Como agendar, executar, registrar contraste/dose e trabalhar com laudos no mesmo atendimento.",
    steps: [
      "Localize a solicitação de imagem pendente e confirme o atendimento/paciente.",
      "Agende data/hora, protocolo, sala e equipamento quando exigidos.",
      "Atualize confirmação/chegada/falta/cancelamento diretamente na agenda.",
      "Inicie a execução e, ao finalizar, registre identificadores DICOM/PACS e intercorrências disponíveis.",
      "Registre contraste com as verificações de segurança e dose de radiação quando aplicáveis à modalidade.",
      "Crie e libere o laudo mantendo o vínculo com a execução e o atendimento.",
    ],
    warnings: ["PACS/visualizador e integrações DICOM reais dependem da infraestrutura homologada da instituição."],
    links: [{ label: "Diagnóstico por Imagem", href: "/assistencial/imagem" }],
    keywords: ["imagem", "ris", "pacs", "dicom", "contraste", "dose", "laudo"],
    sourceDocs: ["docs/MANUAL.md", "docs/MANUAL_IMAGEM_RIS_PACS.md"],
  },
  {
    slug: "internacao-nir-leitos",
    title: "Internação, NIR e gestão de leitos",
    category: "Assistencial",
    audience: ["Internação", "NIR", "Enfermagem"],
    summary: "Diferença entre admissão, mapa físico de leitos, regulação NIR, censo e alta.",
    steps: [
      "Use o Painel da Internação para acompanhar a jornada do paciente internado.",
      "Use o Mapa de Leitos para a situação operacional/física dos leitos.",
      "Use a NIR para reserva, alocação e regulação do leito dentro das regras institucionais.",
      "Registre movimentações e transferências pelo fluxo próprio para preservar histórico e censo.",
      "Conclua a alta pela etapa correspondente, mantendo o handoff para Auditoria/Contas Médicas quando aplicável.",
    ],
    warnings: ["Não altere ocupação de leito por DML direto para corrigir divergência operacional."],
    links: [{ label: "Internação", href: "/internacao" }, { label: "Mapa de leitos", href: "/internacao/leitos" }, { label: "NIR", href: "/internacao/nir" }],
    keywords: ["internação", "nir", "leito", "censo", "transferência", "alta"],
    sourceDocs: ["docs/MANUAL.md", "docs/TRANSFERENCIAS_INTERUNIDADES.md"],
  },
  {
    slug: "auditoria-contas-medicas",
    title: "Auditoria pós-alta e Contas Médicas",
    category: "Receita",
    audience: ["Auditoria", "Contas Médicas", "Faturamento"],
    summary: "Como interpretar pendências atuais, histórico resolvido e revalidar antes do handoff para Contas Médicas.",
    steps: [
      "Abra a conta/atendimento na fila da Auditoria após a alta.",
      "Diferencie pendências atualmente abertas de histórico já resolvido.",
      "Corrija a origem da divergência no módulo responsável; a Central de Pendências não deve reescrever o fato.",
      "Use a revalidação da Auditoria para recalcular as críticas atuais antes da liberação.",
      "Somente após a liberação confirmada a conta segue para Contas Médicas e etapas de faturamento.",
    ],
    warnings: ["Não altere liberações formais diretamente no banco para remover uma pendência visual."],
    links: [{ label: "Auditoria", href: "/auditoria" }, { label: "Contas Médicas", href: "/contas-medicas" }],
    keywords: ["auditoria", "contas médicas", "pendência", "histórico", "revalidar", "liberação"],
    sourceDocs: ["docs/MANUAL.md"],
  },
  {
    slug: "faturamento-tiss",
    title: "Faturamento e TISS: da conta ao lote",
    category: "Receita",
    audience: ["Faturamento", "Contas Médicas"],
    summary: "Sequência correta entre conta validada, guia, lote, XML, protocolo e retorno.",
    steps: [
      "Trabalhe somente com a conta que passou pelas etapas de Auditoria/Contas Médicas exigidas pelo fluxo.",
      "Valide itens, contrato, tabela, autorização e valores antes de gerar a guia.",
      "Gere/prepare a Guia TISS e corrija as críticas impeditivas.",
      "Inclua a guia em lote e gere o XML conforme a versão aplicável.",
      "Valide o XML contra os schemas/regras aplicáveis antes de envio.",
      "Registre protocolo e retorno da operadora para manter a rastreabilidade do ciclo.",
    ],
    warnings: ["Não considere um XML tecnicamente gerado como TISS homologado sem validação e homologação do canal aplicável."],
    links: [{ label: "Pré-faturamento", href: "/faturamento" }, { label: "Lotes TISS", href: "/faturamento/lotes" }],
    keywords: ["faturamento", "tiss", "guia", "lote", "xml", "xsd", "protocolo"],
    sourceDocs: ["docs/MANUAL.md"],
  },
  {
    slug: "glosas-recursos",
    title: "Glosas e recursos",
    category: "Receita",
    audience: ["Faturamento", "Recurso de Glosas", "Financeiro"],
    summary: "Como manter motivo, item, valor, justificativa, protocolo, prazo e decisão vinculados à conta original.",
    steps: [
      "Localize a glosa pela conta/guia correta.",
      "Confira código/motivo, item e valor glosado antes de preparar o recurso.",
      "Registre justificativa e valor recursado de acordo com a ocorrência real.",
      "Acompanhe protocolo, prazo e resultado sem substituir o histórico da glosa original.",
      "Reflita deferimento/indeferimento no ciclo financeiro somente pelo fluxo correspondente.",
    ],
    warnings: ["Catálogos de motivos são referência; a ocorrência real continua vinculada à conta/guia/item."],
    links: [{ label: "Glosas e recursos", href: "/faturamento/glosas" }],
    keywords: ["glosa", "recurso", "justificativa", "protocolo", "prazo", "deferido"],
    sourceDocs: ["docs/MANUAL.md"],
  },
  {
    slug: "financeiro-nfse",
    title: "Financeiro, recebimentos e NFS-e",
    category: "Receita",
    audience: ["Financeiro", "Faturamento"],
    summary: "Como acompanhar previsão, recebimento, conciliação e notas fiscais sem antecipar integrações não homologadas.",
    steps: [
      "Acompanhe os recebíveis e suas previsões de pagamento no Financeiro.",
      "Registre baixas/conciliações somente quando houver evidência da movimentação correspondente.",
      "Confira bruto, glosas, retenções e líquido antes de concluir a conciliação.",
      "Em NFS-e, utilize emissão manual ou adapter municipal efetivamente configurado/homologado.",
      "Mantenha o vínculo entre nota, conta/recebível e unidade para evitar duplicidade de informação.",
    ],
    warnings: ["Não habilite emissão automática de NFS-e sem credenciais e adapter reais do município/provedor."],
    links: [{ label: "Financeiro", href: "/financeiro" }, { label: "Notas fiscais", href: "/financeiro/notas-fiscais" }],
    keywords: ["financeiro", "recebimento", "conciliação", "nfse", "nota fiscal", "retenção"],
    sourceDocs: ["docs/MANUAL.md"],
  },
  {
    slug: "compras-estoque",
    title: "Compras, recebimento e estoque",
    category: "Gestão",
    audience: ["Compras", "Almoxarifado", "Farmácia"],
    summary: "Fluxo entre solicitação, cotação, aprovação, pedido, recebimento, lote e saldo.",
    steps: [
      "Inicie pela solicitação/requisição do setor responsável.",
      "Realize cotação e aprovações conforme as alçadas configuradas.",
      "Emita o pedido e registre o recebimento físico pela operação própria.",
      "No recebimento, preserve lote, validade e demais dados de rastreabilidade disponíveis.",
      "Use inventário, reposição e transferências para ajustar o fluxo físico sem editar saldo diretamente.",
    ],
    warnings: ["Movimentação física não substitui o catálogo mestre usado por assistência e faturamento."],
    links: [{ label: "Compras", href: "/compras" }, { label: "Estoque", href: "/almoxarifado" }],
    keywords: ["compras", "cotação", "pedido", "recebimento", "estoque", "lote", "inventário"],
    sourceDocs: ["docs/MANUAL.md"],
  },
  {
    slug: "usuarios-permissoes",
    title: "Usuários, perfis e permissões",
    category: "Configuração",
    audience: ["Administrador", "TI"],
    summary: "Como administrar acesso respeitando RBAC, empresa/unidade e princípio do menor privilégio.",
    steps: [
      "Cadastre ou localize o usuário na área de acessos.",
      "Vincule os perfis necessários à função real do usuário.",
      "Revise permissões e escopo de empresa/unidade antes de liberar o acesso.",
      "Evite conceder privilégios administrativos apenas para resolver erro operacional de um módulo.",
      "Teste o acesso com o perfil correspondente e registre ajustes pela configuração oficial.",
    ],
    warnings: ["RLS/RBAC não devem ser contornados por grants manuais ou uso de credenciais privilegiadas no frontend."],
    links: [{ label: "Usuários e acessos", href: "/configuracoes/acessos" }],
    keywords: ["usuário", "perfil", "permissão", "rbac", "rls", "acesso", "unidade"],
    sourceDocs: ["docs/MATRIZ_PERMISSOES.md", "docs/SEGURANCA.md"],
  },
];

export const knowledgeBaseCategories = ["Todas", ...Array.from(new Set(knowledgeBaseArticles.map((article) => article.category)))];
