import type { KnowledgeBaseArticle } from "@/modules/knowledge-base/articles";

export const assistencialOperationalKnowledgeBaseArticles: KnowledgeBaseArticle[] = [
  {
    slug: "urgencia-emergencia-reavaliacao",
    title: "Urgência e Emergência: risco, ABCDE e reavaliação",
    category: "Assistencial",
    audience: ["Urgência", "Enfermagem", "Corpo clínico"],
    summary: "Como manter classificação de risco, ABCDE, procedimentos imediatos, reavaliação e destino no mesmo episódio do paciente.",
    steps: [
      "Selecione o atendimento já aberto para preservar RA, prontuário, prescrição, exames e eventual internação.",
      "Registre origem, mecanismo, classificação de risco, sala, protocolo e impressão clínica inicial.",
      "Complete ABCDE e procedimentos imediatos conforme o atendimento realizado.",
      "Defina a próxima reavaliação e acompanhe a fila clínica priorizada por risco e vencimento.",
      "Registre cada reavaliação no mesmo registro de emergência e atualize conduta, risco e destino quando necessário.",
      "Ao definir internação, UTI, centro cirúrgico, alta ou transferência, continue pela transição correspondente sem criar episódio paralelo.",
    ],
    warnings: [
      "Classificação de risco e reavaliação são registros assistenciais; não devem ser alterados apenas para modificar posição na fila.",
      "Abrir um novo atendimento para o mesmo episódio fragmenta o prontuário longitudinal e o ciclo da receita.",
    ],
    links: [
      { label: "Urgência e Emergência", href: "/assistencial/urgencia" },
      { label: "Triagem", href: "/triagem" },
    ],
    keywords: ["urgência", "emergência", "ABCDE", "risco", "reavaliação", "observação", "destino", "SLA"],
    sourceDocs: ["docs/STATUS.md", "docs/MANUAL.md"],
  },
  {
    slug: "uti-acompanhamento-episodio",
    title: "UTI: acompanhar o paciente no mesmo episódio",
    category: "Assistencial",
    audience: ["UTI", "Enfermagem", "Corpo clínico"],
    summary: "Orientação para trabalhar no episódio internado preservando prontuário, prescrições, exames, dispositivos e eventos críticos.",
    steps: [
      "Abra a UTI a partir do atendimento/internação correspondente ao paciente.",
      "Confirme leito, setor e contexto assistencial antes de registrar novas informações.",
      "Use o prontuário longitudinal para evoluções, prescrições, exames e documentos do mesmo episódio.",
      "Registre eventos, dispositivos e acompanhamentos pela operação específica do módulo quando disponível.",
      "Quando houver transferência ou alta da UTI, mantenha a internação e a movimentação de leito como autoridades do fluxo.",
    ],
    warnings: ["Não crie uma nova internação apenas por mudança para UTI; a movimentação deve permanecer vinculada ao episódio vigente."],
    links: [
      { label: "UTI", href: "/assistencial/uti" },
      { label: "Internação", href: "/internacao" },
    ],
    keywords: ["UTI", "intensiva", "leito", "internação", "dispositivo", "episódio", "transferência"],
    sourceDocs: ["docs/STATUS.md", "docs/MANUAL.md"],
  },
  {
    slug: "sae-processo-enfermagem",
    title: "SAE: processo de enfermagem no prontuário longitudinal",
    category: "Assistencial",
    audience: ["Enfermagem", "SAE"],
    summary: "Como manter avaliação, planejamento, aprazamento e registros de enfermagem vinculados ao mesmo atendimento.",
    steps: [
      "Confirme o atendimento/RA antes de iniciar o registro da SAE.",
      "Registre avaliação e necessidades de enfermagem conforme o fluxo disponível.",
      "Planeje cuidados e aprazamentos preservando vínculo com prescrições e demais registros assistenciais.",
      "Acompanhe execução e evolução sem duplicar o atendimento ou transportar dados para outro episódio.",
      "Use os registros longitudinais para continuidade entre setores e turnos.",
    ],
    warnings: ["A SAE complementa o prontuário; não deve manter uma ficha paralela fora do episódio hospitalar."],
    links: [
      { label: "SAE", href: "/assistencial/sae" },
      { label: "Enfermagem", href: "/assistencial/enfermagem" },
    ],
    keywords: ["SAE", "processo de enfermagem", "aprazamento", "cuidados", "evolução", "enfermagem"],
    sourceDocs: ["docs/STATUS.md", "docs/MANUAL.md"],
  },
  {
    slug: "cme-rastreabilidade-processamento",
    title: "CME: rastreabilidade do processamento de materiais",
    category: "Assistencial",
    audience: ["CME", "Centro Cirúrgico", "Enfermagem"],
    summary: "Como manter processamento e rastreabilidade dos materiais integrados ao Centro Cirúrgico e ao episódio assistencial.",
    steps: [
      "Localize o fluxo de material ou conjunto associado à operação assistencial.",
      "Registre as etapas de processamento pela operação própria da CME, preservando identificação e rastreabilidade.",
      "Confirme liberação e disponibilidade antes do uso no Centro Cirúrgico.",
      "No consumo cirúrgico, mantenha vínculo entre material, procedimento, atendimento e equipe quando o sistema disponibilizar essa relação.",
      "Use a trilha histórica para investigar divergências sem alterar registros já consolidados.",
    ],
    warnings: ["Não ajuste manualmente estoque ou rastreabilidade para compensar ausência de etapa do processamento."],
    links: [
      { label: "CME", href: "/assistencial/cme" },
      { label: "Centro Cirúrgico", href: "/assistencial/centro-cirurgico" },
    ],
    keywords: ["CME", "esterilização", "rastreabilidade", "material", "centro cirúrgico", "processamento"],
    sourceDocs: ["docs/STATUS.md", "docs/MANUAL.md"],
  },
  {
    slug: "dialise-sessao-integrada",
    title: "Diálise: registrar a sessão integrada à internação",
    category: "Assistencial",
    audience: ["Diálise", "Enfermagem", "Corpo clínico"],
    summary: "Orientação para manter sessão, acompanhamento e fatos assistenciais vinculados ao mesmo episódio e ao prontuário.",
    steps: [
      "Selecione o atendimento/internação correto antes de iniciar a sessão.",
      "Confirme contexto clínico e prescrições relacionadas ao paciente.",
      "Registre a sessão e seus acompanhamentos pela operação do módulo, preservando o vínculo longitudinal.",
      "Registre intercorrências no episódio correspondente e utilize o prontuário para continuidade assistencial.",
      "Ao concluir, mantenha o registro disponível para Enfermagem, corpo clínico e demais módulos autorizados.",
    ],
    warnings: ["Não crie atendimento separado apenas para registrar uma sessão realizada durante internação vigente."],
    links: [
      { label: "Diálise", href: "/assistencial/dialise" },
      { label: "Prontuário", href: "/prontuario" },
    ],
    keywords: ["diálise", "hemodiálise", "sessão", "internação", "prontuário", "intercorrência"],
    sourceDocs: ["docs/STATUS.md", "docs/MANUAL.md"],
  },
];
