import type { KnowledgeBaseArticle } from "@/modules/knowledge-base/articles";

export const commercialKnowledgeBaseArticles: KnowledgeBaseArticle[] = [
  {
    slug: "comercial-contratos-tabelas",
    title: "Configurar contratos, tabelas e DePara TUSS",
    category: "Receita",
    audience: ["Comercial", "Credenciamento", "Faturamento", "Auditoria"],
    summary: "Como definir a abrangência do contrato, vincular a tabela correta e registrar metodologia e DePara de cobrança sem criar preço ou equivalência implícitos.",
    steps: [
      "Abra Comercial / Contratos e selecione o convênio e o contrato que deseja parametrizar.",
      "Na aba Contrato, confira vigência e selecione o plano/produto quando a negociação não valer para todos os planos do convênio.",
      "Na aba Tabelas / negociação, vincule a fonte correta e escolha a categoria de cobrança; use uma categoria específica antes de Geral quando o contrato exigir cadeias diferentes.",
      "Defina se a edição será fixa ou vigente na data do serviço. Para Brasíndice, CMED ou SIMPRO, informe explicitamente a base de preço prevista no contrato.",
      "Preencha somente os componentes negociados, como CH, HM, SADT, UCO, filme radiológico por m², ajuste, prioridade, arredondamento e adicionais.",
      "Use Itens da tabela para conferir códigos, TUSS, atributos e quantidade de itens da edição. Edições publicadas são históricas; crie uma nova versão para alterações futuras.",
      "Quando a fonte usar código diferente do TUSS, abra DePara TUSS, selecione o mesmo contrato e a fonte vinculada e registre código de origem, TUSS confirmado e vigência. Se a equivalência mudar, encerre a vigência anterior e crie uma nova versão.",
      "Antes de liberar o contrato para uso, abra Prontidão comercial, escolha a data de referência e trate os bloqueios e avisos apresentados.",
      "Depois, use o Simulador de preço para testar códigos reais e confirmar a memória de cálculo antes de depender da configuração em uma conta faturada.",
      "Quando a revisão interna estiver concluída, registre a Homologação comercial. O HIS fotografará a prontidão e sinalizará se a cadeia for alterada depois.",
    ],
    warnings: [
      "Tabela comercial fornece referência e atributos; o contrato define a cobrança. Não cadastre um preço apenas para remover um alerta.",
      "DePara TUSS deve existir como equivalência explícita e auditável. O sistema não sugere nem infere um código equivalente.",
      "Uma fonte precisa estar vinculada ao contrato antes de receber DePara. Vigências ativas do mesmo código/fonte não podem se sobrepor.",
      "Alterações futuras de contrato, tabela ou DePara não devem recalcular silenciosamente contas históricas fechadas.",
    ],
    links: [
      { label: "Contratos comerciais", href: "/comercial" },
      { label: "Prontidão comercial", href: "/comercial/prontidao" },
      { label: "Simulador de preço", href: "/comercial/simulador" },
      { label: "Homologação comercial", href: "/comercial/homologacao" },
      { label: "Fontes e edições", href: "/comercial/tabelas" },
      { label: "DePara TUSS", href: "/comercial/depara" },
      { label: "Regras, CBHPM e pacotes", href: "/comercial/regras" },
    ],
    keywords: ["comercial", "contrato", "credenciamento", "tabela", "amb", "cbhpm", "brasindice", "cmed", "simpro", "tuss", "depara", "ch", "uco", "filme", "simulador", "preço", "homologação"],
    sourceDocs: ["docs/FATURAMENTO_TABELAS_CONTRATOS.md"],
  },
  {
    slug: "comercial-prontidao-contratual",
    title: "Validar a prontidão comercial do contrato",
    category: "Receita",
    audience: ["Comercial", "Credenciamento", "Faturamento", "Auditoria"],
    summary: "Como revisar bloqueios e avisos comerciais por data antes de depender do contrato no faturamento ou na preparação TISS.",
    steps: [
      "Abra Prontidão comercial e selecione o contrato que deseja verificar.",
      "Informe a data de referência correspondente ao atendimento ou à vigência que deseja simular.",
      "Trate primeiro os bloqueios: contrato fora de vigência, tabela/edição sem resolução, edição sem itens, base de preço obrigatória ausente ou componentes de cálculo sem valor contratual.",
      "Para AMB, confirme os componentes exigidos pela edição, inclusive SADT e filme/m² quando houver quantidade de filme.",
      "Para CBHPM, confira UCO e valores monetários de porte de procedimento/anestesia na vigência aplicável.",
      "Revise avisos de TUSS/DePara quando o item não tiver TUSS direto; confirme se o uso correto é tabela própria 00 ou se existe equivalência explícita a cadastrar.",
      "Use o botão de correção de cada diagnóstico para abrir Contrato, Negociação, CBHPM ou DePara já no contexto adequado e execute novamente a prontidão após a correção.",
      "Com a prontidão sem bloqueios, valide códigos reais no Simulador de preço antes da homologação operacional.",
      "Depois da simulação, abra Homologação comercial para registrar a aprovação interna e fotografar os avisos aceitos.",
    ],
    warnings: [
      "Prontidão verde não equivale a homologação com operadora ou validação jurídica do contrato; ela indica apenas ausência de pendências comerciais conhecidas pelo motor para a data escolhida.",
      "O diagnóstico é somente leitura: nunca crie valor, porte, edição ou DePara apenas para transformar o resultado em verde.",
      "Uma conta histórica fechada preserva o snapshot original e não deve ser recalculada silenciosamente após uma mudança futura do contrato.",
    ],
    links: [
      { label: "Prontidão comercial", href: "/comercial/prontidao" },
      { label: "Simulador de preço", href: "/comercial/simulador" },
      { label: "Homologação comercial", href: "/comercial/homologacao" },
      { label: "Contratos comerciais", href: "/comercial" },
      { label: "DePara TUSS", href: "/comercial/depara" },
      { label: "Regras e CBHPM", href: "/comercial/regras" },
    ],
    keywords: ["prontidão", "contrato", "bloqueio", "aviso", "homologação", "amb", "cbhpm", "tuss", "depara", "base de preço", "vigência", "simulador"],
    sourceDocs: ["docs/FATURAMENTO_TABELAS_CONTRATOS.md"],
  },
  {
    slug: "comercial-simulador-precificacao",
    title: "Simular a precificação antes do faturamento",
    category: "Receita",
    audience: ["Comercial", "Credenciamento", "Faturamento", "Auditoria"],
    summary: "Como reproduzir a cadeia contratual de um código sem criar conta, gravar preço ou alterar histórico, conferindo tabela, DePara, CBHPM e regras aplicadas.",
    steps: [
      "Abra Simulador de preço e selecione o contrato que está em homologação ou revisão.",
      "Informe um código da fonte, código próprio ou TUSS e escolha a data e a categoria comercial compatíveis com o atendimento que deseja testar.",
      "Quando necessário, marque urgência, horário especial, acomodação individual, anestesia, mesma via e informe sequência, auxiliares, via de acesso ou origem/tipo.",
      "Execute a simulação e confira o valor base resolvido pela tabela/vínculo, o valor final e a quantidade de regras aplicadas.",
      "Abra a Memória da base para confirmar fonte, edição, código de origem, TUSS, DePara, método, pontos, porte, UCO, filme e ajuste contratual usados pelo motor.",
      "Revise o caminho de regras para conferir a prioridade, operação e o valor antes/depois de cada regra aplicada.",
      "Se o simulador indicar contrato contextual diferente, revise sobreposição, plano, unidade e vigência; não use o valor retornado como homologação do contrato selecionado.",
      "Se retornar sem preço contratual, corrija a prontidão, negociação, CBHPM ou DePara e execute novamente o mesmo cenário.",
      "Depois de testar os cenários relevantes, registre a Homologação comercial e documente as ressalvas ou referências internas da revisão.",
    ],
    warnings: [
      "A simulação é somente leitura e não cria snapshot. O valor definitivo da conta continua sendo registrado no contexto real do atendimento/faturamento.",
      "Não altere dados comerciais apenas para produzir um valor no simulador. Ausência de preço seguro deve permanecer visível até a configuração documental correta.",
      "O simulador reproduz regras cadastradas; ele não valida se o conteúdo do contrato assinado foi parametrizado corretamente sem revisão humana/institucional.",
      "Um contrato geral não prova automaticamente todos os cenários de planos ou unidades mais específicos; teste os contextos relevantes antes da homologação.",
    ],
    links: [
      { label: "Simulador de preço", href: "/comercial/simulador" },
      { label: "Prontidão comercial", href: "/comercial/prontidao" },
      { label: "Homologação comercial", href: "/comercial/homologacao" },
      { label: "Contratos comerciais", href: "/comercial" },
      { label: "DePara TUSS", href: "/comercial/depara" },
      { label: "Regras e CBHPM", href: "/comercial/regras" },
    ],
    keywords: ["simulador", "precificação", "preço", "memória de cálculo", "contrato", "tuss", "depara", "cbhpm", "regra", "urgência", "múltiplos procedimentos", "homologação"],
    sourceDocs: ["docs/FATURAMENTO_TABELAS_CONTRATOS.md"],
  },
  {
    slug: "comercial-homologacao-contratual",
    title: "Homologar a configuração comercial",
    category: "Receita",
    audience: ["Comercial", "Credenciamento", "Faturamento", "Auditoria"],
    summary: "Como registrar a aprovação interna da parametrização comercial, preservar o snapshot revisado e identificar quando a homologação ficou desatualizada após uma mudança.",
    steps: [
      "Abra Homologação comercial e selecione o contrato e a data de referência que foram revisados.",
      "Confirme que a Prontidão comercial não possui bloqueios. Bloqueios impedem a homologação e precisam ser resolvidos na origem.",
      "Execute o Simulador de preço com códigos e contextos representativos do contrato, incluindo cenários de urgência, acomodação, anestesia, auxiliares ou múltiplos procedimentos quando aplicáveis.",
      "Se o contrato for geral, teste também os planos e unidades específicos relevantes, porque uma configuração mais específica pode ter precedência no atendimento real.",
      "Revise os avisos existentes. Quando houver avisos não bloqueantes, marque o aceite explícito somente após compreender e documentar a ressalva.",
      "Registre observações como documento revisado, cenários simulados ou referência interna e use Homologar configuração. A prontidão, data e usuário ficam fotografados no histórico.",
      "Acompanhe o estado da homologação. Se contrato, tabela, edição, item, regra, pacote, CBHPM ou DePara mudar depois, o HIS passa a exibir Desatualizado.",
      "Quando a configuração mudar, repita prontidão e simulação e registre uma nova homologação. A anterior será preservada como substituída.",
      "Se a aprovação precisar ser retirada sem uma nova versão, use Revogar homologação e informe obrigatoriamente o motivo.",
    ],
    warnings: [
      "Homologação comercial no HIS não substitui homologação da operadora, validação jurídica, conferência documental, auditoria institucional ou obrigação regulatória aplicável.",
      "Não force a prontidão para verde criando preço, porte, edição, percentual ou DePara sem respaldo documental.",
      "Uma homologação desatualizada continua no histórico como evidência do que foi aprovado anteriormente, mas não deve ser interpretada como aprovação da configuração atual.",
      "A homologação não recalcula contas históricas e não altera snapshots já gravados no faturamento.",
    ],
    links: [
      { label: "Homologação comercial", href: "/comercial/homologacao" },
      { label: "Prontidão comercial", href: "/comercial/prontidao" },
      { label: "Simulador de preço", href: "/comercial/simulador" },
      { label: "Contratos comerciais", href: "/comercial" },
      { label: "DePara TUSS", href: "/comercial/depara" },
      { label: "Regras e CBHPM", href: "/comercial/regras" },
    ],
    keywords: ["homologação", "aprovação", "governança", "contrato", "prontidão", "simulador", "snapshot", "desatualizado", "revogação", "auditoria", "comercial"],
    sourceDocs: ["docs/FATURAMENTO_TABELAS_CONTRATOS.md"],
  },
  {
    slug: "comercial-regras-cbhpm-pacotes",
    title: "Cadastrar regras, portes CBHPM e pacotes",
    category: "Receita",
    audience: ["Comercial", "Credenciamento", "Faturamento", "Auditoria"],
    summary: "Como versionar exceções de cobrança, valores monetários de porte CBHPM e pacotes preservando prioridade, vigência e memória de cálculo.",
    steps: [
      "Abra Regras, CBHPM e pacotes a partir do workspace Comercial.",
      "Para uma regra contratual, selecione contrato e categoria, informe um código estável, descrição, operação, prioridade e vigência.",
      "Preencha apenas as condições que realmente constam do contrato, como urgência, horário especial, acomodação individual, anestesia, sequência, auxiliares, via, origem ou código específico.",
      "Para CBHPM, selecione o vínculo CBHPM correto, escolha Procedimento ou Anestesia e informe exatamente o porte, valor monetário negociado e sua vigência.",
      "Quando houver reajuste ou aditivo de porte, encerre a vigência anterior e crie uma nova versão; vigências ativas sobrepostas são bloqueadas.",
      "Para pacote, cadastre código, nome, valor, vigência, inclusões e exclusões e depois detalhe os itens e a regra de cobrança de excedente.",
      "Confirme o feedback inline de salvamento e use o histórico/a memória de cálculo para auditar qual regra ou valor foi aplicado.",
      "Depois de qualquer mudança relevante, revise a Homologação comercial; uma aprovação anterior deve aparecer como desatualizada.",
    ],
    warnings: [
      "O texto do porte CBHPM não possui valor monetário universal; o valor precisa estar cadastrado no vínculo contratual e na vigência correta.",
      "Não copie percentuais de contratos de terceiros como padrão do HIS.",
      "Se faltar configuração contratual válida, o resultado correto é sem preço contratual, não um fallback inventado.",
    ],
    links: [
      { label: "Regras, CBHPM e pacotes", href: "/comercial/regras" },
      { label: "Prontidão comercial", href: "/comercial/prontidao" },
      { label: "Simulador de preço", href: "/comercial/simulador" },
      { label: "Homologação comercial", href: "/comercial/homologacao" },
      { label: "Contratos comerciais", href: "/comercial" },
      { label: "DePara TUSS", href: "/comercial/depara" },
    ],
    keywords: ["regra", "cbhpm", "porte", "anestesia", "urgencia", "acomodacao", "multiplo", "via", "pacote", "vigencia", "faturamento", "simulador", "homologação"],
    sourceDocs: ["docs/FATURAMENTO_TABELAS_CONTRATOS.md"],
  },
];
