import type { KnowledgeBaseArticle } from "@/modules/knowledge-base/articles";

export const billingTissKnowledgeBaseArticles: KnowledgeBaseArticle[] = [
  {
    slug: "faturamento-conta-producao",
    title: "Conferir conta e produção antes do TISS",
    category: "Receita",
    audience: ["Faturamento", "Auditoria", "Contas Médicas"],
    summary: "Como usar a relação de contas, conferir fatos assistenciais e revisar a precificação antes de gerar a guia TISS.",
    steps: [
      "Abra Faturamento / Contas e filtre por competência, convênio, plano, natureza do atendimento e status.",
      "Entre na conta correta e confirme paciente, atendimento, cobertura, período e natureza faturável antes de editar qualquer item.",
      "Confira Produção para validar se procedimentos, materiais, medicamentos, taxas e demais fatos assistenciais chegaram à conta pelo fluxo canônico.",
      "Revise tabela, código, quantidade, valor contratual e memória de cálculo. Divergências devem ser corrigidas na origem contratual ou pelo fluxo transacional do faturamento, nunca por DML direto.",
      "Em Internação, confirme se a conta é corrente, parcial, final ou complementar e se o período não sobrepõe conta já fechada.",
      "Somente avance para a Guia TISS quando a conta estiver coerente com o atendimento, a auditoria e a regra contratual aplicável.",
    ],
    warnings: [
      "A relação de contas é uma visão operacional; escritas permanecem nos formulários e RPCs canônicos.",
      "Não altere a natureza do atendimento para encaixar uma cobrança depois que houver Guia TISS ativa.",
      "Farmácia ou Almoxarifado identificam origem operacional do lançamento e não substituem a localização física do paciente.",
    ],
    links: [
      { label: "Relação de contas", href: "/faturamento/contas" },
      { label: "Produção", href: "/faturamento/producao" },
      { label: "Central de faturamento", href: "/faturamento" },
    ],
    keywords: ["conta", "produção", "competência", "convênio", "precificação", "memória de cálculo", "internação", "parcial", "final"],
    sourceDocs: ["docs/FATURAMENTO_UX_OPERACIONAL_V2.md", "docs/FATURAMENTO_TABELAS_CONTRATOS.md"],
  },
  {
    slug: "faturamento-tiss-guia-lote",
    title: "Validar Guia TISS e fechar lote sem misturar atendimentos",
    category: "TISS",
    audience: ["Faturamento", "Contas Médicas", "Auditoria"],
    summary: "Sequência segura entre conta, guia, validação e lote TISS, preservando versão de comunicação e natureza faturável.",
    steps: [
      "Abra Guias TISS e localize a guia vinculada à conta correta. O número da Guia do Prestador deve acompanhar o número do atendimento conforme a regra do HIS.",
      "Confira beneficiário, prestador, profissional, CBO/conselho, procedimentos, datas, quantidades, valores e demais snapshots exigidos pela versão de comunicação.",
      "Execute a validação da guia e trate os bloqueios apontados antes de tentar fechar ou transmitir.",
      "Na criação do lote, selecione a mesma natureza faturável das contas: Pronto Atendimento, Ambulatório, Internação ou SADT.",
      "Não misture naturezas diferentes no mesmo lote; o HIS bloqueia essa composição para evitar inconsistência de faturamento.",
      "Confirme a versão de comunicação fotografada na guia/lote e gere a mensagem final somente pelo fluxo TISS transacional.",
    ],
    warnings: [
      "Não reutilize XML ou Preview de outra versão de comunicação como evidência de validação da guia atual.",
      "Conta corrente interna não é faturável; para Internação use snapshots parciais/finais conforme o período efetivamente fechado.",
      "Erros de CBO, conselho, identificação ou contrato devem ser corrigidos na fonte cadastral/contratual e revalidados.",
    ],
    links: [
      { label: "Guias TISS", href: "/faturamento/guias" },
      { label: "Lotes TISS", href: "/faturamento/lotes" },
      { label: "Cadastros TISS", href: "/cadastros/tiss" },
    ],
    keywords: ["TISS", "guia", "lote", "XML", "CBO", "conselho", "versão", "SADT", "internação", "validação"],
    sourceDocs: ["docs/TISS_XSD_ANS.md", "docs/MANUAL_CADASTROS_TISS.md", "docs/FATURAMENTO_UX_OPERACIONAL_V2.md"],
  },
  {
    slug: "faturamento-glosa-analise",
    title: "Analisar glosa sem perder o vínculo com conta, guia e recebível",
    category: "Receita",
    audience: ["Faturamento", "Auditoria", "Recurso de Glosas", "Financeiro"],
    summary: "Como revisar a glosa a partir do ciclo da receita e decidir se o item será aceito, corrigido ou recursado.",
    steps: [
      "Abra Faturamento / Glosas e localize o item pelo protocolo, guia, conta, paciente ou operadora.",
      "Compare valor apresentado, valor liberado, valor glosado e motivo/código de glosa com a guia e a memória contratual da conta.",
      "Confirme se a causa está em cadastro, autorização, regra contratual, execução assistencial, TISS ou processamento da operadora.",
      "Quando houver fundamento para recurso, mantenha o vínculo do item com a glosa original e siga para Recursos; não crie um item financeiro paralelo.",
      "Quando a glosa for aceita, preserve a rastreabilidade da decisão para que o Financeiro considere corretamente o saldo a receber.",
      "Use o histórico do ciclo da receita para conferir alterações posteriores e evitar recobrança ou recurso duplicado.",
    ],
    warnings: [
      "Não ajuste o recebível manualmente para esconder uma glosa ainda não analisada.",
      "Valor apresentado a maior e incompatibilidade de CBO/especialidade exigem revisão da regra/cadastro que originou a cobrança, além da decisão sobre recurso.",
    ],
    links: [
      { label: "Glosas", href: "/faturamento/glosas" },
      { label: "Recursos", href: "/faturamento/recursos" },
      { label: "Recebíveis", href: "/financeiro/recebiveis" },
    ],
    keywords: ["glosa", "valor apresentado", "valor liberado", "motivo", "operadora", "recurso", "CBO", "recebível"],
    sourceDocs: ["docs/FATURAMENTO_UX_OPERACIONAL_V2.md", "docs/STATUS.md"],
  },
  {
    slug: "faturamento-recurso-glosa-retorno",
    title: "Registrar retorno de recurso de glosa de forma transacional",
    category: "Receita",
    audience: ["Recurso de Glosas", "Faturamento", "Financeiro", "Auditoria"],
    summary: "Como registrar deferimento e indeferimento da operadora sem ultrapassar o valor recursado e mantendo o recebível sincronizado.",
    steps: [
      "Abra Faturamento / Recursos e entre no recurso correspondente ao protocolo enviado à operadora.",
      "Confira o resultado financeiro atual: valor glosado, recursado, já deferido, já indeferido e saldo ainda pendente.",
      "Use Registrar retorno e informe data/hora, protocolo da operadora e os valores deferido e indeferido de cada item analisado.",
      "O HIS valida se o retorno excede o saldo recursado do item ou a glosa original e bloqueia valores inválidos.",
      "Ao confirmar, a RPC transacional atualiza retorno, itens do recurso, situação da glosa e recalcula o recebível relacionado.",
      "Reabra o recurso para conferir o saldo pendente; novos retornos podem ser registrados apenas sobre o valor ainda não analisado.",
    ],
    warnings: [
      "Não grave valor_deferido ou valor_indeferido por DML direto na interface ou no banco.",
      "Um retorno parcial não encerra automaticamente itens que ainda possuem saldo recursado pendente.",
      "Protocolo e observação devem refletir o documento/retorno real da operadora para manter a trilha de auditoria.",
    ],
    links: [
      { label: "Recursos", href: "/faturamento/recursos" },
      { label: "Glosas", href: "/faturamento/glosas" },
      { label: "Recebíveis", href: "/financeiro/recebiveis" },
    ],
    keywords: ["recurso", "retorno", "deferido", "indeferido", "protocolo", "saldo recursado", "RPC", "recebível"],
    sourceDocs: ["docs/FATURAMENTO_UX_OPERACIONAL_V2.md", "docs/STATUS.md"],
  },
  {
    slug: "financeiro-recebiveis-nfse",
    title: "Conciliar recebível e NFS-e depois do faturamento",
    category: "Financeiro",
    audience: ["Financeiro", "Faturamento"],
    summary: "Como acompanhar previsão, recebimento, glosa, recurso e nota fiscal sem quebrar o vínculo com o lote TISS.",
    steps: [
      "Abra Recebíveis e localize o título originado pelo lote/conta correspondente.",
      "Confira valor apresentado, glosas, recursos deferidos/indeferidos e saldo líquido antes de registrar recebimento.",
      "Registre baixa ou conciliação somente pelo fluxo financeiro transacional para preservar histórico e auditoria.",
      "Na área de Notas fiscais, acompanhe a NFS-e vinculada ao recebível e registre emissão manual somente quando a integração automática não for utilizada.",
      "Quando houver retorno posterior de recurso de glosa, confirme que o recebível foi recalculado antes de concluir a conciliação final.",
    ],
    warnings: [
      "Não conte a mesma nota fiscal duas vezes apenas por aparecer em diferentes visões do mesmo ciclo.",
      "NFS-e emitida e recebimento financeiro são eventos distintos; ambos precisam manter seu próprio estado e trilha de auditoria.",
    ],
    links: [
      { label: "Recebíveis", href: "/financeiro/recebiveis" },
      { label: "Notas fiscais", href: "/financeiro/notas-fiscais" },
      { label: "Financeiro", href: "/financeiro" },
    ],
    keywords: ["recebível", "NFS-e", "nota fiscal", "conciliação", "baixa", "glosa", "recurso", "financeiro"],
    sourceDocs: ["docs/FATURAMENTO_UX_OPERACIONAL_V2.md", "docs/STATUS.md"],
  },
];
