import { HeartPulse, Accessibility, Siren, UsersRound } from "lucide-react";
import { emitirSenhaTotem } from "@/modules/senhas/actions";

export default async function TotemPage({ params, searchParams }: { params: Promise<{ unidadeId: string }>; searchParams: Promise<{ senha?: string; erro?: string }> }) {
  const { unidadeId } = await params;
  const { senha, erro } = await searchParams;
  return <main className="min-h-screen bg-slate-100 p-5 sm:p-8"><div className="mx-auto max-w-4xl">
    <header className="mb-8 flex items-center justify-center gap-3 text-center"><span className="grid size-14 place-items-center rounded-2xl bg-brand-950 text-white shadow-lg"><HeartPulse className="size-7" /></span><div><h1 className="text-3xl font-bold tracking-tight text-slate-950">MedSync · Totem de Senhas</h1><p className="mt-1 text-sm text-slate-500">Retire sua senha antes de dirigir-se à recepção.</p></div></header>
    {senha ? <section className="mb-8 rounded-3xl border border-emerald-200 bg-white p-8 text-center shadow-sm"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-600">Sua senha</p><div className="mt-3 text-7xl font-black tracking-tight text-brand-950">{senha}</div><p className="mt-4 text-slate-600">Aguarde a chamada no painel. Tenha seus documentos em mãos.</p></section> : null}
    {erro ? <div className="mb-6 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-center text-sm font-medium text-rose-700">Não foi possível emitir a senha. Procure um colaborador.</div> : null}
    <section className="grid gap-4 md:grid-cols-3">
      <form action={emitirSenhaTotem} className="contents"><input type="hidden" name="unidade_id" value={unidadeId}/><input type="hidden" name="setor_codigo" value="recepcao"/><input type="hidden" name="prioridade" value="normal"/><button className="rounded-3xl border border-slate-200 bg-white p-8 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-brand-200 hover:shadow-md"><span className="grid size-14 place-items-center rounded-2xl bg-brand-50 text-brand-700"><UsersRound className="size-7"/></span><h2 className="mt-5 text-xl font-bold text-slate-950">Atendimento Geral</h2><p className="mt-2 text-sm text-slate-500">Consultas, exames, internação, informações e recepção.</p></button></form>
      <form action={emitirSenhaTotem} className="contents"><input type="hidden" name="unidade_id" value={unidadeId}/><input type="hidden" name="setor_codigo" value="recepcao"/><input type="hidden" name="prioridade" value="preferencial"/><button className="rounded-3xl border border-slate-200 bg-white p-8 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-violet-200 hover:shadow-md"><span className="grid size-14 place-items-center rounded-2xl bg-violet-50 text-violet-700"><Accessibility className="size-7"/></span><h2 className="mt-5 text-xl font-bold text-slate-950">Atendimento Preferencial</h2><p className="mt-2 text-sm text-slate-500">Idosos, gestantes, PCD e demais prioridades legais.</p></button></form>
      <form action={emitirSenhaTotem} className="contents"><input type="hidden" name="unidade_id" value={unidadeId}/><input type="hidden" name="setor_codigo" value="recepcao"/><input type="hidden" name="prioridade" value="emergencia"/><button className="rounded-3xl border border-rose-200 bg-rose-50 p-8 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className="grid size-14 place-items-center rounded-2xl bg-rose-100 text-rose-700"><Siren className="size-7"/></span><h2 className="mt-5 text-xl font-bold text-rose-950">Urgência / Emergência</h2><p className="mt-2 text-sm text-rose-700">Para situações que necessitam avaliação prioritária imediata.</p></button></form>
    </section>
    <p className="mt-8 text-center text-xs text-slate-400">A senha é obrigatória para iniciar o atendimento administrativo.</p>
  </div></main>;
}
