import Link from "next/link";
import { notFound } from "next/navigation";
import { Building2, CalendarClock, FileText, Handshake, Mail, MapPin, Phone, ReceiptText, ShieldCheck, TableProperties } from "lucide-react";
import { CadastrosWorkspaceNav, CadastroKpi } from "@/components/cadastros/cadastros-workspace-nav";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";
import { criarUrlFotoAssinada } from "@/modules/cadastros/fotos";

function one<T>(value:T|T[]|null){return Array.isArray(value)?value[0]??null:value;}
function dataBr(value:string|null|undefined){return value?new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR"):"—";}

export default async function Convenio360Page({params}:{params:Promise<{convenioId:string}>}){
  const {convenioId}=await params;
  const supabase=await createClient();
  const [{data:convenio},{data:planos},{data:contratos},{data:edicoes},{data:emails},{data:telefones},{data:enderecos}]=await Promise.all([
    supabase.from("convenios").select("id,registro_ans,razao_social,nome_fantasia,cnpj,telefone,email,logo_path,ativo").eq("id",convenioId).maybeSingle(),
    supabase.from("convenio_planos").select("id,nome,codigo,acomodacao,ativo").eq("convenio_id",convenioId).order("nome"),
    supabase.from("credenciamento_contratos").select("id,numero_contrato,data_inicio,data_fim,status,prazo_pagamento_dias,reajuste_indice,contato_comercial,email_comercial,tabelas:credenciamento_tabelas(id,nome,referencia,vigencia_inicio,vigencia_fim,ativo)").eq("convenio_id",convenioId).order("created_at",{ascending:false}),
    supabase.from("tabelas_comerciais_edicoes").select("id,nome_edicao,referencia,vigencia_inicio,vigencia_fim,status,fonte:tabelas_comerciais_fontes(nome,tipo)").eq("convenio_id",convenioId).order("vigencia_inicio",{ascending:false}),
    supabase.from("convenio_emails").select("id,email,tipo,principal").eq("convenio_id",convenioId).order("principal",{ascending:false}),
    supabase.from("convenio_telefones").select("id,telefone,tipo,principal").eq("convenio_id",convenioId).order("principal",{ascending:false}),
    supabase.from("convenio_enderecos").select("id,tipo,logradouro,numero,complemento,bairro,cidade,uf,cep,principal").eq("convenio_id",convenioId).order("principal",{ascending:false}),
  ]);
  if(!convenio) notFound();
  const logoUrl=await criarUrlFotoAssinada(supabase,convenio.logo_path);
  const ativos=(contratos??[]).filter(c=>c.status==="ativo");
  const hoje=new Date();const em90=new Date(hoje.getTime()+90*86400000);
  const vencendo=ativos.filter(c=>c.data_fim&&new Date(`${c.data_fim}T23:59:59`)>=hoje&&new Date(`${c.data_fim}T23:59:59`)<=em90);
  const tabelasContrato=ativos.reduce((n,c)=>n+(Array.isArray(c.tabelas)?c.tabelas.filter(t=>t.ativo).length:0),0);
  return <SectionPage eyebrow="Cadastros / Convênios / Ficha 360°" title={convenio.nome_fantasia} description="Visão consolidada da operadora: cadastro, planos, contratos, tabelas, contatos e atalhos operacionais.">
    <CadastrosWorkspaceNav active="/convenios"/>
    <section className="ui-card mb-5 p-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-4"><span className="grid size-16 shrink-0 place-items-center overflow-hidden rounded-2xl border border-slate-200 bg-white text-brand-700" style={logoUrl?{backgroundImage:`url(${logoUrl})`,backgroundPosition:"center",backgroundSize:"contain",backgroundRepeat:"no-repeat"}:undefined}>{logoUrl?null:<Building2 className="size-7"/>}</span><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black text-slate-950">{convenio.nome_fantasia}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${convenio.registro_ans?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{convenio.registro_ans?`ANS ${convenio.registro_ans}`:"ANS pendente"}</span></div><p className="mt-1 text-sm text-slate-500">{convenio.razao_social}</p><p className="mt-1 text-xs text-slate-400">CNPJ {convenio.cnpj||"—"}</p></div></div><div className="flex flex-wrap gap-2"><Link href={`/central-guias?convenio=${convenio.id}`} className="ui-button-secondary"><ShieldCheck className="size-4"/>Central de Guias</Link><Link href={`/faturamento?convenio=${convenio.id}`} className="ui-button-secondary"><ReceiptText className="size-4"/>Faturamento</Link><Link href="/comercial" className="ui-button-primary"><Handshake className="size-4"/>Contratos</Link></div></div></section>
    <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><CadastroKpi label="Planos ativos" value={(planos??[]).filter(p=>p.ativo).length}/><CadastroKpi label="Contratos ativos" value={ativos.length}/><CadastroKpi label="Vencem em 90 dias" value={vencendo.length} detail={vencendo.length?"Ação comercial necessária":"Sem vencimento próximo"}/><CadastroKpi label="Tabelas contratuais" value={tabelasContrato}/><CadastroKpi label="Edições próprias" value={(edicoes??[]).length}/></section>
    <div className="grid gap-5 xl:grid-cols-3"><section className="ui-card overflow-hidden xl:col-span-2"><div className="border-b border-slate-100 p-5"><h2 className="flex items-center gap-2 font-bold text-slate-950"><Handshake className="size-5 text-brand-700"/>Contratos e vigências</h2></div><div className="divide-y divide-slate-100">{contratos?.length?contratos.map(c=>{const tabelas=Array.isArray(c.tabelas)?c.tabelas:[];return <article key={c.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold text-slate-900">Contrato {c.numero_contrato||"sem número"}</h3><p className="mt-1 text-sm text-slate-500">{dataBr(c.data_inicio)} → {c.data_fim?dataBr(c.data_fim):"vigência aberta"} · pagamento {c.prazo_pagamento_dias?`${c.prazo_pagamento_dias} dias`:"não informado"}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${c.status==="ativo"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{c.status}</span></div>{tabelas.length?<div className="mt-3 flex flex-wrap gap-2">{tabelas.map(t=><span key={t.id} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-600"><b>{t.nome}</b> · {t.referencia||"sem referência"}</span>)}</div>:null}</article>}):<p className="p-8 text-center text-sm text-slate-500">Nenhum contrato cadastrado para esta operadora.</p>}</div></section>
      <aside className="space-y-5"><section className="ui-card p-5"><h2 className="flex items-center gap-2 font-bold text-slate-950"><FileText className="size-5 text-brand-700"/>Dados e contatos</h2><div className="mt-4 space-y-3 text-sm"><Info icon={Mail} label="E-mail" value={emails?.[0]?.email||convenio.email||"—"}/><Info icon={Phone} label="Telefone" value={telefones?.[0]?.telefone||convenio.telefone||"—"}/><Info icon={MapPin} label="Endereço" value={enderecos?.[0]?`${enderecos[0].logradouro}, ${enderecos[0].numero||"s/n"} · ${enderecos[0].cidade}/${enderecos[0].uf}`:"—"}/></div></section><section className="ui-card p-5"><h2 className="flex items-center gap-2 font-bold text-slate-950"><TableProperties className="size-5 text-brand-700"/>Planos</h2><div className="mt-3 space-y-2">{planos?.length?planos.map(p=><div key={p.id} className="rounded-xl bg-slate-50 p-3"><p className="font-semibold text-slate-800">{p.nome}</p><p className="mt-1 text-xs text-slate-500">{p.codigo||"Sem código"} · {p.acomodacao||"Acomodação não informada"}</p></div>):<p className="text-sm text-slate-500">Nenhum plano cadastrado.</p>}</div></section></aside></div>
    <section className="ui-card mt-5 overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="flex items-center gap-2 font-bold text-slate-950"><CalendarClock className="size-5 text-brand-700"/>Tabelas comerciais vinculadas diretamente à operadora</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Fonte</th><th className="px-4 py-3">Edição</th><th className="px-4 py-3">Referência</th><th className="px-4 py-3">Vigência</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{edicoes?.length?edicoes.map(e=>{const f=one(e.fonte);return <tr key={e.id}><td className="px-4 py-3 font-medium">{f?.nome||"—"}</td><td className="px-4 py-3">{e.nome_edicao}</td><td className="px-4 py-3">{e.referencia||"—"}</td><td className="px-4 py-3">{dataBr(e.vigencia_inicio)} → {e.vigencia_fim?dataBr(e.vigencia_fim):"aberta"}</td><td className="px-4 py-3 capitalize">{e.status}</td></tr>}):<tr><td colSpan={5} className="p-8 text-center text-slate-500">Nenhuma edição específica da operadora.</td></tr>}</tbody></table></div></section>
  </SectionPage>;
}
function Info({icon:Icon,label,value}:{icon:typeof Mail;label:string;value:string}){return <div className="flex gap-3 rounded-xl bg-slate-50 p-3"><Icon className="mt-0.5 size-4 text-slate-400"/><div><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 font-medium text-slate-700">{value}</p></div></div>}
