import Link from "next/link";
import { FileCheck2 } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { createClient } from "@/lib/supabase/server";

function one<T>(rel:T|T[]|null){return Array.isArray(rel)?rel[0]??null:rel;}

export default async function ContasMedicasPage(){
  const supabase=await createClient();
  const {data:processos}=await supabase.from("contas_medicas_processos").select("id,status,total_conta,total_autorizado,total_nao_autorizado,created_at,conta:contas_faturamento(id,competencia,auditoria_liberada,contas_medicas_liberada),atendimento:atendimentos(numero_atendimento),paciente:pacientes(nome_completo,ra,numero_registro),convenio:convenios(nome_fantasia)").order("created_at",{ascending:false}).limit(100);
  return <SectionPage eyebrow="Receita / Contas Médicas" title="Contas Médicas" description="Conferência final de documentação, autorizações, contratos e valores antes da geração TISS.">
    <section className="ui-card overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-100 px-5 py-4"><FileCheck2 className="size-5 text-brand-700"/><div><h2 className="font-semibold text-slate-900">Fila de processamento</h2><p className="text-sm text-slate-500">Somente contas liberadas pela Auditoria devem seguir para esta etapa.</p></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Paciente</th><th className="px-4 py-3">Atendimento</th><th className="px-4 py-3">Convênio</th><th className="px-4 py-3">Competência</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Não autorizado</th><th className="px-4 py-3">Status</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{processos?.length?processos.map(p=>{const pac=one(p.paciente),at=one(p.atendimento),conv=one(p.convenio),conta=one(p.conta);return <tr key={p.id}><td className="px-4 py-3"><b>{pac?.nome_completo??"—"}</b><div className="text-xs text-slate-400">Registro #{pac?.numero_registro??"—"} · {pac?.ra??"—"}</div></td><td className="px-4 py-3">#{at?.numero_atendimento??"—"}</td><td className="px-4 py-3">{conv?.nome_fantasia??"Particular"}</td><td className="px-4 py-3">{conta?.competencia??"—"}</td><td className="px-4 py-3">R$ {Number(p.total_conta||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}</td><td className="px-4 py-3 text-rose-600">R$ {Number(p.total_nao_autorizado||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}</td><td className="px-4 py-3 capitalize">{String(p.status).replaceAll("_"," ")}</td><td className="px-4 py-3"><Link className="text-brand-700 hover:underline" href={`/faturamento/${conta?.id}`}>Abrir conta</Link></td></tr>}):<tr><td colSpan={8} className="px-4 py-8 text-center text-slate-500">Nenhuma conta em Contas Médicas.</td></tr>}</tbody></table></div></section>
  </SectionPage>;
}
