-- Canonical repository migration for the live 20260828194919 Internação package.
alter table public.integracao_eventos drop constraint if exists integracao_eventos_tipo_check;
alter table public.integracao_eventos add constraint integracao_eventos_tipo_check check(tipo_evento=any(array['exame.liberado','imagem.executada','laudo.liberado','cirurgia.iniciada','cirurgia.concluida','opme.utilizada','producao.registrada','prescricao.assinada','farmacia.validada','medicamento.dispensado','medicamento.administrado','medicamento.devolvido','estoque.consumo_paciente','internacao.admitida','leito.alocado','leito.transferido','internacao.alta','leito.higienizacao_concluida']::text[]));

create or replace function public.admitir_internacao_operacional(p_atendimento_id uuid,p_setor text,p_profissional_responsavel_id uuid default null,p_leito_id uuid default null,p_acomodacao text default null,p_acomodacao_tuss49_codigo text default null,p_motivo text default null,p_previsao_alta date default null,p_observacoes text default null) returns uuid language plpgsql security definer set search_path='' as $$
declare a public.atendimentos%rowtype; d record; i uuid;
begin
 if auth.uid() is null then raise exception 'INTERNACAO_AUTENTICACAO_OBRIGATORIA' using errcode='42501'; end if;
 if coalesce(btrim(p_setor),'')='' then raise exception 'INTERNACAO_SETOR_OBRIGATORIO'; end if;
 select * into a from public.atendimentos where id=p_atendimento_id for update;
 if not found then raise exception 'INTERNACAO_ATENDIMENTO_NAO_LOCALIZADO'; end if;
 if not public.tem_unidade(a.empresa_id,a.unidade_id) then raise exception 'INTERNACAO_UNIDADE_FORA_ESCOPO' using errcode='42501'; end if;
 if a.status in('alta','cancelado') then raise exception 'INTERNACAO_ATENDIMENTO_ENCERRADO'; end if;
 if not(public.tem_permissao(a.empresa_id,a.unidade_id,'internacao.admitir') or public.tem_permissao(a.empresa_id,a.unidade_id,'internacao.criar') or public.tem_permissao(a.empresa_id,a.unidade_id,'internacao.gerenciar')) then raise exception 'INTERNACAO_SEM_PERMISSAO_ADMITIR' using errcode='42501'; end if;
 if exists(select 1 from public.internacoes x where x.atendimento_id=a.id and x.status in('aguardando_leito','internado','transferido')) then raise exception 'INTERNACAO_ATIVA_JA_EXISTE'; end if;
 if p_profissional_responsavel_id is not null and not exists(select 1 from public.profissionais p where p.id=p_profissional_responsavel_id and p.empresa_id=a.empresa_id and p.ativo) then raise exception 'INTERNACAO_RESPONSAVEL_INVALIDO'; end if;
 if a.cobertura::text='convenio' and coalesce(btrim(p_acomodacao_tuss49_codigo),'')='' then raise exception 'INTERNACAO_ACOMODACAO_ANS_OBRIGATORIA'; end if;
 if coalesce(btrim(p_acomodacao_tuss49_codigo),'')<>'' then select conceito_id,codigo,display,versao,canonical into d from public.ans_fhir_dominios_ativos where tabela=49 and codigo=btrim(p_acomodacao_tuss49_codigo) limit 1; if d.codigo is null then raise exception 'INTERNACAO_ACOMODACAO_ANS_INVALIDA'; end if; end if;
 insert into public.internacoes(empresa_id,unidade_id,atendimento_id,profissional_responsavel_id,setor,acomodacao,acomodacao_tuss49_conceito_id,acomodacao_tuss49_codigo,acomodacao_tuss49_descricao,acomodacao_tuss49_versao,acomodacao_tuss49_canonical,motivo,previsao_alta,observacoes,status,created_by,updated_by)
 values(a.empresa_id,a.unidade_id,a.id,p_profissional_responsavel_id,btrim(p_setor),nullif(btrim(p_acomodacao),''),d.conceito_id,d.codigo,d.display,d.versao,d.canonical,nullif(btrim(p_motivo),''),p_previsao_alta,nullif(btrim(p_observacoes),''),'aguardando_leito',auth.uid(),auth.uid()) returning id into i;
 update public.atendimentos set status='em_atendimento',setor_atual=btrim(p_setor),ultima_movimentacao_em=now(),updated_at=now(),updated_by=auth.uid() where id=a.id;
 if p_leito_id is not null then perform public.movimentar_internacao_leito(i,p_leito_id,'Admissão'); end if;
 return i;
end $$;
revoke execute on function public.admitir_internacao_operacional(uuid,text,uuid,uuid,text,text,text,date,text) from public,anon; grant execute on function public.admitir_internacao_operacional(uuid,text,uuid,uuid,text,text,text,date,text) to authenticated;

create or replace function public.sincronizar_contexto_atendimento_internacao() returns trigger language plpgsql security definer set search_path='' as $$begin
 if new.status in('aguardando_leito','internado','transferido') then update public.atendimentos set status='em_atendimento',setor_atual=coalesce(nullif(new.setor,''),setor_atual),ultima_movimentacao_em=now(),updated_at=now(),updated_by=coalesce(auth.uid(),new.updated_by,new.created_by) where id=new.atendimento_id and status not in('alta','cancelado'); end if; return new; end$$;
revoke execute on function public.sincronizar_contexto_atendimento_internacao() from public,anon,authenticated;
drop trigger if exists trg_sincronizar_contexto_atendimento_internacao on public.internacoes; create trigger trg_sincronizar_contexto_atendimento_internacao after insert or update of status,setor,leito_id on public.internacoes for each row execute function public.sincronizar_contexto_atendimento_internacao();

create or replace function public.capturar_integracao_internacao() returns trigger language plpgsql security definer set search_path='' as $$declare p uuid;begin
 select paciente_id into p from public.atendimentos where id=new.atendimento_id;
 if tg_op='INSERT' then perform public.registrar_integracao_evento_internal(new.empresa_id,new.unidade_id,new.atendimento_id,p,'internacao.admitida','internacoes',new.id,new.data_internacao,jsonb_build_object('internacao_id',new.id,'status',new.status,'setor',new.setor,'leito_id',new.leito_id,'acomodacao',new.acomodacao,'tipo_internacao_ans_codigo',new.tipo_internacao_ans_codigo));
 elsif new.status='alta' and old.status is distinct from new.status then perform public.registrar_integracao_evento_internal(new.empresa_id,new.unidade_id,new.atendimento_id,p,'internacao.alta','internacoes',new.id,coalesce(new.data_alta,now()),jsonb_build_object('internacao_id',new.id,'motivo_alta',new.motivo_alta,'data_alta',new.data_alta)); end if; return new; end$$;
revoke execute on function public.capturar_integracao_internacao() from public,anon,authenticated;
drop trigger if exists trg_capturar_integracao_internacao on public.internacoes; create trigger trg_capturar_integracao_internacao after insert or update of status on public.internacoes for each row execute function public.capturar_integracao_internacao();

create or replace function public.capturar_integracao_movimentacao_leito() returns trigger language plpgsql security definer set search_path='' as $$declare p uuid;t text;begin
 t:=case new.tipo when 'admissao' then 'leito.alocado' when 'transferencia' then 'leito.transferido' end; if t is null then return new; end if;
 select paciente_id into p from public.atendimentos where id=new.atendimento_id; perform public.registrar_integracao_evento_internal(new.empresa_id,new.unidade_id,new.atendimento_id,p,t,'movimentacoes_leitos',new.id,new.movimentado_em,jsonb_build_object('internacao_id',new.internacao_id,'leito_origem_id',new.leito_origem_id,'leito_destino_id',new.leito_destino_id,'motivo',new.motivo)); return new; end$$;
revoke execute on function public.capturar_integracao_movimentacao_leito() from public,anon,authenticated;
drop trigger if exists trg_capturar_integracao_movimentacao_leito on public.movimentacoes_leitos; create trigger trg_capturar_integracao_movimentacao_leito after insert on public.movimentacoes_leitos for each row execute function public.capturar_integracao_movimentacao_leito();

create or replace function public.capturar_integracao_higienizacao_leito() returns trigger language plpgsql security definer set search_path='' as $$declare p uuid;begin
 if new.status='concluida' and(tg_op='INSERT' or old.status is distinct from new.status) then if new.atendimento_id is not null then select paciente_id into p from public.atendimentos where id=new.atendimento_id; end if; perform public.registrar_integracao_evento_internal(new.empresa_id,new.unidade_id,new.atendimento_id,p,'leito.higienizacao_concluida','leito_higienizacoes',new.id,coalesce(new.concluida_em,now()),jsonb_build_object('internacao_id',new.internacao_id,'leito_id',new.leito_id)); end if; return new; end$$;
revoke execute on function public.capturar_integracao_higienizacao_leito() from public,anon,authenticated;
drop trigger if exists trg_capturar_integracao_higienizacao_leito on public.leito_higienizacoes; create trigger trg_capturar_integracao_higienizacao_leito after insert or update of status on public.leito_higienizacoes for each row execute function public.capturar_integracao_higienizacao_leito();

create or replace function public.integrar_alta_medica_faturamento() returns trigger language plpgsql security definer set search_path='' as $$declare e text;s text;begin
 if new.status='alta' and old.status is distinct from new.status then begin perform public.sincronizar_producao_atendimento_internal(new.id); perform public.preparar_conta_pos_alta_internal(new.id); update public.integracao_pendencias set status='resolvida',resolvida_em=now(),resolvida_por=auth.uid(),updated_at=now() where empresa_id=new.empresa_id and unidade_id=new.unidade_id and status='aberta' and regra_chave='alta_faturamento_nao_preparado' and origem_tabela='atendimentos' and origem_id=new.id;
 exception when others then e:=left(sqlerrm,500);s:=sqlstate; insert into public.integracao_pendencias(empresa_id,unidade_id,atendimento_id,paciente_id,regra_chave,origem_tabela,origem_id,setor_origem,setor_destino,severidade,titulo,detalhes,contexto) values(new.empresa_id,new.unidade_id,new.id,new.paciente_id,'alta_faturamento_nao_preparado','atendimentos',new.id,'internacao','faturamento','critica','Alta com Produção/Conta pendente','Alta clínica preservada; Produção/Conta pós-alta exige regularização.',jsonb_build_object('sqlstate',s,'erro',e)) on conflict do nothing; update public.integracao_pendencias set ultima_deteccao_em=now(),updated_at=now(),contexto=jsonb_build_object('sqlstate',s,'erro',e) where empresa_id=new.empresa_id and status='aberta' and regra_chave='alta_faturamento_nao_preparado' and origem_tabela='atendimentos' and origem_id=new.id; end; end if; return new; end$$;
revoke execute on function public.integrar_alta_medica_faturamento() from public,anon,authenticated;

create or replace function public.reconciliar_pendencias_internacao_internal(p_empresa_id uuid,p_unidade_id uuid,p_atendimento_id uuid default null,p_resolvida_por uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare r int:=0;o int:=0;
begin
 insert into public.integracao_pendencias(empresa_id,unidade_id,atendimento_id,paciente_id,regra_chave,origem_tabela,origem_id,setor_origem,setor_destino,severidade,titulo,detalhes,contexto)
 select i.empresa_id,i.unidade_id,i.atendimento_id,a.paciente_id,'internacao_sem_leito_status_internado','internacoes',i.id,'internacao','nir','critica','Internação sem leito físico','Status internado exige leito físico.',jsonb_build_object('internacao_id',i.id,'setor',i.setor) from public.internacoes i join public.atendimentos a on a.id=i.atendimento_id where i.empresa_id=p_empresa_id and i.unidade_id=p_unidade_id and i.status='internado' and i.leito_id is null and(p_atendimento_id is null or i.atendimento_id=p_atendimento_id) on conflict do nothing;
 insert into public.integracao_pendencias(empresa_id,unidade_id,atendimento_id,paciente_id,regra_chave,origem_tabela,origem_id,setor_origem,setor_destino,severidade,titulo,detalhes,contexto)
 select i.empresa_id,i.unidade_id,i.atendimento_id,a.paciente_id,'internacao_leito_inconsistente','internacoes',i.id,'internacao','nir','critica','Leito e internação divergentes','Leito vinculado não está ocupado.',jsonb_build_object('leito_id',i.leito_id) from public.internacoes i join public.atendimentos a on a.id=i.atendimento_id where i.empresa_id=p_empresa_id and i.unidade_id=p_unidade_id and i.status='internado' and i.leito_id is not null and(p_atendimento_id is null or i.atendimento_id=p_atendimento_id) and not exists(select 1 from public.leitos l where l.id=i.leito_id and l.empresa_id=i.empresa_id and l.unidade_id=i.unidade_id and l.status='ocupado') on conflict do nothing;
 insert into public.integracao_pendencias(empresa_id,unidade_id,atendimento_id,paciente_id,regra_chave,origem_tabela,origem_id,setor_origem,setor_destino,severidade,titulo,detalhes,contexto)
 select d.empresa_id,d.unidade_id,d.atendimento_id,a.paciente_id,'diaria_internacao_sem_producao','internacao_diarias',d.id,'internacao','faturamento','alta','Diária sem produção','Fato diário ativo sem evento de produção.',jsonb_build_object('data_referencia',d.data_referencia) from public.internacao_diarias d join public.atendimentos a on a.id=d.atendimento_id where d.empresa_id=p_empresa_id and d.unidade_id=p_unidade_id and lower(coalesce(d.status,''))<>'cancelada' and(p_atendimento_id is null or d.atendimento_id=p_atendimento_id) and not exists(select 1 from public.producao_assistencial_eventos e where e.origem_tipo='internacao_diaria' and e.origem_id=d.id and e.status in('registrado','consolidado')) on conflict do nothing;
 insert into public.integracao_pendencias(empresa_id,unidade_id,atendimento_id,paciente_id,regra_chave,origem_tabela,origem_id,setor_origem,setor_destino,severidade,titulo,detalhes,contexto)
 select i.empresa_id,i.unidade_id,i.atendimento_id,a.paciente_id,'alta_sem_conta_faturamento','internacoes',i.id,'internacao','faturamento','critica','Alta sem conta pós-alta','Internação encerrada sem conta vinculada.',jsonb_build_object('data_alta',i.data_alta) from public.internacoes i join public.atendimentos a on a.id=i.atendimento_id where i.empresa_id=p_empresa_id and i.unidade_id=p_unidade_id and i.status='alta' and(p_atendimento_id is null or i.atendimento_id=p_atendimento_id) and not exists(select 1 from public.contas_faturamento c where c.atendimento_id=i.atendimento_id) on conflict do nothing;
 insert into public.integracao_pendencias(empresa_id,unidade_id,atendimento_id,paciente_id,regra_chave,origem_tabela,origem_id,setor_origem,setor_destino,severidade,titulo,detalhes,contexto)
 select ap.empresa_id,ap.unidade_id,ap.atendimento_id,ap.paciente_id,'alta_com_aprazamento_vencido_pendente','prescricao_aprazamentos',ap.id,'enfermagem','enfermagem','alta','Alta com aprazamento vencido','Dose devida até a alta permaneceu pendente.',jsonb_build_object('prescricao_id',ap.prescricao_id,'programado_em',ap.programado_em) from public.internacoes i join public.prescricao_aprazamentos ap on ap.atendimento_id=i.atendimento_id and ap.empresa_id=i.empresa_id and ap.unidade_id=i.unidade_id where i.empresa_id=p_empresa_id and i.unidade_id=p_unidade_id and i.status='alta' and ap.status='pendente' and ap.programado_em<=coalesce(i.data_alta,now()) and(p_atendimento_id is null or i.atendimento_id=p_atendimento_id) on conflict do nothing;
 insert into public.integracao_pendencias(empresa_id,unidade_id,atendimento_id,paciente_id,regra_chave,origem_tabela,origem_id,setor_origem,setor_destino,severidade,titulo,detalhes,contexto)
 select m.empresa_id,m.unidade_id,m.atendimento_id,a.paciente_id,'alta_sem_higienizacao_leito','movimentacoes_leitos',m.id,'internacao','nir','alta','Alta sem higienização rastreável','Leito de origem não possui ciclo de higienização.',jsonb_build_object('leito_id',m.leito_origem_id) from public.movimentacoes_leitos m join public.internacoes i on i.id=m.internacao_id join public.atendimentos a on a.id=m.atendimento_id where m.empresa_id=p_empresa_id and m.unidade_id=p_unidade_id and m.tipo='alta' and m.leito_origem_id is not null and i.status='alta' and(p_atendimento_id is null or m.atendimento_id=p_atendimento_id) and not exists(select 1 from public.leito_higienizacoes h where h.internacao_id=m.internacao_id and h.leito_id=m.leito_origem_id) on conflict do nothing;
 update public.integracao_pendencias x set status='resolvida',resolvida_em=now(),resolvida_por=p_resolvida_por,updated_at=now() where x.empresa_id=p_empresa_id and x.unidade_id=p_unidade_id and x.status='aberta' and(p_atendimento_id is null or x.atendimento_id=p_atendimento_id) and(
 (x.regra_chave='internacao_sem_leito_status_internado' and not exists(select 1 from public.internacoes i where i.id=x.origem_id and i.status='internado' and i.leito_id is null)) or
 (x.regra_chave='internacao_leito_inconsistente' and not exists(select 1 from public.internacoes i where i.id=x.origem_id and i.status='internado' and i.leito_id is not null and not exists(select 1 from public.leitos l where l.id=i.leito_id and l.empresa_id=i.empresa_id and l.unidade_id=i.unidade_id and l.status='ocupado'))) or
 (x.regra_chave='diaria_internacao_sem_producao' and not exists(select 1 from public.internacao_diarias d where d.id=x.origem_id and lower(coalesce(d.status,''))<>'cancelada' and not exists(select 1 from public.producao_assistencial_eventos e where e.origem_tipo='internacao_diaria' and e.origem_id=d.id and e.status in('registrado','consolidado')))) or
 (x.regra_chave='alta_sem_conta_faturamento' and not exists(select 1 from public.internacoes i where i.id=x.origem_id and i.status='alta' and not exists(select 1 from public.contas_faturamento c where c.atendimento_id=i.atendimento_id))) or
 (x.regra_chave='alta_com_aprazamento_vencido_pendente' and not exists(select 1 from public.prescricao_aprazamentos ap join public.internacoes i on i.atendimento_id=ap.atendimento_id where ap.id=x.origem_id and i.status='alta' and ap.status='pendente' and ap.programado_em<=coalesce(i.data_alta,now()))) or
 (x.regra_chave='alta_sem_higienizacao_leito' and not exists(select 1 from public.movimentacoes_leitos m join public.internacoes i on i.id=m.internacao_id where m.id=x.origem_id and m.tipo='alta' and m.leito_origem_id is not null and i.status='alta' and not exists(select 1 from public.leito_higienizacoes h where h.internacao_id=m.internacao_id and h.leito_id=m.leito_origem_id))) or
 (x.regra_chave='alta_faturamento_nao_preparado' and exists(select 1 from public.contas_faturamento c where c.atendimento_id=x.atendimento_id)));
 get diagnostics r=row_count;
 select count(*) into o from public.integracao_pendencias where empresa_id=p_empresa_id and unidade_id=p_unidade_id and status='aberta' and regra_chave in('internacao_sem_leito_status_internado','internacao_leito_inconsistente','diaria_internacao_sem_producao','alta_sem_conta_faturamento','alta_com_aprazamento_vencido_pendente','alta_sem_higienizacao_leito','alta_faturamento_nao_preparado') and(p_atendimento_id is null or atendimento_id=p_atendimento_id);
 return jsonb_build_object('abertas_internacao',o,'resolvidas_nesta_execucao',r);
end$$;
revoke execute on function public.reconciliar_pendencias_internacao_internal(uuid,uuid,uuid,uuid) from public,anon,authenticated;

create or replace function public.reconciliar_pendencias_integracao(p_empresa_id uuid,p_unidade_id uuid,p_atendimento_id uuid default null) returns jsonb language plpgsql security definer set search_path='public','pg_catalog' as $$
declare c jsonb;m jsonb;i jsonb;b jsonb;r int;
begin
 if auth.uid() is null then raise exception 'INTEGRACAO_AUTENTICACAO_OBRIGATORIA' using errcode='42501'; end if;
 if not public.tem_unidade(p_empresa_id,p_unidade_id) then raise exception 'INTEGRACAO_UNIDADE_FORA_ESCOPO' using errcode='42501'; end if;
 if not public.tem_permissao(p_empresa_id,p_unidade_id,'integracao.reconciliar') then raise exception 'INTEGRACAO_SEM_PERMISSAO' using errcode='42501'; end if;
 if p_atendimento_id is not null and not exists(select 1 from public.atendimentos a where a.id=p_atendimento_id and a.empresa_id=p_empresa_id and a.unidade_id=p_unidade_id) then raise exception 'INTEGRACAO_ATENDIMENTO_FORA_ESCOPO' using errcode='42501'; end if;
 c:=public.reconciliar_pendencias_cirurgia_estoque_internal(p_empresa_id,p_unidade_id,p_atendimento_id,auth.uid());m:=public.reconciliar_pendencias_medicamentos_internal(p_empresa_id,p_unidade_id,p_atendimento_id,auth.uid());i:=public.reconciliar_pendencias_internacao_internal(p_empresa_id,p_unidade_id,p_atendimento_id,auth.uid());b:=public.reconciliar_pendencias_integracao_internal(p_empresa_id,p_unidade_id,p_atendimento_id,auth.uid());
 r:=coalesce((c->>'resolvidas_nesta_execucao')::int,0)+coalesce((m->>'resolvidas_nesta_execucao')::int,0)+coalesce((i->>'resolvidas_nesta_execucao')::int,0)+coalesce((b->>'resolvidas_nesta_execucao')::int,0);
 return jsonb_build_object('abertas',coalesce((b->>'abertas')::int,0),'resolvidas_nesta_execucao',r,'abertas_medicamentos',coalesce((m->>'abertas_medicamentos')::int,0),'abertas_cirurgia_estoque',coalesce((c->>'abertas_cirurgia_estoque')::int,0),'abertas_internacao',coalesce((i->>'abertas_internacao')::int,0));
end$$;

create index if not exists idx_movimentacoes_leitos_reconciliacao_internacao on public.movimentacoes_leitos(empresa_id,unidade_id,internacao_id,tipo,movimentado_em desc);
create index if not exists idx_leito_higienizacoes_internacao_leito_status on public.leito_higienizacoes(internacao_id,leito_id,status) where internacao_id is not null;
create index if not exists idx_internacao_diarias_reconciliacao on public.internacao_diarias(empresa_id,unidade_id,atendimento_id,status,data_referencia);
