-- Painéis configuráveis + identificação no totem + autorização + roteamento pós-triagem
create table if not exists public.configuracoes_painel_chamadas (
  id bigint generated by default as identity primary key,
  unidade_id uuid not null,
  modo text not null default 'integrado' check (modo in ('integrado','setorial')),
  recepcao_chama_todos boolean not null default true,
  chamar_por_nome_apos_identificacao boolean not null default true,
  exibir_senha_apoio boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (unidade_id)
);

alter table public.senhas_atendimento add column if not exists paciente_id bigint null;
alter table public.senhas_atendimento add column if not exists atendimento_id bigint null;
alter table public.senhas_atendimento add column if not exists setor_destino_id bigint null;

create table if not exists public.autorizacoes_atendimento (
  id bigint generated by default as identity primary key,
  unidade_id uuid not null,
  atendimento_id bigint not null,
  paciente_id bigint null,
  convenio_id bigint null,
  numero_guia_prestador text null,
  numero_guia_operadora text null,
  senha_autorizacao text null,
  validade date null,
  status text not null default 'pendente' check (status in ('pendente','solicitada','autorizada','negada','dispensada')),
  observacao text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.encaminhamentos_assistenciais (
  id bigint generated by default as identity primary key,
  unidade_id uuid not null,
  atendimento_id bigint not null,
  paciente_id bigint null,
  origem text not null default 'triagem',
  especialidade text not null,
  prestador_id bigint null,
  status text not null default 'aguardando_profissional' check (status in ('aguardando_profissional','chamado','em_atendimento','concluido','cancelado')),
  prioridade text null,
  created_at timestamptz not null default now(),
  chamado_em timestamptz null,
  iniciado_em timestamptz null,
  concluido_em timestamptz null
);

create index if not exists idx_encaminhamentos_especialidade_status on public.encaminhamentos_assistenciais (unidade_id, especialidade, status, created_at);
create index if not exists idx_autorizacoes_atendimento on public.autorizacoes_atendimento (unidade_id, atendimento_id, status);

-- Regra funcional esperada pela aplicação:
-- 1. recepção abre o atendimento e, se houver convênio, cria autorização pendente;
-- 2. triagem define a especialidade clínica no atendimento;
-- 3. ao concluir triagem, cria encaminhamento_assistencial com essa especialidade;
-- 4. a fila médica deve mostrar somente encaminhamentos da especialidade vinculada ao prestador logado;
-- 5. o painel pode operar integrado ou por setor conforme configuracoes_painel_chamadas.
