import Link from "next/link";
import { Fingerprint, KeyRound, ShieldCheck, UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { SectionPage } from "@/components/painel/section-page";
import { getAssistencialContext } from "@/modules/assistencial/context";
import { registrarBiometriaPacienteAction, registrarTokenConvenioPacienteAction } from "@/modules/pacientes/identificacao-actions";

export const dynamic="force-dynamic";
export const revalidate=0;
const fmt=(v:string|null|undefined)=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(v)):"—";

type Biometria={id:string;dedo:string|null;provedor:string|null;dispositivo:string|null;identificador_externo:string|null;qualidade:number|null;consentimento_registrado:boolean;capturado_em:string;ativo:boolean};
type Token={id:string;convenio_id:string;validado:boolean;validado_em:string|null;created_at:string;origem:string|null;convenio:{nome_fantasia:string|null;razao_social:string|null}|{nome_fantasia:string|null;razao_social:string|null}[]|null};
const one=<T,>(v:T|T[]|null)=>Array.isArray(v)?v[0]??null:v;

export default async function IdentificacaoPacientePage({params,searchParams}:{params:Promise<{pacienteId:string}>;searchParams:Promise<{sucesso?:string;erro?:string}>}){
 const {pacienteId}=await params; const sp=await searchParams;
 const {supabase,empresaId}=await getAssistencialContext();
 const [pacRes,bioRes,tokenRes,convRes]=await Promise.all([
  supabase.from("pacientes").select("id,nome_completo,nome_social,ra,numero_registro,cpf,foto_path").eq("id",pacienteId).eq("empresa_id",empresaId).maybeSingle(),
  supabase.from("paciente_biometrias").select("id,dedo,provedor,dispositivo,identificador_externo,qualidade,consentimento_registrado,capturado_em,ativo").eq("empresa_id",empresaId).eq("paciente_id",pacienteId).order("capturado_em",{ascending:false}),
  supabase.from("paciente_convenio_tokens").select("id,convenio_id,validado,validado_em,created_at,origem,convenio:convenios(nome_fantasia,razao_social)").eq("empresa_id",empresaId).eq("paciente_id",pacienteId).order("created_at",{ascending:false}).limit(50),
  supabase.from("convenios").select("id,nome_fantasia,razao_social,registro_ans").eq("empresa_id",empresaId).eq("ativo",true).order("nome_fantasia"),
 ]);
 if(!pacRes.data) notFound();
 const paciente=pacRes.data; const biometrias=(bioRes.data??[]) as Biometria[]; const tokens=(tokenRes.data??[]) as unknown as Token[]; const convenios=convRes.data??[];
 return <SectionPage eyebrow="Cadastros / Pacientes / Identificação" title={paciente.nome_social||paciente.nome_completo} description={`RA ${paciente.ra} · Registro #${paciente.numero_registro} · identificação biométrica e tokens de operadora.`}>
  <div className="mb-4 flex flex-wrap gap-2"><Link href="/pacientes" className="ui-button-secondary">← Pacientes</Link></div>
  {sp.sucesso?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">Operação concluída: {sp.sucesso.replaceAll("_"," ")}.</div>:null}
  {sp.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">Falha: {decodeURIComponent(sp.erro)}.</div>:null}

  <section className="grid gap-5 xl:grid-cols-2">
   <form action={registrarBiometriaPacienteAction} className="his-card p-5"><input type="hidden" name="paciente_id" value={pacienteId}/><div className="flex items-center gap-3"><Fingerprint className="size-6 text-brand-700"/><div><h2 className="font-black">Cadastrar digital</h2><p className="text-sm text-slate-500">Recebe uma referência opaca gerada pelo SDK/serviço local do leitor. Não envie imagem bruta da impressão digital.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><select name="dedo" className="ui-input" defaultValue="indicador_direito"><option value="indicador_direito">Indicador direito</option><option value="indicador_esquerdo">Indicador esquerdo</option><option value="polegar_direito">Polegar direito</option><option value="polegar_esquerdo">Polegar esquerdo</option><option value="outro">Outro dedo</option></select><input name="provedor" className="ui-input" placeholder="SDK / fabricante do leitor"/><input name="dispositivo" className="ui-input" placeholder="Modelo / serial do leitor"/><input name="identificador_externo" className="ui-input" placeholder="ID no sistema externo"/><input name="template_ref" required className="ui-input sm:col-span-2" placeholder="Referência/token retornado pelo leitor/SDK"/><select name="base_legal" className="ui-input sm:col-span-2" defaultValue="identificacao_assistencial"><option value="identificacao_assistencial">Identificação assistencial</option><option value="execucao_contrato_saude">Execução do contrato de saúde</option><option value="tutela_saude">Tutela da saúde</option></select><label className="flex items-start gap-2 rounded-xl border border-slate-200 p-3 text-sm sm:col-span-2"><input type="checkbox" name="consentimento" className="mt-1"/><span><b>Registro de ciência/consentimento quando aplicável.</b><br/><span className="text-xs text-slate-500">A base legal deve ser definida pela política LGPD da instituição; este campo registra a evidência operacional.</span></span></label></div><button className="ui-button-primary mt-4"><Fingerprint className="size-4"/>Registrar digital</button></form>

   <form action={registrarTokenConvenioPacienteAction} className="his-card p-5"><input type="hidden" name="paciente_id" value={pacienteId}/><div className="flex items-center gap-3"><KeyRound className="size-6 text-violet-700"/><div><h2 className="font-black">Token da operadora</h2><p className="text-sm text-slate-500">Para fluxos como NDI/Hapvida: o beneficiário informa o token e o HIS registra somente o hash para auditoria.</p></div></div><div className="mt-4 grid gap-3"><select name="convenio_id" required className="ui-input" defaultValue=""><option value="">Convênio *</option>{convenios.map(c=><option key={c.id} value={c.id}>{c.nome_fantasia||c.razao_social} · ANS {c.registro_ans||"—"}</option>)}</select><input name="token" required autoComplete="one-time-code" inputMode="numeric" className="ui-input" placeholder="Token informado pelo beneficiário"/><input name="atendimento_id" className="ui-input" placeholder="Atendimento (opcional)"/><input name="origem" className="ui-input" defaultValue="app_beneficiario" placeholder="Origem do token"/></div><button className="ui-button-primary mt-4"><ShieldCheck className="size-4"/>Registrar token</button></form>
  </section>

  <section className="mt-5 grid gap-5 xl:grid-cols-2"><div className="his-card overflow-hidden"><div className="border-b p-4"><h2 className="flex items-center gap-2 font-black"><Fingerprint className="size-4"/>Biometrias cadastradas</h2></div><div className="divide-y">{biometrias.map(b=><div key={b.id} className="p-4 text-sm"><div className="flex justify-between gap-3"><div><b>{b.dedo?.replaceAll("_"," ")||"Digital"}</b><p className="text-xs text-slate-500">{b.provedor||"SDK não informado"} · {b.dispositivo||"dispositivo não informado"}</p></div><span className={`rounded-full px-2 py-1 text-xs font-black ${b.ativo?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{b.ativo?"Ativa":"Inativa"}</span></div><p className="mt-2 text-xs text-slate-400">Capturada {fmt(b.capturado_em)} · ID externo {b.identificador_externo||"—"}</p></div>)}{!biometrias.length?<p className="p-6 text-center text-sm text-slate-500">Nenhuma digital cadastrada.</p>:null}</div></div><div className="his-card overflow-hidden"><div className="border-b p-4"><h2 className="flex items-center gap-2 font-black"><UserRound className="size-4"/>Tokens recentes</h2></div><div className="divide-y">{tokens.map(t=>{const c=one(t.convenio);return <div key={t.id} className="p-4 text-sm"><div className="flex justify-between gap-3"><b>{c?.nome_fantasia||c?.razao_social||"Convênio"}</b><span className={`rounded-full px-2 py-1 text-xs font-black ${t.validado?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{t.validado?"Validado":"Pendente"}</span></div><p className="mt-1 text-xs text-slate-500">Origem {t.origem||"—"} · registrado {fmt(t.created_at)}{t.validado_em?` · validado ${fmt(t.validado_em)}`:""}</p></div>})}{!tokens.length?<p className="p-6 text-center text-sm text-slate-500">Nenhum token registrado.</p>:null}</div></div></section>
 </SectionPage>;
}
