import { Activity, ClipboardCheck, HeartPulse, ListChecks, RefreshCw, ShieldCheck, Stethoscope } from "lucide-react";
import { SectionPage } from "@/components/painel/section-page";
import { EncounterPicker } from "@/components/atendimentos/encounter-picker";
import { getAssistencialContext } from "@/modules/assistencial/context";
import { adicionarItemPlanoSAE, checarCuidadoSAE, criarPlanoCuidadosSAE, registrarAvaliacaoSAE, registrarCuidadoSAE, registrarDiagnosticoSAE, registrarPassagemPlantao } from "@/modules/assistencial/sae-actions";

export const dynamic="force-dynamic";
export const revalidate=0;

function one<T>(v:T|T[]|null){ return Array.isArray(v)?v[0]??null:v; }

export default async function SaePage({searchParams}:{searchParams:Promise<{atendimento?:string;sucesso?:string;erro?:string}>}){
  const sp=await searchParams;
  const {supabase,unidadeId}=await getAssistencialContext();
  const {data:episodios}=await supabase.from("atendimentos").select("id,numero_atendimento,data_abertura,paciente:pacientes(nome_completo,cpf,ra,numero_registro)").eq("unidade_id",unidadeId).in("status",["aberto","em_espera","em_atendimento"]).order("data_abertura",{ascending:false}).limit(300);
  const encounters=(episodios??[]).map((item)=>{const p=one(item.paciente);return{id:item.id,numero_atendimento:item.numero_atendimento,data_abertura:item.data_abertura,paciente:{nome_completo:p?.nome_completo??"Paciente",cpf:p?.cpf??null,ra:p?.ra??null,numero_registro:p?.numero_registro??null}};});
  const atendimentoId=sp.atendimento && encounters.some((e)=>e.id===sp.atendimento)?sp.atendimento:null;

  let avaliacoes:any[]=[];let diagnosticos:any[]=[];let planos:any[]=[];let cuidados:any[]=[];let passagens:any[]=[];let terminologias:any[]=[];
  if(atendimentoId){
    const [a,d,p,c,pl,t]=await Promise.all([
      supabase.from("sae_avaliacoes").select("id,historico_enfermagem,exame_fisico,riscos,assinado_em,created_at,profissional:profissionais(nome_completo)").eq("atendimento_id",atendimentoId).order("created_at",{ascending:false}).limit(20),
      supabase.from("sae_diagnosticos").select("id,codigo,diagnostico,dominio,prioridade,status,terminologia_id,created_at").eq("atendimento_id",atendimentoId).order("created_at",{ascending:false}).limit(50),
      supabase.from("sae_planos_cuidado").select("id,objetivo_geral,status,reavaliar_em,created_at").eq("atendimento_id",atendimentoId).order("created_at",{ascending:false}).limit(20),
      supabase.from("sae_cuidados").select("id,cuidado,frequencia,horario_programado,resultado_esperado,meta,ultima_checagem_em,proxima_checagem_em,status,created_at").eq("atendimento_id",atendimentoId).order("created_at",{ascending:false}).limit(100),
      supabase.from("sae_passagens_plantao").select("id,turno,resumo_clinico,pendencias,riscos,plano_proximo_turno,assinado_em,created_at,profissional:profissionais(nome_completo)").eq("atendimento_id",atendimentoId).order("created_at",{ascending:false}).limit(20),
      supabase.from("sae_terminologias").select("id,sistema,tipo,codigo,titulo,versao").eq("ativo",true).order("titulo").limit(1000),
    ]);
    avaliacoes=(a.data??[]) as unknown as any[];diagnosticos=(d.data??[]) as unknown as any[];planos=(p.data??[]) as unknown as any[];cuidados=(c.data??[]) as unknown as any[];passagens=(pl.data??[]) as unknown as any[];terminologias=(t.data??[]) as unknown as any[];
  }

  const selecionado=encounters.find((e)=>e.id===atendimentoId);
  return <SectionPage eyebrow="Assistencial / Enfermagem" title="SAE de Enfermagem" description="Avaliação, diagnósticos, resultados, intervenções, plano de cuidados, checagem e passagem de plantão no mesmo episódio assistencial.">
    {sp.sucesso?<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">Registro concluído: {sp.sucesso}.</div>:null}
    {sp.erro?<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">Não foi possível concluir: {sp.erro}.</div>:null}

    <section className="his-card p-5"><div className="mb-4 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-brand-50 text-brand-700"><Activity className="size-5"/></span><div><h2 className="font-black text-slate-900">Selecionar paciente / atendimento</h2><p className="text-sm text-slate-500">Todo o processo de enfermagem abaixo fica vinculado ao atendimento selecionado.</p></div></div><form method="get" className="flex flex-col gap-3 lg:flex-row lg:items-end"><div className="min-w-0 flex-1"><EncounterPicker encounters={encounters} name="atendimento" defaultValue={atendimentoId??undefined}/></div><button className="ui-button-primary h-11"><RefreshCw className="size-4"/>Carregar SAE</button></form></section>

    {!atendimentoId?<div className="his-card mt-5 p-10 text-center"><Stethoscope className="mx-auto size-10 text-slate-300"/><h2 className="mt-4 font-black text-slate-900">Selecione um atendimento</h2><p className="mt-2 text-sm text-slate-500">A avaliação, diagnósticos e cuidados serão carregados em uma única visão.</p></div>:<>
      <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[
        ["Avaliações",avaliacoes.length],["Diagnósticos",diagnosticos.filter((d)=>d.status==="ativo").length],["Planos",planos.filter((p)=>p.status==="ativo").length],["Cuidados",cuidados.filter((c)=>c.status!=="cancelado").length],["Passagens",passagens.length]
      ].map(([label,value])=><div key={String(label)} className="his-kpi"><p className="text-xs font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-brand-950">{value}</p></div>)}</section>
      <div className="mt-3 rounded-xl border border-brand-100 bg-brand-50 px-4 py-3 text-sm font-semibold text-brand-800">Paciente: {selecionado?.paciente.nome_completo} · Atendimento #{selecionado?.numero_atendimento}</div>

      <section className="mt-5 grid gap-5 xl:grid-cols-2">
        <form action={registrarAvaliacaoSAE} className="his-card p-6"><input type="hidden" name="atendimento_id" value={atendimentoId}/><div className="mb-5 flex items-center gap-3"><HeartPulse className="size-5 text-brand-700"/><div><h2 className="font-black">1. Avaliação de Enfermagem</h2><p className="text-xs text-slate-500">Histórico, exame físico, necessidades e riscos.</p></div></div><div className="grid gap-3">
          <textarea name="historico_enfermagem" rows={4} className="ui-input" placeholder="Histórico de enfermagem, queixas, dependência e contexto..."/><textarea name="exame_fisico" rows={4} className="ui-input" placeholder="Exame físico céfalo-caudal..."/>
          <div className="grid gap-2 sm:grid-cols-2">{[["risco_queda","Queda"],["risco_lesao_pressao","Lesão por pressão"],["risco_broncoaspiracao","Broncoaspiração"],["risco_flebite","Flebite"]].map(([n,l])=><label key={n} className="rounded-xl border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" name={n} className="mr-2"/>{l}</label>)}</div>
          <input name="outros_riscos" className="ui-input" placeholder="Outros riscos"/><div className="grid gap-3 sm:grid-cols-2"><input name="necessidade_respiracao" className="ui-input" placeholder="Respiração"/><input name="necessidade_nutricao" className="ui-input" placeholder="Nutrição / hidratação"/><input name="necessidade_eliminacao" className="ui-input" placeholder="Eliminação"/><input name="necessidade_mobilidade" className="ui-input" placeholder="Mobilidade"/><input name="necessidade_sono" className="ui-input" placeholder="Sono / repouso"/><input name="necessidade_higiene" className="ui-input" placeholder="Higiene / conforto"/></div><textarea name="observacoes" rows={2} className="ui-input" placeholder="Observações"/><button className="ui-button-primary justify-self-end">Salvar avaliação</button>
        </div></form>

        <div className="his-card p-6"><div className="mb-4 flex items-center gap-3"><ListChecks className="size-5 text-violet-700"/><h2 className="font-black">2. Diagnósticos de Enfermagem</h2></div><form action={registrarDiagnosticoSAE} className="grid gap-3"><input type="hidden" name="atendimento_id" value={atendimentoId}/><select name="terminologia_id" className="ui-input" defaultValue=""><option value="">Diagnóstico livre / sem catálogo</option>{terminologias.filter((t)=>t.tipo==="diagnostico").map((t)=><option key={t.id} value={t.id}>{t.sistema} {t.codigo} · {t.titulo}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><input name="codigo" className="ui-input" placeholder="Código"/><input name="dominio" className="ui-input" placeholder="Domínio"/></div><input name="diagnostico" required className="ui-input" placeholder="Diagnóstico de enfermagem"/><select name="prioridade" className="ui-input" defaultValue="normal"><option value="alta">Alta</option><option value="normal">Normal</option><option value="baixa">Baixa</option></select><button className="ui-button-primary justify-self-end">Adicionar diagnóstico</button></form><div className="mt-5 space-y-2">{diagnosticos.slice(0,8).map((d)=><div key={d.id} className="rounded-xl border border-slate-100 p-3"><p className="font-bold text-slate-900">{d.codigo?`${d.codigo} · `:""}{d.diagnostico}</p><p className="mt-1 text-xs text-slate-500">{d.dominio??"Sem domínio"} · prioridade {d.prioridade}</p></div>)}</div></div>

        <form action={criarPlanoCuidadosSAE} className="his-card p-6"><input type="hidden" name="atendimento_id" value={atendimentoId}/><div className="mb-4 flex items-center gap-3"><ClipboardCheck className="size-5 text-emerald-700"/><h2 className="font-black">3. Plano de Cuidados</h2></div><select name="avaliacao_id" className="ui-input" defaultValue=""><option value="">Sem avaliação vinculada</option>{avaliacoes.map((a)=><option key={a.id} value={a.id}>Avaliação {new Date(a.created_at).toLocaleString("pt-BR")}</option>)}</select><textarea name="objetivo_geral" rows={3} className="ui-input mt-3" placeholder="Objetivo geral do plano"/><label className="mt-3 block text-sm font-semibold text-slate-700">Reavaliar em<input name="reavaliar_em" type="datetime-local" className="ui-input mt-2"/></label><button className="ui-button-primary mt-4">Criar plano ativo</button></form>

        <form action={adicionarItemPlanoSAE} className="his-card p-6"><input type="hidden" name="atendimento_id" value={atendimentoId}/><h2 className="font-black">4. Resultado / Intervenção do Plano</h2><div className="mt-4 grid gap-3"><select name="plano_id" required className="ui-input" defaultValue=""><option value="">Selecione o plano</option>{planos.filter((p)=>p.status==="ativo").map((p)=><option key={p.id} value={p.id}>{p.objetivo_geral||"Plano ativo"}</option>)}</select><select name="tipo" className="ui-input" defaultValue="intervencao"><option value="resultado">Resultado esperado (NOC/local)</option><option value="intervencao">Intervenção (NIC/local)</option></select><select name="terminologia_id" className="ui-input" defaultValue=""><option value="">Sem terminologia vinculada</option>{terminologias.filter((t)=>t.tipo!=="diagnostico").map((t)=><option key={t.id} value={t.id}>{t.sistema} {t.codigo} · {t.titulo}</option>)}</select><textarea name="descricao" required rows={2} className="ui-input" placeholder="Resultado ou intervenção"/><div className="grid gap-3 sm:grid-cols-2"><input name="meta" className="ui-input" placeholder="Meta"/><input name="valor_alvo" className="ui-input" placeholder="Valor alvo"/><input name="frequencia" className="ui-input" placeholder="Frequência"/><input name="responsavel_perfil" className="ui-input" defaultValue="Enfermagem"/></div><button className="ui-button-primary justify-self-end">Adicionar ao plano</button></div></form>

        <form action={registrarCuidadoSAE} className="his-card p-6"><input type="hidden" name="atendimento_id" value={atendimentoId}/><h2 className="font-black">5. Prescrever cuidado / aprazar</h2><div className="mt-4 grid gap-3"><select name="diagnostico_id" className="ui-input" defaultValue=""><option value="">Sem diagnóstico específico</option>{diagnosticos.filter((d)=>d.status==="ativo").map((d)=><option key={d.id} value={d.id}>{d.diagnostico}</option>)}</select><input name="cuidado" required className="ui-input" placeholder="Cuidado de enfermagem"/><div className="grid gap-3 sm:grid-cols-2"><input name="frequencia" className="ui-input" placeholder="Ex.: 4/4h"/><input name="proxima_checagem_em" type="datetime-local" className="ui-input"/><input name="resultado_esperado" className="ui-input" placeholder="Resultado esperado"/><input name="meta" className="ui-input" placeholder="Meta"/></div><button className="ui-button-primary justify-self-end">Prescrever cuidado</button></div></form>

        <div className="his-card p-6"><h2 className="font-black">6. Checagem dos cuidados</h2><div className="mt-4 space-y-3">{cuidados.length?cuidados.map((c)=><form key={c.id} action={checarCuidadoSAE} className="rounded-xl border border-slate-100 p-4"><input type="hidden" name="atendimento_id" value={atendimentoId}/><input type="hidden" name="cuidado_id" value={c.id}/><p className="font-bold">{c.cuidado}</p><p className="mt-1 text-xs text-slate-500">{c.frequencia??"Sem frequência"} · última checagem {c.ultima_checagem_em?new Date(c.ultima_checagem_em).toLocaleString("pt-BR"):"—"}</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><select name="status" className="ui-input" defaultValue="realizado"><option value="realizado">Realizado</option><option value="nao_realizado">Não realizado</option><option value="recusado">Recusado</option></select><input name="justificativa" className="ui-input flex-1" placeholder="Justificativa, se necessário"/><button className="btn-secondary"><ShieldCheck className="size-4"/>Checar</button></div></form>):<p className="text-sm text-slate-500">Nenhum cuidado prescrito.</p>}</div></div>

        <form action={registrarPassagemPlantao} className="his-card p-6 xl:col-span-2"><input type="hidden" name="atendimento_id" value={atendimentoId}/><h2 className="font-black">7. Passagem de plantão assinada</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input name="turno" required className="ui-input" placeholder="Turno / equipe"/><input name="isolamento" className="ui-input" placeholder="Isolamento / precauções"/><textarea name="resumo_clinico" rows={3} className="ui-input md:col-span-2" placeholder="Resumo clínico e estado atual"/><textarea name="pendencias" rows={3} className="ui-input" placeholder="Pendências"/><textarea name="riscos" rows={3} className="ui-input" placeholder="Riscos prioritários"/><input name="dieta" className="ui-input" placeholder="Dieta"/><textarea name="plano_proximo_turno" rows={3} className="ui-input md:col-span-2" placeholder="Plano para o próximo turno"/><button className="ui-button-primary md:col-span-2 md:justify-self-end">Assinar passagem de plantão</button></div></form>
      </section>
    </>}
  </SectionPage>;
}
